pkg/controller/kogitoapp/constants/constants.go, pkg/controller/kogitoapp/definitions/build_config.go, pkg/controller/kogitoapp/definitions/build_config_runner.go, pkg/controller/kogitoapp/definitions/build_config_s2i.go, pkg/controller/kogitoapp/definitions/build_config_test.go, pkg/controller/kogitoapp/definitions/deployment_config.go, pkg/controller/kogitoapp/definitions/deployment_config_test.go, pkg/controller/kogitoapp/definitions/main.go, pkg/controller/kogitoapp/definitions/meta.go, pkg/controller/kogitoapp/definitions/meta_test.go, pkg/controller/kogitoapp/definitions/role_binding.go, pkg/controller/kogitoapp/definitions/route.go, pkg/controller/kogitoapp/definitions/service.go, pkg/controller/kogitoapp/definitions/service_account.go, pkg/controller/kogitoapp/definitions/service_test.go, pkg/controller/kogitoapp/kogitoapp_controller.go
**Note:** I'll leave this PR opened for others to take a look while we work on the redesign. 
This first PR intends to add the "definition" concept to the architecture, which are the data structures that define how the Kubernetes/OpenShift resources will be created to attend the CRD requirement.
The implementation can be viewed on `pkg/controller/<crd>/definitions`. Each file represents a Kubernetes/OpenShift resource  that know how to create each object.
@sutaakar @errantepiphany please chime in. @tchughesiv only if you have the time. :stuck_out_tongue: 
Reference: https://docs.google.com/presentation/d/1xpWaqcTbvb87_uAfNZW1EJg4zJnV5zVLwYRU04D-Kms
=> [KOGITO-84] - Introduction to definitions package

pkg/client/meta/meta.go, pkg/controller/kogitoapp/builder/builder.go, pkg/controller/kogitoapp/builder/inventory.go, pkg/controller/kogitoapp/builder/role_binding.go
See:
https://issues.jboss.org/browse/KOGITO-171
With onboarding example we get (no other services available):
```log
2019-08-21 23:50:02,513 WARN  [org.kie.kog.clo.wor.ser.dis.BaseServiceDiscovery] (executor-thread-1) Haven't found any endpoint in the namespace kogito-cli with labels employeeValidation:null
2019-08-21 23:50:02,513 ERROR [org.jbp.wor.ins.imp.WorkflowProcessInstanceImpl] (executor-thread-1) Unexpected error (id 16de14b4-9552-42a3-aa6f-d1253eb1885a) while executing node Validate employee in process instance f656ecc7-40bc-4b0c-8d87-d209d1c12ddc: org.jbpm.workflow.instance.WorkflowRuntimeException: [onboarding.onboarding:f656ecc7-40bc-4b0c-8d87-d209d1c12ddc - Validate employee:7] -- No endpoint found for service employeeValidation
```
The service discovery can now works OOTB …
=> [KOGITO-171] - Adding a custom role for service discovery

cmd/kogito/command_checks.go, cmd/kogito/delete_project.go, cmd/kogito/delete_project_test.go, cmd/kogito/delete_service.go, cmd/kogito/delete_service_test.go, cmd/kogito/deploy.go, cmd/kogito/resource_checks.go, pkg/client/kubernetes/resource.go
See:
https://issues.jboss.org/browse/KOGITO-242
In this PR:
1. Added CLI `kogito delete-service NAME [flags]` feature, which will delete a specified service
2. Added CLI `kogito delete-project NAME` feature, which will delete a specified project
=> [KOGITO-242] Adding CLI delete service and project feature

Makefile, README.md, cmd/kogito/deploy_service.go, cmd/kogito/deploy_service_test.go, deploy/crds/app_v1alpha1_kogitoapp_crd-0.4.0.yaml, deploy/olm-catalog/kogito-cloud-operator/0.4.0/app_v1alpha1_kogitoapp_crd.yaml, hack/run-e2e.sh, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/zz_generated.deepcopy.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/controller/kogitoapp/builder/build_config_s2i.go, pkg/controller/kogitoapp/builder/build_config_s2i_test.go, pkg/controller/kogitoapp/builder/build_config_test.go, pkg/controller/kogitoapp/builder/deployment_config.go, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/kogitoapp_controller_test.go, pkg/controller/kogitoapp/shared/utils.go, test/e2e/kogitoapp_test.go
See:
https://issues.jboss.org/browse/KOGITO-127
In this PR:
1. Fixed the resources used by s2i builds when deploying Kogito Runtime Services
2. Enhanced e2e tests to make it easy to verify build time
During my tests, the JVM builds (using `drools-quarkus-example` as benchmark) preformed really well with 1GB RAM and 0.5 CPUs.
For Native builds, things got really complicated and I had to raise memory to 4GB and CPU to 1 core. Unfortunately there isn't much to do since GraalVM is a resource killer.
Here's an illustration of the JVM build being limited:
=> [KOGITO-127] - Limiting s2i builds CPU and Memory resources

Makefile, hack/run-e2e.sh
See:
https://issues.jboss.org/browse/KOGITO-130
@sutaakar as we talked, here a fix to the `Makefile` to treat correctly the passed parameters to the test script. 
=> [KOGITO-130] - Fixing makefile e2e parameters

.circleci/config.yml, cmd/kogito/command/context/config.go, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/deploy/deploy_service_test.go
See:
https://issues.jboss.org/browse/KOGITO-376
The problem here was a problem with an unmarshal feature from Viper when handling timestamps. Since we are not using the "saved" KogitoApp in the config file, I removed. Once we need a cache from the created CR, we can then handle the unmarshal problem and also only save the data that will be needed.
Also, I panic'ed all errors regarding manipulating the configuration file since it's being write/read in the user's home. If we got an error there, the command flow should interrupt right away to not spawn the bug to other features.
Now let's see the CI behavior.
=> [KOGITO-376] - Removing 'LastSavedKogitoApp' to avoid marshall problems

Makefile, hack/go-build-cli.sh, vendor/github.com/google/uuid/go.mod, vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod, vendor/github.com/magiconair/properties/go.mod, vendor/github.com/mitchellh/go-homedir/go.mod, vendor/github.com/mitchellh/mapstructure/go.mod, vendor/go.opencensus.io/go.mod, vendor/gopkg.in/yaml.v2/go.mod, vendor/gopkg.in/yaml.v2/go.sum
See:
https://issues.jboss.org/browse/KOGITO-184
Small script to release the CLI bits.
@xiezhang7 @spolti  could you guys please take a look? 
```
 make build-cli release=true version=v0.5.0
```
Generates this:
```
ll build/_output/release/
total 52048
-rw-rw-r--. 1 ricferna ricferna 17754135 Oct 14 12:11 kogito-v0.5.0-darwin-amd64.tar.gz
-rw-rw-r--. 1 ricferna ricferna 17786332 Oct 14 12:11 kogito-v0.5.0-linux-amd64.tar.gz
-rw-rw-r--. 1 ricferna ricferna 17751530 Oct 14 12:11 kogito-v0.5.0-windows-amd64.zip
```
There's also mod's updates.
=> [KOGITO-184] Script for Kogito CLI release

hack/go-build-cli.sh
https://issues.jboss.org/browse/KOGITO-470
Corrected inclusion of template files into kogito cli binaries.
=> KOGITO-470: Kogito CLI cannot find operator template files when trying to install it into the namespace

cmd/kogito/command/context/root.go, cmd/kogito/version/version.go
See:
https://issues.jboss.org/browse/KOGITO-485
Small workaround to have the `kogito --version` to display the correct version. 
To have more context, please refer to the JIRA
=> [KOGITO-485] Small patch for the Kogito CLI 0.5.1 release

pkg/client/client.go, pkg/client/client_test.go
See:
https://issues.jboss.org/browse/KOGITO-498
In this PR we read from the `KUBECONFIG` env var first before trying the default path, which is `$HOME/.kube/config`.
=> [KOGITO-498] - Kogito CLI to read from KUBECONFIG before the home dir

README.md, cmd/kogito/command/test/common.go, deploy/examples/data-index.yaml, deploy/examples/jbpm-quarkus-example.yaml, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/client/client.go, pkg/client/client_test.go, pkg/client/meta/meta.go, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/resource/requested_resources_test.go, pkg/controller/kogitoapp/test/crd_validation_test.go, pkg/controller/kogitodataindex/kogitodataindex_controller.go, pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/controller/kogitodataindex/resource/manage_resources_test.go, pkg/controller/kogitodataindex/status/manage_status_test.go, pkg/infrastructure/integration.go, pkg/infrastructure/integration_test.go, pkg/infrastructure/kogito_data_index.go, pkg/infrastructure/kogito_data_index_test.go, pkg/logger/logger.go, pkg/test/client.go, pkg/util/env_var.go, pkg/util/env_var_test.go, pkg/util/envs.go, pkg/util/resources.go, pkg/util/resources_test.go, test/e2e/customresources.go, test/e2e/kogitoapp_test.go, vendor/modules.txt
See:
https://issues.jboss.org/browse/KOGITO-494
In this PR we introduce the `integration` package that will handle calls to the deployed infrastructure to inject service/URLs to the Kogito Runtime Services. For this JIRA, we're adding the Data Index route if one exists in the namespace.
Also, a small refactoring to the `CreateFakeClient` function to avoid repetition in the unit tests. If you need a mock kubernetes client, use this one from the `pkg/test` package.
=> [KOGITO-494] Injecting KOGITO_DATAINDEX_URL in kogito runtime services

pkg/controller/kogitoapp/resource/build_config_s2i.go
See:
https://issues.jboss.org/browse/KOGITO-504
OCP 4.x is resource hungry for building from source. After some investigations, I opened this bug (https://bugzilla.redhat.com/show_bug.cgi?id=1768533) and increased the limit to handle the image puller/signature step for s2i builds.
=> [KOGITO-504] - Increasing default limit to 2 CPUs and 2Gi for JVM

hack/go-build-cli.sh, hack/go-build.sh, hack/go-fmt.sh, hack/go-lint.sh, hack/go-mod-env.sh, hack/go-test.sh, hack/go-vet.sh, hack/run-e2e-cli.sh, hack/run-e2e.sh
[KOGITO-859](https://issues.jboss.org/browse/KOGITO-589)
Script ```hack/go-build-cli``` has bash-specific features such as function keyword and arrays. If shebang is #!/bin/sh and sh is a link to any shell different from bash (dash, for example), the script will fail. Making an explicit shebang #!/bin/bash resolves the issue.
=> [KOGITO-589] bash script should have bash shebang

cmd/kogito/command/project/display_project.go, cmd/kogito/command/project/display_project_test.go, cmd/kogito/command/project/factory.go
https://issues.jboss.org/browse/KOGITO-490
`kogito project` now displays the current used project.
=> KOGITO-490: Kogito CLI: Add `kogito project` to display which project has been configured.

pkg/controller/kogitoapp/resource/deployment_config.go, pkg/controller/kogitodataindex/resource/infinispan.go, pkg/controller/kogitodataindex/resource/manage_resources.go, pkg/controller/kogitodataindex/resource/manage_resources_test.go, pkg/controller/kogitodataindex/resource/statefulset.go, pkg/infrastructure/infinispan.go, pkg/util/env_var.go
See:
https://issues.jboss.org/browse/KOGITO-677
In this PR we keep the Infinispan credentials in the secret.
TODO:
=> [KOGITO-677] - Add Infinispan credentials as envfrom secret

cmd/kogito/command/shared/install_operator.go, cmd/kogito/command/shared/install_operator_test.go, cmd/kogito/command/shared/operatorhub.go, deploy/olm-catalog/kogito-operator/0.7.0-rc1/kogito-operator.v0.7.0-rc1.clusterserviceversion.yaml, pkg/client/client.go, pkg/client/meta/meta.go, pkg/util/hash.go, vendor/modules.txt
See:
https://issues.redhat.com/browse/KOGITO-703
Instead of given the annoying WARN that the Operator is available in the hub, installs it via Hb Subscription.
=> [KOGITO-703] Installs Kogito Operator if available in the OperatorHub

pkg/client/client.go, pkg/client/meta/meta.go, test/smoke/disabled/deploy_prometheus.feature, test/smoke/kubernetes.go, test/smoke/main_test.go, test/smoke/openshift.go, test/smoke/prometheus.go, test/smoke/util.go
https://issues.redhat.com/browse/KOGITO-850
=> [KOGITO-850] Add Cucumber test for Prometheus integration

deploy/olm-catalog/kogito-operator/0.7.0-rc4/kogito-operator.v0.7.0-rc4.clusterserviceversion.yaml, pkg/client/openshift/imagestream.go, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/kogitoapp_controller_test.go, pkg/controller/kogitoapp/resource/kogito_imagestream.go, pkg/controller/kogitoapp/resource/kogito_imagestream_test.go, pkg/controller/kogitoapp/resource/requested_resources.go, pkg/framework/comparator.go
See:
https://issues.redhat.com/browse/KOGITO-691
In this PR we add the possibility to have multiple image tags for the same image stream.
=> [KOGITO-691] - Creating new tags when ImageStream already exists

cmd/kogito/command/deploy/deploy_service.go, deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.8.0/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.8.0/kogito-operator.v0.8.0.clusterserviceversion.yaml, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/controller/kogitoapp/resource/deployment_config.go, pkg/controller/kogitoapp/resource/deployment_config_test.go, pkg/framework/istio.go
See:
https://issues.redhat.com/browse/KOGITO-839
In this PR we added the possibility to have istio annotations. Needs more testing, specially with the full Istio infrastructure.
Here's the image:
https://quay.io/repository/ricardozanini/kogito-cloud-operator?tab=tags (0.8.0)
@kmacedovarela
To test it, the operator must be installed via YAML files and the `kogitoApp` CRD applied. I'll be on PTO next week. Could you please try to test it? If you run into problems, please ask @radtriste that he will help you :)
=> [KOGITO-839] Adding Istio annotation to KogitoApp generated pods

pkg/client/kubernetes/event.go, pkg/client/kubernetes/kubernetes.go, test/framework/logging.go, test/framework/util.go, test/steps/data.go
https://issues.redhat.com/browse/KOGITO-1206
Example output:
```
LAST_SEEN            | FIRST_SEEN           | COUNT  | NAME                                               | KIND  | SUBOBJECT                               | TYPE    | REASON             | ACTION   | SOURCE             | MESSAGE                                                                                                               | 
2020-02-20 13:06:54  | 2020-02-20 13:06:54  | 0      | kogito-operator-564f4659db-5xkrd.15f51ae4ee7eaef0  | -     | -                                       | Normal  | Scheduled          | Binding  | default-scheduler  | Successfully assigned tradisso-local-cucumber-pchy/kogito-operator-564f4659db-5xkrd to playground-lmlv7-worker-9mhtv  | 
0001-01-01 00:00:00  | 0001-01-01 00:00:00  | 1 …
```
=> [KOGITO-1206] Bump events after scenario run

pkg/controller/kogitodataindex/kogitodataindex_controller.go, pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/infrastructure/services/deployer.go, pkg/infrastructure/services/kafka.go, pkg/infrastructure/services/resources.go
See:
https://issues.redhat.com/browse/KOGITO-993
In this PR we change the way the ConfigMap is mounted in Data Index to avoid symlinks, messing with the Data Index watcher.
Instead of having the protobuf environment variables to be added via Arrays (which doesn't have a required order), we are adding then in a sorted way to avoid this bug: 
https://github.com/RHsyseng/operator-utils/pull/44
I also removed the creation of KafkaTopics by the operator since now Strimzi is auto creating and managing those by itself. The user will be able to change and adjust them accordingly via Strimzi. Was causing a side effect in the ConfigMap tests with Data Index.
Please make sure that your PR meets …
=> [KOGITO-993] Removing annoying symlinks from protobuf configMaps

go.mod, go.sum, pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/infrastructure/services/deployment.go, pkg/infrastructure/services/image.go, pkg/infrastructure/services/image_test.go, pkg/infrastructure/services/manage_status.go, pkg/infrastructure/services/resources.go, pkg/infrastructure/services/resources_test.go, pkg/test/image.go
See:
https://issues.redhat.com/browse/KOGITO-1255
In this PR we reinvented the way we add images to Deployment resources. Now the Operator will wait for the ImageStream to be ready to create the Deployment resource. In case you change the image, we just hold the old value until the OpenShift triggers us again.
Bonus: we fixed the annoying sort bug that made a lot of reconciliation updates until the environment variables were in the order it wants. This one is from the operator-utils, that's why we changed the `go.mod`file.
I'll rebase this PR once we merge https://github.com/kiegroup/kogito-cloud-operator/pull/196
I've decided to submit this one to move the clutter before starting working on the binary builds.
Would be awesome to have …
=> [KOGITO-1255] - Handling Deployment Images like a boss 

Makefile, deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml, deploy/examples/data-index.yaml, deploy/examples/example-custom-build-images.yaml, deploy/examples/jbpm-quarkus-example-persistence.yaml, deploy/examples/jbpm-quarkus-example.yaml, deploy/examples/kogito-kafka-quickstart-quarkus.yaml, deploy/examples/onboarding-example.yaml, deploy/olm-catalog/kogito-operator/0.8.0/kogito-operator.v0.8.0.clusterserviceversion.yaml, deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml, hack/scorecard.sh
See:
https://issues.redhat.com/browse/KOGITO-1396
This commit contains small adjustments for the OperatorHub PR.
=> [KOGITO-1396] Adjustments for 0.8.0 release

test/framework/kubernetes.go, test/framework/operator.go, test/framework/util.go, test/main_test.go, test/steps/data.go
https://issues.redhat.com/browse/KOGITO-1408
Workaround int tests until KOGITO-1376 is implemented, as we would like the kogito pipelines to run correctly.
=> [KOGITO-1408] Install missing dependent crd before start of test

cmd/kogito/command/deploy/common.go, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/deploy/deploy_service_test.go
See:
https://issues.redhat.com/browse/KOGITO-1431
In this PR we took a simple approach to solve the comma problems and added unit tests to verify the bug as reported in the JIRA.
=> [KOGITO-1431] - Fix env parameter problem with commas

pkg/controller/kogitodataindex/kogitodataindex_controller.go, pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/controller/kogitojobsservice/kogitojobsservice_controller.go, pkg/infrastructure/services/deployer.go, pkg/infrastructure/services/deployment.go, pkg/infrastructure/services/deployment_test.go, pkg/infrastructure/services/probe.go
See:
https://issues.redhat.com/browse/KOGITO-586
In this PR we introduce a way of services to fine tune their probe type based on the new health checks added in the Data Index and Jobs Services.
=> [KOGITO-586] - Add Quarkus probes to Kogito Services definition

hack/go-vet.sh
https://issues.redhat.com/projects/KOGITO/issues/KOGITO-1516
Use the canonical path ("github.com/kiegroup/kogito-cloud-operator")
instead of the relative path as argument to the "-i" flag when running
the openapi-gen command, allowing this script to be ran from any
directory without making any modifications.
=> [KOGITO-1516] Allow "make vet" to work from any directory

cmd/kogito/command/install/jobs_service.go, cmd/kogito/command/install/jobs_service_test.go, deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml, deploy/olm-catalog/kogito-operator/0.9.0/app.kiegroup.org_kogitojobsservices_crd.yaml, pkg/apis/app/v1alpha1/kogitojobsservice_types.go, pkg/apis/app/v1alpha1/zz_generated.deepcopy.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/controller/kogitojobsservice/kogitojobsservice_controller.go, pkg/infrastructure/services/kafka.go, pkg/infrastructure/services/resources.go
See:
https://issues.redhat.com/browse/KOGITO-851
Depends on:
https://github.com/kiegroup/kogito-images/pull/114
Image for testing:
`quay.io/ricardozanini/kogito-jobs-service:0.9.0-rc1`
In this PR we introduce the Kafka integration with Jobs Service. When any parameter is set (URL, service instance or `useKogitoInfra`), eventing is automatically enabled in the Jobs Service image.
=> [KOGITO-851] Adding event support to Jobs Service

README.md, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/resource/deployed_resources.go, pkg/controller/kogitoapp/resource/deployed_resources_test.go, pkg/controller/kogitoapp/resource/deployment_config.go, pkg/controller/kogitoapp/resource/deployment_config_test.go, pkg/controller/kogitoapp/resource/requested_resources.go, pkg/controller/kogitoapp/resource/requested_resources_test.go, pkg/controller/kogitoapp/resource/resources.go, pkg/controller/kogitoapp/resource/service_test.go, pkg/controller/kogitodataindex/kogitodataindex_controller.go, pkg/controller/kogitojobsservice/kogitojobsservice_controller.go, pkg/infrastructure/services/configmap.go, pkg/infrastructure/services/configmap_test.go, pkg/infrastructure/services/resources.go, pkg/infrastructure/services/resources_test.go
Jira: https://issues.redhat.com/browse/KOGITO-1193
Description: Quarkus and Springboot support application.properties override based on a directory in the file system. We could leverage from this to mount ConfigMaps to the deployed Kogito Services (either provided or built) for users to fine tune their configuration, not having to always rely on environment variables for that.
Implementation: Calculate the content hash of the `application.properties` of the config map in the reconcile loop. Store the content hash as an annotation of the deployment of the services. When the content hash changes, the deployment will rolling update.
Test: Only tested with quarkus for kogito runtime service and data index service. Springboot and Jobs service should work in the same way. 
Many thanks for …
=> [KOGITO-1193] Mount Config Maps for Kogito Services and Runtimes application properties configuration

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/README.md, test/config/config.go, test/features/install_mgmtconsole.feature, test/framework/kogitomgmtconsole.go, test/steps/data.go, test/steps/kogitomgmtconsole.go
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1002
Description: As part of https://issues.redhat.com/browse/KOGITO-755, operator will be able to provision the management console via CR.
How to run tests:
```
../hack/run-tests.sh --feature "features/install_mgmtconsole.feature" --disabled_crds_update --operator_image quay.io/jcarvaja/kogito-cloud-operator --services_image_version 0.9.0-rc2 --cr_deployment_only
```
=> KOGITO-1002: Cucumber Tests: Test Management Console provisioning via CR

cmd/kogito/command/completion/completion.go, cmd/kogito/command/completion/factory.go, cmd/kogito/command/context/command_context.go, cmd/kogito/command/deploy/delete_service.go, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/deploy/factory.go, cmd/kogito/command/install/data_index.go, cmd/kogito/command/install/factory.go, cmd/kogito/command/install/infinispan.go, cmd/kogito/command/install/install.go, cmd/kogito/command/install/jobs_service.go, cmd/kogito/command/install/kafka.go, cmd/kogito/command/install/keycloak.go, cmd/kogito/command/install/kogito_operator.go, cmd/kogito/command/install/mgmt_console.go, cmd/kogito/command/project/delete_project.go, cmd/kogito/command/project/display_project.go, cmd/kogito/command/project/factory.go, cmd/kogito/command/project/new_project.go, cmd/kogito/command/project/use_project.go, cmd/kogito/command/remove/factory.go, cmd/kogito/command/remove/infinispan.go, cmd/kogito/command/remove/kafka.go, cmd/kogito/command/remove/keycloak.go, cmd/kogito/command/remove/remove.go, cmd/kogito/command/remove/runtime_services.go, cmd/kogito/command/remove/runtime_services_test.go, cmd/kogito/command/test/common.go
See:
https://issues.redhat.com/browse/KOGITO-1258
In this PR we introduce a way to remove kogito services via command line.
=> [master][KOGITO-1258] - Adding 'remove' CLI commands to runtime support services

README.md, cmd/kogito/command/install/jobs_service.go, deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml, deploy/examples/data-index.yaml, deploy/olm-catalog/kogito-operator/0.10.0/kogito-operator.v0.10.0.clusterserviceversion.yaml, pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller_test.go, pkg/infrastructure/data_index.go, pkg/infrastructure/data_index_test.go, pkg/infrastructure/integration_test.go, pkg/infrastructure/jobs_service.go, pkg/infrastructure/kogito_service_test.go, pkg/infrastructure/services/deployer_test.go, pkg/infrastructure/services/resources_test.go, test/features/install_dataindex.feature, test/features/install_jobs_service.feature, test/features/olm/cli_install_operator.feature, test/features/olm/cli_new_project.feature, test/features/olm/cli_use_project.feature
See:
https://issues.redhat.com/browse/KOGITO-1688
In this PR we reviewed the entire naming for Data Index, Management Console and Jobs Service used internally and for the default examples/CR.
=> [master][KOGITO-1688] - Renaming Kogito Support Services

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/features/kogito_service_performance.feature, test/framework/http.go, test/framework/logging.go, test/main_test.go, test/steps/data.go, test/steps/http.go
So guys,
it's finally here. A couple of things to be noted about the reporting:
* The metric which I am measuring now (create a given number of processes) is measured in the `executePostRequestsWithOptionalReportingUsingThreadsOnServiceWithPathAndBody` step function which calls `ExecuteHTTPRequestsInThreads` from the framework. At first, I tried to measure just the loop where requests are made inside the `ExecuteHTTPRequestsInThreads` function, but that would mean to push the `report` parameter and also the name of the metric into that function, so it wouldn't be as general as it is now. And when I measured it, the difference when measuring just requests and requests also with other nearby code was less than 1 ms, which is something I think we can live with as results are in seconds. Also …
=> [master][KOGITO-1044] - Kogito runtime performance and load tests

pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/kogitoservices_types.go, test/features/deploy_quarkus_service.feature, test/features/deploy_service_resources.feature, test/features/deploy_springboot_service.feature, test/features/install_dataindex.feature, test/features/kogito_service_performance.feature, test/features/prometheus.feature, test/features/service_discovery.feature, test/framework/kogitoapp.go, test/steps/kogitoapp.go, test/steps/openshift.go, test/steps/utils.go
Configuration table for KogitoApp:
|first column|second column|third column|
|------|------|------|
|config|native|enabled/disabled|
|config|persistence|enabled/disabled|
|config|events|enabled/disabled|
|build-env|\<name>|\<value>|
|runtime-env|\<name>|\<value>|
|label|\<name>|\<value>|
|build-request|\<name>|\<value>|
|build-limit|\<name>|\<value>|
|runtime-request|\<name>|\<value>|
|runtime-limit|\<name>|\<value>|
Steps added by @Sgitario which need to check requests and limits will use the subset of that table.
By default, if `JAVA_OPTIONS` env variable is not set, it will be set to `-Xmx2G` so we have more stable resources assignment to test with.
Let me know what you think about it.
=> KOGITO-1699 - Unify configuration for KogitoApp deployments in BDD tests

cmd/kogito/command/install/data_index.go, pkg/infrastructure/services/deployer.go, pkg/infrastructure/services/deployer_test.go
Currently the UseKogitoInfra flag is set to true even when external kafka is provided
See for more info - https://issues.redhat.com/browse/KOGITO-2012
Using external kafka instance or url when external kafka instance or url is provided
Signed-off-by: TARUN KHANDELWAL <tarkhand@redhat.com>
=> [KOGITO-2012] - Impossible to configure external Kafka for Data index using kafka-instance CLI parameter

pkg/apis/app/v1alpha1/kogitoservices_types.go, pkg/client/client.go, pkg/client/meta/meta.go, test/features/kogito_service_performance.feature, test/framework/infinispan.go, test/framework/kogitoapp.go, test/framework/kubernetes.go, test/framework/openshift_resources.go, test/steps/infinispan.go, test/steps/kogitoapp.go, test/steps/kogitodataindex.go, test/steps/utils.go
https://issues.redhat.com/browse/KOGITO-1700
Things to discuss:
1. I found that for Infinispan env vars we use 2 maps (Quarkus/Spring Boot) in the operator framework:
https://github.com/kiegroup/kogito-cloud-operator/blob/d967c4f6331ab79d4ee71906058dd1bad2035bce/pkg/controller/kogitoapp/resource/deployment_config.go#L69-L82
But they are not public, so I cannot use them and have to use my own, see the `addInfinispanEnvVars` method. Basically I have to use if now. Can we make them public so they can be used in the test framework, wdyt?
2. I created the `KogitoAppHolder` to follow the pattern of `KogitoServiceHolder` in the framework. For KogitoApp it is not needed on the framework side right now (not used in the framework at all, just in the steps) but I wanted to be consistent with …
=> KOGITO-1700 - Add optional configuration of Infinispan in BDD

Jenkinsfile, Jenkinsfile.nightly, hack/run-tests.sh, test/README.md, test/framework/kubernetes.go, test/framework/namespace.go, test/scripts/prune_namespaces.go
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-2192
Description: Create a namespace history log to delete the namespaces in case of test framework didn't end well and therefore it could not delete it.
Requirements:
- Create history file
- Append the namespaces to the history file (for parallel test executions)
- Delete namespace from history in case of the test deleted the namespace
- Provide an utility go function to prune the rest of namespaces from history
=> KOGITO-2192: BDD tests: Should provide a file with created namespaces

test/framework/http.go, test/framework/process.go, test/framework/task.go, test/steps/http.go
https://issues.redhat.com/browse/KOGITO-1729
JIRA was created as a result of the feedback in https://github.com/kiegroup/kogito-cloud-operator/pull/257#discussion_r403309366.
Things to discuss:
1. Name of the struct is `HTTPRequestInfo`.
I didn't want to name it `HTTPRequest` as then the parameter name, e.g. `request`, would clash with the actual request from Go's http package and it would be confusing in methods like for example here:
https://github.com/kiegroup/kogito-cloud-operator/blob/e9069757dcc2fa0068019cc3a76d49a90719f139/test/framework/http.go#L53-L56 I was also considering `HTTPRequestData` but this isn't just data and `HTTPRequestMetaData` but that's too long. The parameter would then need to be something like `requestMetaData` etc.
1. I think the goal of the JIRA was achieved, …
=> [KOGITO-1729] Consolidate HTTP Request parameters into one struct type

hack/clean-stuck-namespaces.sh, hack/run-tests.sh
https://issues.redhat.com/browse/KOGITO-2350
Script is called after tests are run and namespaces are pruned
=> [KOGITO-2350] Cleanup stuck namespaces (infinispan)

test/features/deploy_kogito_runtime.feature
https://issues.redhat.com/browse/KOGITO-2358
Adds a new scenario that deploys the optaplanner-quarkus example to OpenShift via the operator and checks the application is responding. 
Motivation: we have similar scenarios for a couple of other examples, but until now any automated end-to-end check for OptaPlanner has been missing.
Sorry for the extra changes due to formatting (automatic removal of trailing spaces done by IDE).
=> [KOGITO-2358] Add a scenario for optaplanner-quarkus on OpenShift

test/framework/kubernetes.go, test/framework/openshift.go
JIRA: https://issues.redhat.com/browse/KOGITO-2162
Description: As this issue is no longer happening, this PR is about to revert the workaround done as part of https://github.com/kiegroup/kogito-cloud-operator/pull/342
=> KOGITO-2162: Revert workaround

hack/install.sh
See: https://issues.redhat.com/browse/KOGITO-2524
Small renaming to fit the [docs description](https://docs.jboss.org/kogito/release/latest/html_single/#proc-kogito-deploying-on-kubernetes_kogito-deploying-on-openshift).
=> [KOGITO-2524] - Renaming install script command to fit k8s docs 

test/framework/check_setup.go, test/framework/kogitoruntime.go, test/framework/kogitoserviceutils.go, test/framework/kubernetes.go
JIRA: https://issues.redhat.com/browse/KOGITO-2466
Description:
- Use the port settings from the kogito service specification.
=> KOGITO-2466: BDD tests: Update Port in Ingress for KogitoRuntime

pkg/client/client.go, pkg/framework/controller_watcher.go
See: https://issues.redhat.com/browse/KOGITO-2404
Small fix to do not show WARN messages about OpenShift objects not being registered.
=> [KOGITO-2404] Fix WARN when registering OpenShift components on k8s

test/framework/maven.go
https://issues.redhat.com/browse/KOGITO-2611
Happened indirectly by https://github.com/kiegroup/kogito-cloud-operator/commit/646502b97ec193bb17fe2b4f585b750dc34b6f2d solved the `skipTests` because the append of options should be done all separately and not in a string.
Do not affect PR check as it happens if many `otherOptions`, can be seen when using a specific repository
=> [KOGITO-2611] BDD tests: `otherOptions` append corrected

pkg/apis/app/v1alpha1/kogitoservices_types.go, test/features/update_httpport.feature, test/framework/kogitoserviceutils.go, test/steps/kogito_service_table_parser.go
JIRA: https://issues.redhat.com/browse/KOGITO-2438
Description: All the Kogito Services (Data Index, Jobs Service, Management and runtimes) now includes a new field in KogitoServiceSpec to specify the HTTP port to use.
=> KOGITO-2438: Cover Port changes configuration for Kogito services

Jenkinsfile.deploy, Jenkinsfile.promote, Makefile, hack/go-build.sh
https://issues.redhat.com/browse/KOGITO-2435
and added skip tests parameter
=> [KOGITO-2451] Migrate nightly pipelines to RHBA

deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/crds/app.kiegroup.org_kogitobuilds_crd.yaml, deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitobuilds_crd.yaml, examples/process-quarkus-example-runtime-build-webhook.yaml, examples/process-quarkus-example-runtime-build.yaml, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/kogitobuild_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go
See:
https://issues.redhat.com/browse/KOGITO-2688
This needs to be on 0.12.0, otherwise users will fail to install all the CRDs in Kubernetes 1.18, like the newer minikube.
=> [KOGITO-2688] Removing listType=map from non-required objects

.github/workflows/Kogito-Operator-PR-Check.yaml
https://issues.redhat.com/browse/KOGITO-2692
=> KOGITO-2692 codecov changed with GH actions

Jenkinsfile.deploy, test/features/deploy_quarkus_service.feature
https://issues.redhat.com/browse/KOGITO-2723
After testing of 0.12.0, there were some small adjustments on deploy pipeline.
=> [KOGITO 2723] Post-release updates

pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/framework/comparator.go, pkg/framework/comparator_test.go, pkg/infrastructure/services/resources.go
See: https://issues.redhat.com/browse/KOGITO-2797
In this PR we introduce a fix to the `Deployment` and `DeploymentComparator` to avoid infinite reconciliation triggers when reading a given volume.
@sutaakar I wasn't able to test on a cluster yet, could you please give it a quick try? Also, do you think it's feasible to have a BDD test for this scenario as well? I think it's important. Thanks!
=> [KOGITO-2797] - Fixing Deployment comparator

hack/bump-version.sh
https://issues.redhat.com/browse/KOGITO-2795
The script guess the `oldVersion` from `./hack/export-version.sh` script.
Also, test config is set depending on `release` parameter or not.
Normal change of version:
```
./hack/bump-version.sh 0.14.0
```
It should set test config to `latest` and `master`.
Release change of version:
```
./hack/bump-version.sh 0.14.0 true
```
It should set the test config according to the given version: branch `0.14.x` and version to `0.14.0`
If no release branch has been created, use:
```
./hack/bump-version.sh 0.14.0 true true
```
and it will keep the examples-ref on master
=> [KOGITO-2795] Update bump-version.sh script

deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.13.0/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go
See: https://issues.redhat.com/browse/KOGITO-2813
Minor change to not distinguish between `KogitoApp` and a custom Kogito sevice represented by a `KogitoRuntime` CR. 
=> [KOGITO-2813] - Renaming KogitoApp description to KogitoService, Fixes #462

hack/install-manifests.sh, pkg/apis/app/v1alpha1/conditions_test.go, pkg/framework/comparator.go, pkg/framework/comparator_test.go
See: https://issues.redhat.com/browse/KOGITO-2872
In this PR we introduce a little fix to our comparators to relax Triggers equality on `BuildConfig` spec. On OCP 4.5 this field, when empty, is treated as a nil value. On former versions this attribute was an empty array. That was accusing our structure to be different from the requested and deployed ones.
=> [KOGITO-2872] BuildConfig comparator to handle empty and nil Triggers

cmd/kogito/command/completion/completion.go
See: https://issues.redhat.com/browse/KOGITO-2916
After running `kogito completion fish > ~/.config/fish/completions/kogito.fish`, the auto-completion for `fish` works and looks like such:
I also updated the [long description](https://github.com/Kevin-Mok/kogito-cloud-operator/blob/7d0b02e21434641f5ec48fd8078e89e1ed6f54b7/cmd/kogito/command/completion/completion.go#L50-L77) for `kogito completion --help` to match [Cobra's latest long description](https://github.com/spf13/cobra/blob/master/shell_completions.md#generating-shell-completions).
=> [KOGITO-2916] CLI auto-completion for fish shell

.github/pull_request_template.md
See: https://issues.redhat.com/browse/KOGITO-2917
I put a direct link instead of a relative link because they don't seem to work properly as a template. If you play around with the [preview in a PR](https://github.com/kiegroup/kogito-cloud-operator/compare/master...Kevin-Mok:KOGITO-2917?expand=1), you can see that no relative links work properly.
Using the relative link `../` so that it links to the project base directory produces the link: https://github.com/kiegroup/kogito-cloud-operator/README.md#contributing-to-the-kogito-operator. However, you need the `blob/master` to produce a valid link: https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator.
Trying to link to the header directly (`(#contributing-to-the-kogito-operator)`) to try …
=> [KOGITO-2917] Update contributors' guide link in PR template

cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/deploy/deploy_service_test.go, cmd/kogito/command/flag/build_flag.go
See: https://issues.redhat.com/browse/KOGITO-1925
The task description says to add a warning in the logs if the user tries to do a native build but ends up doing a binary build. I chose to just not allow the user to do the native build without specifying a source. This is because they specifically want a native build, so we should force the user to specify the source for in order for it to work; else, they can just remove the native flag and be aware they are doing a binary build.
I accidentally initially did this task on my local repo that was 25 commits behind `master`...  :sweat_smile: But while I was doing that, I noticed that there were [way more tests in `cmd/kogito/command/deploy/deploy_service_test.go`](https://github.com/Kevin-Mok/kogito-cloud-operator/blob/KOGITO-1925-old/cmd/kog …
=> [KOGITO-1925] CLI: force native build to use s2i

test/features/deploy_kogito_build.feature, test/framework/kogitobuild.go, test/framework/mappers/cr_to_cli.go, test/framework/openshift.go, test/steps/mappers/create_kogito_build.go, test/steps/openshift.go
JIRA: https://issues.redhat.com/browse/KOGITO-2771
Description: Cover that the kogito cloud operator initialises correctly the build config in Openshift.
=> KOGITO-2771: Cucumber Tests: Cover Webhooks in KogitoBuild

pkg/framework/comparator.go, pkg/framework/comparator_test.go
See: https://issues.redhat.com/browse/KOGITO-2957
In this PR we ignore the injected `K_SINK` environment variable by Knative Eventing when comparing `PodTemplate`s to be full compatible of their way of service discovery mechanism. More info: https://knative.dev/docs/eventing/migration/sinkbinding/
=> [KOGITO-2957] Considering K_SINK env var when comparing Deployments

hack/go-build-cli.sh
See: https://issues.redhat.com/browse/KOGITO-3005
I ran `./hack/go-build-cli.sh true 0.14.0` to produce `kogito-cli-0.14.0-windows-amd64.zip` (contains `kogito.exe`) which I uploaded [here](https://github.com/Kevin-Mok/kogito-cloud-operator/releases/download/7.31.0/kogito-cli-0.14.0-windows-amd64.zip). Extracting it and running it works without asking which program to use it with:
```
PS C:\Users\Kevin> C:\Users\Kevin\Downloads\kogito.exe
{"level":"warn","T":"2020-08-07T17:08:47.685-0400","logger":"client_api","msg":"Kubernetes local configuration 'C:\\Users\\Kevin/.kube/config' is empty."}
{"level":"warn","T":"2020-08-07T17:08:47.686-0400","logger":"client_api","msg":"Make sure to login to your cluster with oc/kubectl before using this tool"}
panic: Impossible to get Kubernetes local …
```
=> [KOGITO-3005] Add exe extension to Windows CLI

pkg/framework/comparator.go, pkg/framework/comparator_test.go, pkg/framework/env_var.go, pkg/framework/env_var_test.go
See: https://issues.redhat.com/browse/KOGITO-3032
Knative 0.16 introduces a new variable being injected in the SinkBinding sources. Instead of keeping ignoring known env vars that could be injected, we are now ignoring any variables injected by other managers. This would also allow users to add a new env var to their deployment to make quick tests or something they need (through the web ui). For long term envs, they would still use the `KogitoService` interface as the recommended approach.
Keeping up to the Knative/Istio changes and injection in our PodSpecTemplate resources would be a pain to maintain.
I also removed unused functions from the `framework` package.
Please make sure that …
=> [KOGITO-3032] - Ignoring any injected variables on PodSpecTemplate

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3045
If pipeline is unstable due to tests failing, then we still push to registry but properties were not set because of `success` post whereas the pipeline is no more success ...
Properties will be set normally after the push and PR created
=> [KOGITO-3045] Set image's deployment properties

cmd/kogito/command/command.go, cmd/kogito/command/context/logger.go, pkg/logger/logger.go
See: https://issues.redhat.com/browse/KOGITO-3063
This is incredible. We should take control of the CLI for testing purposes, but instead we were setting to `nil`. We should be fine now. Tested redirecting the output to `/dev/null` like `kogito install data-index >/dev/null`. It's working.
=> [KOGITO-3063] Redirecting kogito CLI default output to stdout

cmd/kogito/command/install/infinispan.go, cmd/kogito/command/install/kafka.go, cmd/kogito/command/install/keycloak.go, deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml, deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
See: https://issues.redhat.com/browse/KOGITO-3148
In this PR we removed the CSV required field, so OLM won't install third party operators any more when installing Kogito Operator.
We're missing the docs PR to add links to the installation pages of Strimzi and Infinispan.
=> [KOGITO-3148] - Remove third party required dependencies from CSV

deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml, deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml, pkg/apis/app/v1alpha1/kogitobuild_types.go, pkg/apis/app/v1alpha1/kogitodataindex_types.go, pkg/apis/app/v1alpha1/kogitoinfra_types.go, pkg/apis/app/v1alpha1/kogitojobsservice_types.go, pkg/apis/app/v1alpha1/kogitomgmtconsole_types.go, pkg/apis/app/v1alpha1/kogitoruntime_types.go, pkg/apis/app/v1alpha1/kogitotrusty_types.go
JIRA: https://issues.redhat.com/browse/KOGITO-3104
For the resources showing I was able to test this for `KogitoRuntime` and `KogitoBuild` objects with these latest changes
For KogitoRuntime using the contents:
```
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
name: process-business-rules-quarkus
spec:
replicas: 1
image:
domain: quay.io
name: process-business-rules-quarkus
tag: latest
namespace: kaitou786
```
Resources:
For KogitoBuild I tested with creating an object directly through openshift console, with a default value
Resources:
If you want to test this you can use my registry image: `quay.io/kaitou786/temp-registry:latest` with these changes in CSV
And follow this [guide](https://www.openshift.com/blog/openshift-4-3-managing-catalog-sources-in-the-openshift-web …
=> [KOGITO-3104] - Missing Resources for Operator CRs

test/features/install_trusty.feature
https://issues.redhat.com/browse/KOGITO-3176
The outgoing topic trusty-explainability-request is not created by the kafka operator. So the trusty service keeps working but from an health perspective it is in error. I'm disabling the test as long as a fix is implemented
=> KOGITO-3176 - disable standalone trusty test due to kafka change

test/features/install_trusty.feature
=> [0.15.x] KOGITO-3176 - disable standalone trusty test due to kafka change

test/features/integration/keycloak.feature
JIRA: https://issues.redhat.com/browse/KOGITO-3333
Description: Rewriting scenario to check whether the route is forbidden.
=> KOGITO-3333: Refactor Jobs Service test with keycloak

cmd/kogito/command/service/buildresource_service.go, cmd/kogito/command/service/buildresource_service_test.go
See: https://issues.redhat.com/browse/KOGITO-3350
This PR adds a helper function to convert a GitHub link to a file in a repo to its raw URL so that it can be downloaded correctly.
I wrote unit tests to check the conversion of a URL to a file in a specific branch and commit. I also ran an s2i build of a BPMN file which was able to deploy correctly.
=> [KOGITO-3350] CLI fails to download GitHub file properly

.github/workflows/Kogito-Operator-PR-Check.yaml, hack/bump-version.sh, hack/bump-version.sh.bats
https://issues.redhat.com/browse/KOGITO-3127
Csv fields are now corrected after the `make vet`
This is done as we may be coming from `1.0.0-snapshot`. latest released version is now taken from `deploy/olm-catalog/kogito-operator` directories.
=> [KOGITO-3127] Set the `replaces` correctly in csv

examples/data-index.yaml, examples/explainability.yaml, examples/jobs-service.yaml, examples/process-quarkus-example-persistence.yaml, examples/travelapp-kogito-travel-agency.yaml, examples/travelapp-kogito-visas.yaml, examples/trusty.yaml, pkg/controller/kogitoinfra/infinispan/infinispan_properties.go, pkg/controller/kogitoinfra/kogitoinfra_controller_test.go
https://issues.redhat.com/browse/KOGITO-3502
=> [KOGITO-3502] - Sasl mechanism no longer set by Kogito operator

hack/go-vet.sh, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/controller/kogitoexplainability/kogitoexplainability_controller_test.go, pkg/controller/kogitoinfra/kogitoinfra_controller_test.go, pkg/controller/kogitotrusty/kogitotrusty_controller_test.go, pkg/framework/containers.go, pkg/infrastructure/services/route.go
See: https://issues.redhat.com/browse/KOGITO-3516
Now any service can be called via `http://name.namespace` from the cluster.
=> [KOGITO-3516] Services now listen to default HTTP port

examples/kubernetes/travel-agency/deploy.sh
Getting below error while running deploy.sh(/examples/kubernetes/travel-agency/deploy.sh) script to deploy travel-agency example on Kuberentes 
> error: the path "./deploy/examples/kubernetes/travel-agency/data-index.yaml" does not exist
> error: the path "./deploy/examples/kubernetes/travel-agency/data-index-ingress.yaml" does not exist
> Deploying Management Console
> error: the path "./deploy/examples/kubernetes/travel-agency/management-console.yaml" does not exist
> error: the path "./deploy/examples/kubernetes/travel-agency/management-console-ingress.yaml" does not exist
> Deploying Kogito Travels Application
> error: the path "./deploy/examples/kubernetes/travel-agency/kogito-travels.yaml" does not exist
> error: the path "./deploy/examples/kubernetes/travel-agency/kogito-travels-ing …
=> Fix EXAMPLES_DIR path

.github/pull_request_template.md, RELEASE_NOTES.md
@Kaitou786 can we add an option to the bot to also comment in the PR when RELEASE_NOTES.md is not updated for changes on the operator (do not consider BDD changes)?
=> Updating Release Notes to 1.1.0

RELEASE_NOTES.md, cmd/kogito/command/deploy/delete_service.go, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/deploy/deploy_service_test.go, cmd/kogito/command/deploy/testdata/greetings.sw.json, cmd/kogito/command/iozip/zip_files.go, cmd/kogito/command/service/build_service.go, cmd/kogito/command/shared/install_operator_test.go, cmd/kogito/command/shared/resource_checks_test.go, cmd/kogito/command/test/common.go, go.mod, go.sum, pkg/client/client.go
See: https://issues.redhat.com/browse/KOGITO-3968
To deploy the [SW greetings example](https://github.com/kiegroup/kogito-examples/tree/master/serverless-workflow-greeting-quarkus) from the source, do:
```bash
$ kogito deploy sw-greetings cmd/kogito/command/deploy/testdata/greetings.sw.json --image-runtime quay.io/kiegroup/kogito-quarkus-jvm-ubi8:1.0 --image-s2i quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0
Kogito Build Service successfully installed in the Project kogito-3968.
Check the Service status by running 'oc describe kogitobuild/sw-greetings -n kogito-3968'
File(s) found: cmd/kogito/command/deploy/testdata/greetings.sw.json.
Triggering the new build
The requested file(s) was successfully uploaded to OpenShift, the build …
```
=> [KOGITO-3968] - Add support to deploy Kogito services from SW files

Jenkinsfile, Jenkinsfile.deploy, hack/go-lint.sh
https://issues.redhat.com/browse/KOGITO-4004
instead of disabling full build, only lock the BDD tests part
=> [KOGITO-4004] Encapsulate BDD tests stages into a lockable resource

pkg/framework/comparator_test.go
jira: https://issues.redhat.com/browse/KOGITO-4082
Hi guys, happy new year :D Just a very small clean up related to  https://github.com/kiegroup/kogito-runtimes/pull/953 . 
Removing all kogito-application.proto references
- [] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change
=> KOGITO-4082 - remove kogito-application.proto reference

Jenkinsfile, Jenkinsfile.deploy, hack/go-lint.sh
https://issues.redhat.com/browse/KOGITO-4004
https://issues.redhat.com/browse/KOGITO-4068
cherry-picks:
- https://github.com/kiegroup/kogito-cloud-operator/pull/706
- https://github.com/kiegroup/kogito-cloud-operator/pull/711
lock did not apply when launching master and 1.1.x in parallel ...
=> [1.1.x][KOGITO-4004][KOGITO-4068][cherry-pick] BDD tests stages in lockable resource

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-4159
Fix https://github.com/kiegroup/kogito-cloud-operator/pull/719
=> [1.1.x][KOGITO-4159] Fix to get the OPENSHIFT_API credentials in lock

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-4159
Fix https://github.com/kiegroup/kogito-cloud-operator/pull/717
=> [KOGITO-4159] Fix to get the OPENSHIFT_API credentials in lock

RELEASE_NOTES.md, api/v1beta1/kogitoinfra_types.go, api/v1beta1/zz_generated.deepcopy.go, controllers/infinispan.go, controllers/kogitoinfra_controller_test.go, pkg/infrastructure/services/deployer_resources.go, pkg/infrastructure/services/deployer_resources_test.go, pkg/test/kogitoinfra.go
The internal and the exposed name should be same, changing the internal name to `Volumes` since it is a list so makes more sense to me 
See: https://issues.redhat.com/browse/KOGITO-4133
=> [KOGITO-4133] - API rule violation when running openapi-gen

cmd/kogito/command/deploy/delete_service_test.go, cmd/kogito/command/deploy/deploy_service_test.go, cmd/kogito/command/project/delete_project_test.go, cmd/kogito/command/project/new_project_test.go, cmd/kogito/command/remove/kogitoinfra_test.go, go.mod, go.sum, test/config/config.go, test/main_test.go
https://issues.redhat.com/browse/KOGITO-4241
=> [KOGITO-4241] Setup godog 0.11

Makefile, RELEASE_NOTES.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/kogitobuild_controller.go, controllers/kogitoinfra_controller.go, controllers/kogitoruntime_controller.go, controllers/kogitosupportingservice_controller.go, controllers/mongodb.go, go.mod, go.sum, kogito-operator.yaml, main.go, pkg/client/client.go, pkg/client/client_builder.go, pkg/client/client_builder_test.go, test/framework/kubernetes.go, test/framework/operator.go
See: https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/operator.20and.20mongo
JIRA: https://issues.redhat.com/browse/KOGITO-4332
While investigating this issue, I've found that the `role.yaml` file was never updated. I fixed that, but the MongoDB permissions were already there. Please see my comment in the JIRA. 
[I also opened a follow-up JIRA](https://issues.redhat.com/browse/KOGITO-4332) to fix the `*` in the resources. We need more time to review that. That's why I haven't done it in this PR. @Kaitou786, do you mind taking this one?
=> [KOGITO-4332] Fixing role.yaml generation

pkg/infrastructure/kogito_images.go
https://issues.redhat.com/browse/KOGITO-4361
=> [KOGITO-4361] Invalid image tag for native image

Jenkinsfile.deploy, hack/ci/run-olm-tests.sh
See: https://issues.redhat.com/browse/KOGITO-2785
Tested to run successfully on: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kaitou786/job/olm-test/9/console
=> [KOGITO-2785] - Operator nightly pipeline: add olm tests

RELEASE_NOTES.md, controllers/kogitoruntime_controller.go, pkg/infrastructure/services/probe.go
- [[KOGITO-4210](https://issues.redhat.com/browse/KOGITO-4210)] Fix probe config for Quarkus deployments
- now checks HTTP path instead of TCP for Quarkus applications
- [[KOGITO-4173](https://issues.redhat.com/browse/KOGITO-4173)] Fix default probe URL for Quarkus
- from `/health` to `/q/health` 
- `/metrics` not changed as Prometheus endpoint unaffected by Quarkus update
- custom [probe](https://github.com/kiegroup/kogito-cloud-operator/blob/0c813a597d58bafd705ee685aafd32e637d57227/kogito-operator.yaml#L1106-L1108)/[metrics](https://github.com/kiegroup/kogito-cloud-operator/blob/0c813a597d58bafd705ee685aafd32e637d57227/kogito-operator.yaml#L1045-L1047) already implemented
I deployed this runtime YAML with an image of `process-quarkus-example` I built with the Quarkus `smallrye-health` …
=> [KOGITO-4210] Fix probe config for Quarkus deployments

core/kogitoservice/dashboards.go, core/kogitoservice/dashboards_test.go
JIRA: https://issues.redhat.com/browse/KOGITO-4444
The codegen generates valid dashboard filenames (for example `Traffic Violation.json`) based on the DMN model name, but these are not valid names for the grafana operator. This is why we need to sanitize the dashboard name before we create the `GrafanaDashboard`. 
We might change the filename on codegen side as well, but since it generates valid filenames, I think it's ok for the time being. 
=> KOGITO-4444 - Sanitize dashboard name

.github/workflows/Kogito-Operator-PR-Check.yaml, hack/go-lint.sh
https://issues.redhat.com/browse/KOGITO-4583
=> [KOGITO-4583] Revert lint to version v1.37.1

core/kogitoinfra/infinispan_reconciler.go
https://issues.redhat.com/browse/KOGITO-4572
=> [KOGITO-4572] KogitoInfra doesn't detect running Infinispan instance

RELEASE_NOTES.md, core/kogitoservice/deployer_resources.go, core/kogitoservice/deployer_resources_test.go, core/test/kogitosupportingservice.go
See: https://issues.redhat.com/browse/KOGITO-4453
The cause of this bug is that the `application.properties` provided in the propertiesConfigMap was not being added to the `appProps` map in `createRequiredResources()`. So when the ConfigMap is created in `createRequiredResources()`, it would not have any of the `application.properties` provided and delete the entire propertiesConfigMap when comparing the deltas of what is created and deployed in the deploy loop.
I fixed this bug by adding the `application.properties` from the propertiesConfigMap to the `appProps` map in `createRequiredResources()`.  This has to be done outside of the `if` block that checks if there is a resolvable image or deployment because I came across the case when there wasn't a resolvable image/deployment ready. In …
=> [KOGITO-4453] Fix overwriting propertiesConfigMap

test/features/deploy_kogito_runtime.feature, test/framework/graphql.go, test/framework/kafka.go, test/steps/kafka.go
Many thanks for submitting your Pull Request :heart: :cake:! 
[KOGITO-3344](https://issues.redhat.com/browse/KOGITO-3344)
* There is currently no other way to scale Kafka to 0 other than killing a pod. Kafka CR doesn't accept values less than 1 for number of instances.
* Even though it's just a deletion of a specific pod, I added a separate method for scaling Kafka to 0 directly to the framework, so we have this functionality right there in case the framework is extracted to a separate repo in the future.
=> KOGITO-3344 - Failover scenario for scaling Kafka to 0 using BDD tests

RELEASE_NOTES.md, api/kogitoservices_types.go, controllers/kogitoruntime_controller_test.go, core/infrastructure/image.go, core/kogitoservice/deployer_resources.go, core/kogitoservice/errors.go
Jira : https://issues.redhat.com/browse/KOGITO-3105
With this fix, conditions will looks as following :
```
Status:
Cloud Events:
Conditions:
Last Transition Time:  2021-03-25T09:19:17Z
Message:               you may not have access to the container image "quay.io/kiegroup/process-quarkus-example-1:latest"
Reason:                ReconciliationFailure
Status:                True
Type:                  Failed
Last Transition Time:  2021-03-25T09:19:17Z
Message:               
Reason:                RequestedReplicasNotEqualToAvailableReplicas
Status:                False
Type:                  Provisioning
Last Transition Time:  2021-03-25T09:19:17Z
Message:               
Reason:                NoPodAvailable
Status: …
```
=> [KOGITO-3105] - Missing status for failures for KogitoRuntime CRs

controllers/runtime_deployer.go, core/framework/comparator.go, core/kogitoservice/prometheus.go, go.mod, go.sum, meta/meta.go, test/pkg/framework/prometheus.go
See: https://issues.redhat.com/browse/KOGITO-4888
In addition to updating the repository link, the version also needed to be updated (see [this comment](https://github.com/kiegroup/rhpam-kogito-operator/pull/12#issuecomment-815000415) for reasoning). I verified on OpenShift 4.7.2 that the Prometheus CRD's were up-to-date for v0.46.0 and that the operator would run with this PR.
=> [KOGITO-4888] Update Prometheus operator GitHub link

RELEASE_NOTES.md, core/kogitoservice/probe.go, core/kogitoservice/probe_test.go
See: https://issues.redhat.com/browse/KOGITO-4781
This PR sets default values for probes so that values not specified for probes in the YAML have the default values in the requested resources. This makes it so that it matches the deployed resources (Kubernetes was automatically adding the default values for unspecified fields) and prevents the operator from continually updating the deployment when it sees a discrepancy between the requested and deployed resources.
I updated the probe unit tests to check that the default values are being added when they are not specified. I also deployed the following YAML on both `master` and this branch:
```yaml
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
name: qe
spec:
replicas: 1
image: quay.io/kmok/process-quarkus-example …
```
=> [KOGITO-4781] Fix deployment constantly updating

RELEASE_NOTES.md, core/kogitoservice/deployer_test.go, core/manager/infra_manager.go
https://issues.redhat.com/browse/KOGITO-4993
Cherrypick of https://github.com/kiegroup/kogito-operator/pull/857
=> [1.6.x][KOGITO-4993] Operator crash when data-index is created

RELEASE_NOTES.md, controllers/kogitoruntime_controller.go, core/kogitoservice/deployer.go, core/kogitoservice/deployment.go, core/kogitoservice/deployment_test.go, core/kogitoservice/probe.go, core/kogitoservice/probe_test.go, core/kogitosupportingservice/dataindex_reconciler.go, core/kogitosupportingservice/explainability_reconciler.go, core/kogitosupportingservice/jobsservice_reconciler.go, core/kogitosupportingservice/trustyai_reconciler.go
See: https://issues.redhat.com/browse/KOGITO-4898
This PR changes `probe.go` to be more runtime agnostic and combines all the previous probe getters into a single catch-all `getProbe` function. The `getProbe` function returns the correct probe based on the runtime and probe type. If the handler is empty (user hasn't specified anything for it), then the returned probe will be the defaults for the specific runtime.  If the handler is not empty and is HTTP, then the path and scheme will be set if they aren't already by the user.  If the handler is not empty and is TCP, then nothing in the handler needs to be set by us since the port is required in the YAML. Finally, the probe timer values are set in all cases to not cause reconciliation problems. So in all, the runtime is only considered …
=> [KOGITO-4898] Set probe defaults based on YAML action values

RELEASE_NOTES.md, core/kogitoservice/configmap.go, core/kogitoservice/configmap_test.go
See: https://issues.redhat.com/browse/KOGITO-4453?focusedCommentId=16158937&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16158937
The cause of this bug was that `getAppPropsFromConfigMap` was splitting the property value by `=` and only using the 2nd value of the split.
I used `SplitN` to keep the rest of value after the first `=` together as it should be.
I deployed the following YAML onto CRC, where the resulting `ConfigMap` kept all its values as they should be:
```yaml
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
name: qe
spec:
replicas: 1
image: quay.io/kmok/process-quarkus-example
propertiesConfigMap: qe-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
name: qe-cm
data:
application.properties: |
kafka.sals.mechanism=PLAIN …
```
=> [KOGITO-4453] Fix getAppPropsFromConfigMap

test/pkg/framework/kogitoinfra.go
Happens when Kogito operator doesn't fill the conditions array before the BDD tests check conditions.
=> BDD tests: Fix nil pointer error for KogitoInfra check

RELEASE_NOTES.md, cmd/kogito/command/deploy/delete_service_test.go, cmd/kogito/command/deploy/deploy_service_test.go, cmd/kogito/command/deploy/testdata/greetings.sw.json, cmd/kogito/command/install/kogito_infra_test.go, cmd/kogito/command/install/supportingservices_test.go, cmd/kogito/command/project/delete_project_test.go, cmd/kogito/command/project/display_project_test.go, cmd/kogito/command/project/new_project_test.go, cmd/kogito/command/project/use_project_test.go, cmd/kogito/command/remove/kogitoinfra_test.go, cmd/kogito/command/remove/supportingservices_test.go, cmd/kogito/command/service/build_service.go, cmd/kogito/command/service/runtime_service.go, cmd/kogito/command/shared/install_services.go, cmd/kogito/command/test/common.go, cmd/kogito/core/doc.go, cmd/kogito/core/resource_manager.go, core/client/kubernetes/resource_writer.go
See: https://issues.redhat.com/browse/KOGITO-4455
In this PR, we enable the possibility to redeploy a given Kogito service. This is **raw** redeploy, e.g., we are just updating the object if it's already there with the parameters sent via CLI. This is meant to enable quick, and dirt incremental builds. 
I'll run some integration tests this afternoon, but don't expect too much now. We should run much more scenarios.
This will avoid the cumbersome task of deleting a service to deploy it again. :disappointed: 
PS: there's a small refactoring in the `SetupCli` functions to enable re-executing the same command, reusing the context.
Depends on https://github.com/kiegroup/kogito-images/pull/399
Many thanks for submitting your Pull Request …
=> [KOGITO-4455] Enabling raw redeploy of Kogito Services on CLI

README.md
The YAML installer already creates the namespace for the user and assumes `kogito-operator-system` for all resources. There's no point adding the NAMESPACE var anymore.
=> Changes in the installation steps

.jenkins/dsl/jobs.groovy, .jenkins/scripts/helper.groovy, Jenkinsfile.deploy, Jenkinsfile.profiling
Our current OCP cluster on PSI is struggling to create volumes ...
Using an external cluster to run the BDD tests and to be able to launch the release.
If that works and we have the rights to keep the external cluster, I guess we should at least have the next release branch on that one to be confident in the release... let's see
=> [1.8.x] Setup External cluster use for BDD tests

Makefile, RELEASE_NOTES.md, go.sum
See: https://issues.redhat.com/browse/KOGITO-5512
CRD's won't be generated with `controller-gen` without disabling the `api` module.  This workaround is already present for the `bundle` rule for `operator-sdk`.
https://github.com/kiegroup/kogito-operator/blob/3122b7da5c716bc832f5762fafdb97d18a34a95b/Makefile#L136-L143
But, the `manifests` rule needs it as well for the CRD's for `controller-gen`.
```
➜ controller-gen crd:crdVersions=v1 paths="./..." output:stdout
[no output]
➜ ./hack/kogito-module-api.sh --disable
controller-gen crd:crdVersions=v1 paths="./..." output:stdout
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
...
```
=> [KOGITO-5512] controller-gen doesn't generate CRD's

RELEASE_NOTES.md, hack/create-olm-manifests.sh
https://issues.redhat.com/browse/KOGITO-4791
=> [KOGITO-4791] Add metrics related files back in the operator bundle

test/Makefile
<details>
<summary>
</summary>
</details>
=> Fix tests to disable_clean_cluster

.github/workflows/Kogito-Operator-OLM-tests.yaml, .github/workflows/Kogito-Operator-PR-Check.yaml, .github/workflows/Kogito-Operator-Unit-tests.yaml
So when we execute the GHA on different branches with different go version, there is no conflict...
<details>
<summary>
</summary>
</details>
=> Updated GHA: cache is specific to Go version

hack/go-build-cli.sh, hack/go-install-cli.sh, modules/org.kie.kogito.app.buildProfilingOperator/install.sh, modules/org.kie.kogito.app.builder/install.sh, modules/org.kie.kogito.rhpam.builder/install.sh
See: https://issues.redhat.com/browse/KOGITO-6230
<details>
<summary>
﻿golang automatically compiles natively, and explicitly setting these
prevents multi-architecture builds from working.
</summary>
</details>
=> [KOGITO-6230] Do not set GOOS/GOARCH

README.md
See:https://issues.redhat.com/browse/KOGITO-6125
Signed-off-by: desmax74 <mdessi@redhat.com>
<details>
<summary>
</summary>
</details>
=> [KOGITO-6125] Default Builder broken

README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/features/deploy_source_files.feature, test/pkg/config/config.go, test/pkg/steps/deploy_files.go
Similarly to what has been done for [kogito-images](https://github.com/kiegroup/kogito-images/commit/b91a8059c7542cd46f72f80ae0b4eda64c5fbb1d), we need a way to specify a specific build of the quarkus platform.
<details>
<summary>
</summary>
</details>
=> [1.11.x] BDD tests: Handle different URL for archetype mirror URL

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.profiling
https://issues.redhat.com/browse/KOGITO-5531
Required by Quarkus 2.2 branch.
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1123
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1961
- https://github.com/kiegroup/optaplanner/pull/1819
- https://github.com/kiegroup/kogito-apps/pull/1223
- https://github.com/kiegroup/kogito-examples/pull/1108
- https://github.com/kiegroup/kogito-operator/pull/1124
=> [1.11.x] KOGITO-5531 Update Jenkins CI to Maven 3.8.1

RELEASE_NOTES.md, cmd/kogito/command/deploy/delete_service.go, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/flag/install_flag.go, cmd/kogito/command/project/delete_project_test.go, cmd/kogito/command/remove/kogitoinfra.go, cmd/kogito/command/shared/resource_checks.go
Signed-off-by: Davide Salerno <dsalerno@redhat.com>
Cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1129
See: https://issues.redhat.com/browse/KOGITO-2787
<details>
<summary>
</summary>
</details>
=> [KOGITO-2787] Unify namespace/project wording in logs and Kogito CLI

hack/go-lint.sh
[KOGITO-4584](https://issues.redhat.com/browse/KOGITO-4584)
<details>
<summary>
</summary>
</details>
=> [KOGITO-4584] Switch lint version back to latest

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile-rhpam, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote, .github/bot-files/reviewers.yml, .github/workflows/Kogito-Operator-OLM-tests.yaml, .github/workflows/Kogito-Operator-PR-Check.yaml, .github/workflows/Kogito-Operator-Unit-tests.yaml, .github/workflows/jenkins-tests-PR.yml
Depends on https://github.com/kiegroup/kogito-pipelines/pull/388
I backported changes from `main` which are useful and removed drools references.
- https://github.com/kiegroup/kogito-pipelines/pull/388
- https://github.com/kiegroup/kogito-pipelines/pull/390
- https://github.com/kiegroup/kogito-runtimes/pull/2028
- https://github.com/kiegroup/optaplanner/pull/1850
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/662
- https://github.com/kiegroup/optaweb-employee-rostering/pull/771
- https://github.com/kiegroup/optaplanner-quickstarts/pull/295
- https://github.com/kiegroup/kogito-apps/pull/1258
- https://github.com/kiegroup/kogito-examples/pull/1144
- https://github.com/kiegroup/kogito-images/pull/1126
- https://github.com/kiegroup/kogito-operator/pull/1139
=> [1.13.x] Prepare branch for productization

test/debug_features/README.md, test/debug_features/install.feature, test/pkg/executor/bdd_executor.go
and profiling is skipped when keep_namespace is active
<details>
<summary>
</summary>
</details>
=> BDD: Setup some debug features

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile-rhpam, .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/484
- https://github.com/kiegroup/drools/pull/4446
- https://github.com/kiegroup/kogito-runtimes/pull/2252
- https://github.com/kiegroup/kogito-apps/pull/1375
- https://github.com/kiegroup/kogito-examples/pull/1285
- https://github.com/kiegroup/kogito-images/pull/1275
- https://github.com/kiegroup/kogito-operator/pull/1204
- https://github.com/kiegroup/optaplanner/pull/2023
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/708
- https://github.com/kiegroup/optaweb-employee-rostering/pull/826
- https://github.com/kiegroup/optaplanner-quickstarts/pull/352
=> [1.13.x] KOGITO-7356 Do not use master node in pipelines

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile-rhpam, .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/485
- https://github.com/kiegroup/kogito-runtimes/pull/2255
- https://github.com/kiegroup/kogito-examples/pull/1286
- https://github.com/kiegroup/kogito-images/pull/1276
- https://github.com/kiegroup/kogito-operator/pull/1205
- https://github.com/kiegroup/optaplanner/pull/2025
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/709
- https://github.com/kiegroup/optaweb-employee-rostering/pull/827
- https://github.com/kiegroup/optaplanner-quickstarts/pull/353
=> [1.13.x-blue] KOGITO-7356 Do not use master node in pipelines (#1204)

modules/org.kie.kogito.rhpam.builder.prod/install.sh, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.builder/install.sh, rhpam-image-prod.yaml
JIRA: https://issues.redhat.com/browse/KIECLOUD-639
This PR introduces an additional module for prod/OSBS builds that strips out the artifacts section to avoid impacting local builds, Cachito is already downloading and unzipping the src into a specific directory. With this section removed CEKit will no longer push main.go to the lookaside cache.
=> [1.13.x] KIECLOUD-639 - Remove lookaside cache usage in OSBS

modules/org.kie.kogito.rhpam.builder.prod/install.sh, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.builder/install.sh, rhpam-image-prod.yaml
JIRA: https://issues.redhat.com/browse/KIECLOUD-639
This PR introduces an additional module for prod/OSBS builds that strips out the artifacts section to avoid impacting local builds, Cachito is already downloading and unzipping the src into a specific directory. With this section removed CEKit will no longer push main.go to the lookaside cache. 
1.13.x PR : https://github.com/kiegroup/kogito-operator/pull/1214
=> KIECLOUD-639 - Remove lookaside cache usage in OSBS

.github/workflows/Kogito-Operator-OLM-tests.yaml, README.md, controllers/rhpam/suite_test.go
https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x-blue/job/nightly/job/kogito-operator-deploy/89/console
```
ok  	github.com/kiegroup/kogito-operator/controllers/app	5.676s	coverage: 100.0% of statements
?   	github.com/kiegroup/kogito-operator/controllers/common	[no test files]
Running Suite: Controller Suite
===============================
Random Seed: [1m1662090718[0m
Will run [1m0[0m of [1m0[0m specs
[1mSTEP[0m: bootstrapping test environment
2022-09-01T23:51:58.812-0400	DEBUG	controller-runtime.test-env	starting control plane	{"api server flags": []}
2022-09-01T23:52:04.014-0400	DEBUG	controller-runtime.test-env	installing CRDs
[91m[1mFailure [5.202 seconds][0m
[91m[1m[BeforeSuite] BeforeSuite [0m …
```
=> [1.13.x-blue] Correct unit tests

Makefile, README.md, bundle/app/manifests/kogito-operator.clusterserviceversion.yaml, config/manager/app/kustomization.yaml, config/manifests/app/bases/kogito-operator.clusterserviceversion.yaml, kogito-operator.yaml, profiling/kogito-operator-profiling.yaml, test/.default_config, version/app/version.go
Reverts kiegroup/kogito-operator#1292
We need first to have https://github.com/kiegroup/kogito-operator/pull/1290 merged
=> Revert "[1.28.x] Update snapshot version to 1.28.1-snapshot"

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/scripts/helper.groovy
JIRA: [5386](https://issues.redhat.com/browse/KOGITO-5386)
related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/1024
- https://github.com/kiegroup/kogito-runtimes/pull/3161
- https://github.com/kiegroup/kogito-apps/pull/1820
- https://github.com/kiegroup/kogito-examples/pull/1757
- https://github.com/kiegroup/kogito-images/pull/1666
- https://github.com/kiegroup/kogito-operator/pull/1504
- https://github.com/kiegroup/kogito-serverless-operator/pull/218
<details>
<summary>
</summary>
Please add comment: …
=> KOGITO-5386: added a new parameter for unique branch name

bamoe-image-bundle.yaml, bamoe-image-prod.yaml, bamoe-image.yaml, bamoe-operator.yaml, bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, config/manager/bamoe/kustomization.yaml, config/manifests/bamoe/bases/bamoe-kogito-operator.clusterserviceversion.yaml, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x-blue-next] Prepare the BAMOE branches for the 8.0.4 release
