apache/incubator-kie-kogito-operator

Gopkg.lock, deploy/role.yaml, pkg/apis/addtoscheme_app_v1alpha1.go, pkg/controller/subapp/subapp_controller.go, pkg/controller/subapp/watch.go
=> initial reconciliation fixes

deploy/crds/subapp.crd.yaml, deploy/crs/app_v1alpha1_subapp_cr.yaml, deploy/role.yaml, pkg/controller/subapp/subapp_controller.go
=> status fixes

Gopkg.lock, pkg/apis/app/v1alpha1/subapp_types.go, pkg/apis/app/v1alpha1/zz_generated.deepcopy.go, pkg/controller/subapp/subapp_controller.go, pkg/controller/subapp/watch.go
=> image & build fixes

pkg/controller/subapp/subapp_controller.go
=> add probes to DC

Gopkg.lock, README.md, cmd/manager/main.go, deploy/catalog_resources/community/0.1.0/submarinecloud-operator.0.1.0.clusterserviceversion.yaml
=> temporary removal of openshift check at startup

deploy/catalog_resources/community/0.1.0/submarinecloud-operator.0.1.0.clusterserviceversion.yaml
=> minor csv fixes

deploy/catalog_resources/community/0.1.0/kogitocloud-operator.0.1.0.clusterserviceversion.yaml
=> olm display fixes

README.md, hack/3.11deploy.sh
OLM & Marketplace are not required.
=> add manual deploy script for 3.11 clusters

.circleci/config.yml
Configuration needed to perform basic CI when a PR is opened in this project
=> [KOGITO-64] - Adding circleci configuration file

.circleci/config.yml
https://issues.jboss.org/browse/KOGITO-64
=> [KOGITO-64] - droping make to use go instead

.github/pull_request_template.md, CONTRIBUTING.MD
Minor grammar/style/typo issues found by Misha Ramendik in PR #28 after that PR as already merged
=> Grammar/style nitpicks by Misha

deploy/role.yaml
https://issues.jboss.org/browse/KOGITO-170
=> KOGITO-170: Add RBAC authorization into role.yaml

deploy/examples/service-labels.yaml
https://issues.jboss.org/browse/KOGITO-82
=> [KOGITO-82] Add example yaml containing service labels

deploy/catalog_resources/community/0.1.0/kogitocloud-operator.0.1.0.clusterserviceversion.yaml, deploy/role.yaml
See:
https://issues.jboss.org/browse/KOGITO-144
=> [KOGITO-144] - Adding replicasets resource to the policy rules

README.md
Small review for the CLI instructions now that we have a release available
=> Review of cli installation instructions 

build/Dockerfile, build/bin/entrypoint, build/bin/user_setup
Jira: https://issues.jboss.org/browse/KOGITO-161
Description: use base image registry.access.redhat.com/ubi8-minimal for Kogito operator.
=> [KOGITO-161] - Upgrade Kogito Operator image to ubi8

cmd/kogito/deploy_data_index.go
=> Fix incorrect error message

pkg/logger/logger.go
See: https://issues.jboss.org/browse/KOGITO-319
Small issue fix.
=> [KOGITO-319] - Remove timestamp from console log

deploy/olm-catalog/kogito-cloud-operator/0.4.0/kogito-cloud-operator.v0.4.0.clusterserviceversion.yaml
Just a small change to the submission to the OperatorHub
=> [KOGITO-67] - Adding more links to the CSV

deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml, pkg/controller/kogitoapp/resource/image_metadata.go, pkg/controller/kogitoapp/resource/image_metadata_test.go
See:
https://github.com/kiegroup/kogito-examples/pull/96
=> [KOGITO-379] - Fixing labels for multi backslash

Makefile, hack/go-test.sh
https://golangcode.com/how-to-run-go-tests-with-coverage-percentage/
=> Add support for test coverage measurement and visualization

cmd/kogito/command/context/config.go, cmd/kogito/command/context/root.go, deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml
See:
https://issues.jboss.org/browse/KOGITO-376
This is a leftover of this JIRA that I've missed at first. The config initialization was happening every time the config file was being read without need.
=> [KOGITO-376] - Moving config initialization out of read functions

Makefile, README.md, deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml, hack/pr-operatorhub.sh
See:
https://issues.jboss.org/browse/KOGITO-410
Small update in the README and a script to make it ease to create OperatorHub PRs.
=> [KOGITO-410] Small script to create operatorhub assets

deploy/examples/onboarding-example.yaml, deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml, pkg/controller/kogitoapp/resource/build_config_s2i.go, pkg/controller/kogitoapp/resource/build_config_s2i_test.go, pkg/controller/kogitoapp/resource/manage_resources_test.go, pkg/controller/kogitoapp/shared/utils.go, pkg/controller/kogitoapp/shared/utils_test.go, vendor/github.com/google/uuid/go.mod, vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod, vendor/github.com/magiconair/properties/go.mod, vendor/github.com/mitchellh/go-homedir/go.mod, vendor/github.com/mitchellh/mapstructure/go.mod, vendor/go.opencensus.io/go.mod, vendor/gopkg.in/yaml.v2/go.mod, vendor/gopkg.in/yaml.v2/go.sum
See:
https://issues.jboss.org/browse/KOGITO-415
=> [KOGITO-415] Fixing resources limits values for OCP 4.2

.gitignore, README.md
After reviewing and trying to follow the README,  I thought about those changes to be more clear.
Let me know what you think.
=> Reorganized a bit the README

pkg/controller/kogitodataindex/resource/defaults.go
https://issues.jboss.org/browse/KOGITO-476
Corrected default image name for data index service
=> Kogito-476: Corrected default image name for data index service

Makefile, hack/run-e2e.sh
Set operator image tag based on tag parameter
https://issues.jboss.org/browse/KOGITO-478
=> [KOGITO-478] Add possibility to run e2e tests with external image 

README.md, deploy/olm-catalog/kogito-cloud-operator/0.6.0/kogito-cloud-operator.v0.6.0.clusterserviceversion.yaml, go.sum, pkg/controller/kogitoapp/resource/build_config_s2i.go
See:
https://issues.jboss.org/browse/KOGITO-419
Depends on:
https://github.com/kiegroup/kogito-cloud/pull/55
Please don't bother the CSV changes, this are automatically generated by the test script with the new operator SDK tool. This will be changed once we deploy it to the hub.
=> [KOGITO-419] - Increasing the default native build memory limit

README.md, pkg/controller/kogitodataindex/resource/defaults.go
See:
https://issues.jboss.org/browse/KOGITO-477
Depends on:
https://github.com/kiegroup/kogito-cloud/pull/56
=> [KOGITO-477] Setting default port to 8080 to match image

cmd/kogito/command/context/root.go, cmd/kogito/version/version.go
Guys, just cherry picked the commit from 0.5.1 and increased the version
=> [KOGITO-485] - Cherry pick from 0.5.1

cmd/kogito/command/context/config.go, cmd/kogito/command/project/use_project_test.go, cmd/kogito/command/shared/resource_checks_test.go, cmd/kogito/command/test/common.go
https://issues.jboss.org/browse/KOGITO-482
Changed tests to use a different config file
To avoid conflicts with current machine configuration
=> KOGITO-482: Kogito CLI tests are changing the kogito config file

pkg/client/meta/meta.go, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/kogitoapp_controller_test.go
Description: fix the reconcile loop to exit when any error is encountered.
Jira: https://issues.jboss.org/browse/KOGITO-550
=> [KOGITO-550] Fix error swallow issues of the reconcile loop

cmd/kogito/command/install/data_index.go
https://issues.jboss.org/browse/KOGITO-567
Corrected kogito data index creation
=> [KOGITO-567] CLI: Bug while installing the dataindex

pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/kogitoapp_controller_test.go
See:
https://issues.jboss.org/browse/KOGITO-600
Simple update to the KogitoApp to remove default builds, avoiding side effects like the one exemplified in the JIRA
=> [KOGITO-600] - Removing default build limits

cmd/kogito/command/shared/install_operator.go, cmd/kogito/command/shared/install_operator_test.go, deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml, deploy/crds/app.kiegroup.org_kogitoinfras_crd.yaml, deploy/crds/app.kiegroup.org_v1alpha1_kogitoinfra_cr.yaml, deploy/olm-catalog/kogito-cloud-operator/0.6.0/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-cloud-operator/0.6.0/app.kiegroup.org_kogitodataindices_crd.yaml, deploy/olm-catalog/kogito-cloud-operator/0.6.0/app.kiegroup.org_kogitoinfras_crd.yaml, deploy/olm-catalog/kogito-cloud-operator/0.6.0/kogito-cloud-operator.v0.6.0.clusterserviceversion.yaml, go.sum, pkg/apis/app/v1alpha1/kogitoinfra_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/client/client.go, pkg/client/meta/meta.go, pkg/controller/kogitoinfra/kogitoinfra_controller.go, pkg/controller/kogitoinfra/status/manage_status.go, vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
See:
https://issues.jboss.org/browse/KOGITO-624
In this PR:
1. Removed the `subresource` duo to incompatibility issues with OCP 3.11. More details here: https://github.com/operator-framework/operator-sdk/issues/2118#issuecomment-555638254
2. Reading all CRDs from `deploy` directory to install all our CRDs with CLI
3. Verification during `watch` resources to proceed with operator flow even if Infinispan is not enabled.
@radtriste could you please verify this PR in your environment?
=> [KOGITO-624] Adding verification for Infinispan CRD

hack/3.11deploy.sh
and added missing kogitoinfra crd file
=> Refactored 3.11 hack to be more readable

hack/run-e2e.sh, test/e2e/example_verifier.go, test/e2e/kogitoapp_test.go
https://issues.redhat.com/browse/KOGITO-699
=> [KOGITO-699] Implementation of SpringBoot e2e integration test

deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml, deploy/crds/app.kiegroup.org_v1alpha1_kogitoinfra_cr.yaml, deploy/olm-catalog/kogito-cloud-operator/0.6.0/kogito-cloud-operator.v0.6.0.clusterserviceversion.yaml, deploy/olm-catalog/kogito-cloud-operator/kogito-cloud-operator.package.yaml
See:
https://issues.redhat.com/browse/KOGITO-706
Small adjustments to push 0.6.0 to OperatorHub
@radtriste @sutaakar could you guys please review?
A full working sample can be found in here: https://gist.github.com/ricardozanini/20cbc1b7768610cd86a6261f49a955b2
I also added a new channel, `dev-preview` to release 0.7.0-cr1 in two weeks, this way we can have quick milestones during development and treat bugs as soon as they happen.
=> [KOGITO-706] scorecard adjustments for 0.6.0 release

deploy/examples/kogito-kafka-quickstart-quarkus.yaml, deploy/olm-catalog/kogito-cloud-operator/0.6.0/kogito-cloud-operator.v0.6.0.clusterserviceversion.yaml, pkg/infrastructure/integration.go, pkg/infrastructure/integration_test.go, pkg/infrastructure/kogito_data_index.go, pkg/infrastructure/kogito_data_index_test.go
See:
https://issues.redhat.com/browse/KOGITO-720
Simple change to the environment variable that is injected in KogitoApps by Data Index, plus inserting WS scheme to the route.
=> [KOGITO-720] Inserting HTTP and WS urls to KogitoApps

cmd/kogito/command/shared/operatorhub.go, pkg/framework/subscription.go, pkg/infrastructure/operator.go, test/smoke/operator.go
https://issues.redhat.com/browse/KOGITO-852
=> [KOGITO-852] Detect running operator using subscription name

build/Dockerfile
https://issues.redhat.com/browse/KOGITO-915
=> [KOGITO-915] Change operator base image from 'registry.redhat.io' to 'registry.access.redhat.com'

cmd/kogito/command/command.go, cmd/kogito/command/install/infinispan.go, cmd/kogito/command/install/infinispan_test.go, cmd/kogito/command/message/infra.go, cmd/kogito/command/remove/factory.go, cmd/kogito/command/remove/infinispan.go, cmd/kogito/command/remove/infinispan_test.go, cmd/kogito/command/remove/remove.go, cmd/kogito/command/shared/install_data_index.go, cmd/kogito/command/shared/install_kogitoinfra.go, cmd/kogito/command/shared/install_services.go, cmd/kogito/command/shared/remove_kogitoinfra .go, cmd/kogito/command/shared/remove_services.go, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/kogitoapp_controller_test.go, pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/infrastructure/infinispan_integration.go, pkg/infrastructure/kogitoinfra.go, pkg/infrastructure/kogitoinfra_test.go
https://issues.redhat.com/browse/KOGITO-679
Smoke tests ran ok after change in infrastructure.
=> [KOGITO-679] Provide commands to create/delete infinispan instance

pkg/infrastructure/kogitoinfra.go, pkg/infrastructure/kogitoinfra_test.go
https://issues.redhat.com/browse/KOGITO-938
=> [KOGITO-938] [Bug] If the kogitoinfra already exists, the infrastructure package will overwrite the components installation values

cmd/kogito/command/install/factory.go, cmd/kogito/command/install/keycloak.go, cmd/kogito/command/install/keycloak_test.go, cmd/kogito/command/message/infra.go, cmd/kogito/command/remove/keycloak.go, cmd/kogito/command/remove/keycloak_test.go, cmd/kogito/command/shared/install_kogitoinfra.go, cmd/kogito/command/shared/install_services.go, cmd/kogito/command/shared/remove_kogitoinfra .go, cmd/kogito/command/shared/remove_services.go, pkg/infrastructure/kogitoinfra.go
https://issues.redhat.com/browse/KOGITO-921
=> [KOGITO-921] Provide commands to create/delete keycloak instance

cmd/kogito/command/install/kafka.go, cmd/kogito/command/install/kafka_test.go, cmd/kogito/command/message/infra.go, cmd/kogito/command/remove/factory.go, cmd/kogito/command/remove/kafka.go, cmd/kogito/command/remove/kafka_test.go, cmd/kogito/command/shared/install_services.go, cmd/kogito/command/shared/remove_kogitoinfra .go, cmd/kogito/command/shared/remove_services.go, pkg/infrastructure/kogitoinfra.go, pkg/infrastructure/kogitoinfra_test.go
https://issues.redhat.com/browse/KOGITO-909
=> [KOGITO-909] Provide command to create/delete kafka instance

test/smoke/features/cli/cli_deploy_springboot_service.feature, test/smoke/features/operator/deploy_springboot_service.feature
https://issues.redhat.com/browse/KOGITO-956
Will be later enabled in https://issues.redhat.com/browse/KOGITO-957, when problem is solved...
=> [KOGITO-956] Disable smoke test for springboot-example with persistence because of KOGITO-948

Makefile, README.md, hack/run-smoke.sh
https://issues.redhat.com/browse/KOGITO-939
=> [KOGITO-939] Set the concurrent tests as parameter

Makefile, README.md, hack/run-smoke.sh, test/smoke/README.md, test/smoke/framework/cli.go, test/smoke/framework/env.go, test/smoke/framework/kogitoapp.go, test/smoke/framework/operator.go, test/smoke/framework/util.go
https://issues.redhat.com/browse/KOGITO-941
- Get yaml files form Filesystem
- Restrucured also the run-smoke command to be easier (only one command)
=> [KOGITO-941]  Tests operator deployment via yaml files should use the files from Filesystem and not from Github master

test/smoke/features/operator/install_dataindex_service.feature, test/smoke/framework/graphql.go, test/smoke/framework/kogitoapp.go, test/smoke/framework/kogitodataindexservice.go, test/smoke/steps/graphql.go, test/smoke/steps/graphql_queries.go, test/smoke/steps/kogitoapp.go, test/smoke/steps/kogitodataindex.go
https://issues.redhat.com/browse/KOGITO-872
=> [KOGITO-872] Add Cucumber test for Data Index integration

Makefile, hack/go-build.sh
https://issues.redhat.com/browse/KOGITO-972
Also added some parameters in Makefile to change the image information, so we can build easily a local image with own registry, name and/or tag.
=> [KOGITO-972] Allow to change the image-builder when building the operator

README.md, hack/run-smoke.sh, test/smoke/framework/operator.go
https://issues.redhat.com/browse/KOGITO-947
=> [KOGITO-947] CRDs files should be updated before launching the smoke tests and not during

hack/run-smoke.sh
See:
https://issues.redhat.com/browse/KOGITO-1019
=> [KOGITO-1019] add missing semicolons to run-smoke.sh

Makefile, README.md, hack/run-smoke.sh, hack/run-smoke_test.bats, test/smoke/framework/env.go, test/smoke/framework/kogitoapp.go
https://issues.redhat.com/browse/KOGITO-998
=> [KOGITO-998] Setup all run-smoke params into Makefile

go.mod, go.sum, hack/run-smoke.sh, test/smoke/README.md, test/smoke/main_test.go, test/smoke/steps/cli.go, test/smoke/steps/data.go, test/smoke/steps/graphql.go, test/smoke/steps/http.go, test/smoke/steps/kogitoapp.go, test/smoke/steps/kogitodataindex.go, test/smoke/steps/kogitoinfra.go, test/smoke/steps/kogitojobsservice.go, test/smoke/steps/kubernetes.go, test/smoke/steps/operator.go, test/smoke/steps/prometheus.go
https://issues.redhat.com/browse/KOGITO-1109
=> [KOGITO-1109] Setup new path/version for godog

.gitignore, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/client/client.go, pkg/client/client_builder.go, pkg/client/client_builder_test.go, pkg/client/kubernetes/kubernetes.go, pkg/client/kubernetes/pod.go, test/smoke/framework/kubernetes.go, test/smoke/framework/logging.go, test/smoke/steps/data.go
https://issues.redhat.com/browse/KOGITO-950
=> [KOGITO-950] Store test logs into local filesystem

README.md, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/deploy/deploy_service_test.go, deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/examples/example-custom-build-images.yaml, deploy/examples/jbpm-quarkus-example-persistence.yaml, deploy/examples/jbpm-quarkus-example.yaml, deploy/examples/kogito-kafka-quickstart-quarkus.yaml, deploy/examples/onboarding-example.yaml, deploy/examples/travelapp-kogito-travel-agency.yaml, deploy/examples/travelapp-kogito-visas.yaml, deploy/olm-catalog/kogito-operator/0.8.0/app.kiegroup.org_kogitoapps_crd.yaml, go.mod, go.sum, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/controller/kogitoapp/resource/build_config_runtime.go, pkg/controller/kogitoapp/resource/build_config_s2i.go, pkg/controller/kogitoapp/resource/build_config_test.go, test/smoke/framework/cli.go, test/smoke/framework/kogitoapp.go
=> [KOGITO-305] - Add an option to add a maven mirror URL through CLI/CR

.circleci/config.yml, Makefile, README.md, hack/run-smoke.sh, hack/run-smoke_test.bats, test/smoke/feature.go, test/smoke/features/cli/cli_deploy_springboot_service.feature, test/smoke/features/cli/cli_install_kogitoinfra_components.feature, test/smoke/features/cr/deploy_quarkus_service.feature, test/smoke/features/cr/deploy_springboot_service.feature, test/smoke/features/cr/install_dataindex_service.feature, test/smoke/features/cr/install_jobs_service.feature, test/smoke/features/cr/install_kogitoinfra.feature, test/smoke/features/olm/cli_install_operator.feature, test/smoke/features/olm/cli_new_project.feature, test/smoke/features/olm/cli_use_project.feature, test/smoke/framework/cli.go, test/smoke/framework/env.go, test/smoke/framework/kogitoapp.go, test/smoke/framework/operator.go, test/smoke/framework/util.go, test/smoke/main_test.go
https://issues.redhat.com/browse/KOGITO-983
Change has been done as well how the smoke tests are started. No more direct call to godog application but call of go test. That means that we don't need to install godog binary anymore. 
Also, it gives us much more flexibility of configuration (--smoke.* options) and setup.
Also added `timeout` and `debug` options.
=> [KOGITO-983] Check first that the CLI exists

hack/run-smoke.sh
https://issues.redhat.com/browse/KOGITO-1165
=> [KOGITO-1165] Do not delete crds anymore before and after tests

Makefile, README.md, cmd/kogito/command/install/data_index.go, cmd/kogito/command/install/jobs_service.go, cmd/kogito/command/shared/install_data_index.go, hack/run-smoke.sh, pkg/controller/kogitodataindex/resource/defaults.go, pkg/controller/kogitodataindex/resource/deployment.go, pkg/controller/kogitodataindex/resource/image.go, pkg/controller/kogitojobsservice/kogitojobsservice_controller_test.go, pkg/controller/kogitojobsservice/resource/defaults_test.go, pkg/controller/kogitojobsservice/resource/image.go, pkg/framework/image.go, pkg/framework/image_test.go, pkg/infrastructure/data_index.go, pkg/infrastructure/jobs_service.go, pkg/infrastructure/jobs_service_test.go, test/smoke/feature.go, test/smoke/features/cli/cli_install_jobsservice.feature, test/smoke/features/cr/install_jobs_service.feature, test/smoke/features/olm/cli_install_operator.feature, test/smoke/features/olm/cli_new_project.feature, test/smoke/features/olm/cli_use_project.feature, test/smoke/framework/cli.go, test/smoke/framework/env.go, test/smoke/framework/kogitoapp.go, test/smoke/framework/kogitodataindexservice.go, test/smoke/framework/kogitojobsservice.go, test/smoke/steps/cli.go, test/smoke/steps/graphql.go
https://issues.redhat.com/browse/KOGITO-1162
Migrated some constant to `infrastructure` package as I don't think smoke package should rely on `cmd` and/or `controller` packages.
=> [KOGITO-1162] Added services_image_version option

cmd/kogito/command/install/kogito_operator.go, cmd/kogito/command/install/kogito_operator_test.go, cmd/kogito/command/shared/install_operator.go, cmd/kogito/command/shared/install_operator_test.go, cmd/kogito/command/shared/install_services.go, test/smoke/feature.go
see: https://issues.redhat.com/browse/KOGITO-492
=> [KOGITO-492] - CLI: Provide option to force operator installation

test/smoke/features/cli/cli_install_jobsservice.feature, test/smoke/features/cr/install_jobs_service.feature
https://issues.redhat.com/browse/KOGITO-960
=> [KOGITO-960] Enabled jobs-service with persistence test

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/framework/cli.go, test/framework/config.go, test/framework/http.go, test/framework/kogitoapp.go, test/framework/logging.go, test/framework/openshift.go, test/framework/util.go, test/main_test.go, test/steps/data.go
https://issues.redhat.com/browse/KOGITO-1017
Corrected also a small problem with pod logs collecting
=> [KOGITO-1017] Reorganized logs displayed by godog

test/framework/http.go, test/steps/http.go
https://issues.redhat.com/browse/KOGITO-1245
=> [KOGITO-1245] Corrected repetitive post calls if failing

cmd/kogito/command/command.go, cmd/kogito/command/completion/completion.go, cmd/kogito/command/completion/factory.go, go.mod, go.sum
[KOGITO-1240] Add command line completion to the Kogito CLI
https://issues.redhat.com/browse/KOGITO-1240
Signed-off-by: David Ward <dward@redhat.com>
=> [KOGITO-1240] Add command line completion to the Kogito CLI

go.mod, go.sum, hack/run-tests.sh, hack/run-tests.sh.bats, test/features/cr/service_discovery.feature, test/framework/config.go, test/framework/kogitoapp.go, test/main_test.go, test/steps/kogitoapp.go
https://issues.redhat.com/browse/KOGITO-997
=> [KOGITO-997] Setup service discovery feature scenario

README.md
=> KOGITO-1253 Added macOS to the Kogito CLI installation section heading.

test/features/cr/deploy_quarkus_service.feature, test/features/cr/deploy_springboot_service.feature, test/framework/kubernetes.go, test/steps/kogitoapp.go
https://issues.redhat.com/browse/KOGITO-1114
=> [KOGITO-1114] Jobs service tests with Kogito app

test/framework/kogitodataindexservice.go, test/framework/kubernetes.go
https://issues.redhat.com/browse/KOGITO-1295
=> [KOGITO-1295] Detect Data index replicas using Deployment object

test/features/cli/cli_deploy_quarkus_service.feature, test/features/cli/cli_deploy_springboot_service.feature, test/features/cli/cli_install_dataindex.feature, test/features/cli/cli_install_jobsservice.feature, test/features/cli/cli_install_kogitoinfra_components.feature, test/features/cr/deploy_quarkus_service.feature, test/features/cr/deploy_springboot_service.feature, test/features/cr/install_dataindex_service.feature, test/features/cr/install_jobs_service.feature, test/features/cr/install_kogitoinfra.feature, test/framework/operator.go, test/steps/operator.go
https://issues.redhat.com/browse/KOGITO-1257
=> [KOGITO-1257] Cucumber tests - install only needed dependent operators

README.md, cmd/kogito/command/completion/completion.go, cmd/kogito/command/context/logger.go, cmd/kogito/command/context/root.go, cmd/kogito/command/project/display_project_test.go, pkg/logger/logger.go
[KOGITO-1256] Add json output format to the Kogito CLI
https://issues.redhat.com/browse/KOGITO-1256
Signed-off-by: David Ward <dward@redhat.com>
- _Formatting changes also occurred after running the unit tests_
- _Local CLI testing was done_
=> [KOGITO-1256] Add json output format to the Kogito CLI

test/framework/util.go
https://issues.redhat.com/browse/KOGITO-1327
=> [KOGITO-1327] Improve the Cucumber test speed by adjusting waiting loop

test/framework/graphql.go
https://issues.redhat.com/browse/KOGITO-1356
=> [KOGITO-1356] Graphql error returns unsuccessful request

test/framework/graphql.go, test/steps/graphql.go
https://issues.redhat.com/browse/KOGITO-1364
=> [KOGITO-1364] Made WaitForSuccessfulGraphQLRequest more generic

hack/run-tests.sh
https://issues.redhat.com/browse/KOGITO-1375
=> [KOGITO-1375] Update test script to support not existing crd

README.md
=> Add warning about resources for native build in readme

test/framework/cli.go, test/framework/graphql.go, test/framework/util.go
https://issues.redhat.com/browse/KOGITO-1385
=> [KOGITO-1385] Do not stop waitFor loop if error in condition

test/features/install_dataindex.feature
https://issues.redhat.com/browse/KOGITO-1406
=> [KOGITO-1406] Disabling `Process instance events are stored in Data Index` scenario with native enabled

test/features/service_discovery.feature
https://issues.redhat.com/browse/KOGITO-1414
To avoid to have nightly failing tests ...
=> [KOGITO-1414] Disable scenario 'Discovery with onboarding' with native enabled

Makefile, hack/run-tests.sh, hack/run-tests.sh.bats, test/features/install_jobs_service.feature, test/framework/config.go, test/framework/graphql.go, test/framework/http.go, test/framework/kogitodataindex.go, test/framework/kogitoinfra.go, test/framework/kogitojobsservice.go, test/framework/kubernetes.go, test/framework/openshift.go, test/framework/operator.go, test/main_test.go, test/steps/data.go, test/steps/http.go, test/steps/kubernetes.go, test/steps/operator.go
https://issues.redhat.com/browse/KOGITO-1338
Added `load-factor` option
Also reorganized the options to be more structured and keep logic in all part of script/code
=> [KOGITO-1338] Tests: Give possibility to add a load factor for timeout values

hack/3.11deploy.sh, hack/scorecard.sh
https://issues.redhat.com/browse/KOGITO-1453
Simplify file globbing logic and adjust exit status to improve user
feedback.
Also add feedback for when no deployment files are found. This scenario
yields exit code 3, avoiding UNIX reserved exit codes.
Signed-off-by: Lucas Caparelli <lucas.caparelli112@gmail.com>
=> [KOGITO-1453] Refactor shell scripts file discovery logic

test/framework/http.go
https://issues.redhat.com/browse/KOGITO-1478
=> [KOGITO-1478] Improve HTTP request implementation for Cucumber tests

cmd/manager/main.go, deploy/examples/jbpm-quarkus-example-persistence.yaml, pkg/apis/addtoscheme_app_v1alpha1.go, pkg/client/client.go, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitodataindex/kogitodataindex_controller.go, pkg/controller/kogitoinfra/kogitoinfra_controller.go, pkg/controller/kogitojobsservice/kogitojobsservice_controller.go, pkg/framework/controller_watcher.go, pkg/framework/controller_watcher_test.go, pkg/test/client.go, pkg/test/controller_mocks.go
See:
https://issues.redhat.com/browse/KOGITO-1376
TODO:
=> [KOGITO-1376] Handling clusters without required CRDs

Jenkinsfile
Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>
=> [KOGITO-1011] - Github Jenkins Integration for PR

cmd/kogito/command/deploy/deploy_service.go
Signed-off-by: Lucas Caparelli <lucas.caparelli112@gmail.com>
=> Fix error message to match kafka instead of infinispan

test/features/deploy_travel_agency.feature, test/framework/kogitoapp.go, test/framework/process.go, test/framework/task.go, test/steps/data.go, test/steps/kogitoapp.go, test/steps/process.go, test/steps/task.go
Implemented scenario when Visa is not needed.
Other scenario will be delivered as another PR.
https://issues.redhat.com/browse/KOGITO-1316
=> [KOGITO-1316] Travel Agency Openshift scenario

README.md, test/framework/kogitoapp.go
https://issues.redhat.com/browse/KOGITO-1357
=> [KOGITO-1357] Tests: Add a 4Gi resource request if native building

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/framework/config.go, test/framework/kogitodataindex.go, test/framework/kogitojobsservice.go
https://issues.redhat.com/browse/KOGITO-1525
=> [KOGITO-1525] Add possibility to set services image tag in Cucumber tests

test/features/deploy_travel_agency.feature
https://issues.redhat.com/browse/KOGITO-1316
=> [KOGITO-1316] Add Travel agency example with required Visa

test/features/deploy_quarkus_service.feature
https://issues.redhat.com/browse/KOGITO-1506
=> Use ruleunit instead of drools as simple quarkus

pkg/controller/kogitoapp/resource/build_config_s2i.go, pkg/controller/kogitoapp/resource/build_config_test.go
See:
https://issues.redhat.com/browse/KOGITO-1277
=> [KOGITO-1277] - Adding Image Change triggering to s2i builds

cmd/kogito/command/install/factory.go, cmd/kogito/command/install/mgmt_console.go, cmd/kogito/command/install/mgmt_console_test.go, pkg/client/meta/meta.go, pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller.go, pkg/infrastructure/mgmt_console.go
See:
https://issues.redhat.com/browse/KOGITO-1005
=> [KOGITO-1005] Management Console support on CLI

Jenkinsfile.nightly
See: https://issues.redhat.com/browse/KOGITO-1127
Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>
=> [KOGITO-1127] - Operator Nightly Builds

test/features/deploy_springboot_service.feature
https://issues.redhat.com/browse/KOGITO-957
Bug from https://issues.redhat.com/browse/KOGITO-948 does not occur anymore.
=> [KOGITO-957] Tests: Enable springboot-example with persistence

pkg/controller/kogitoinfra/kafka/resource.go
https://issues.redhat.com/browse/KOGITO-1583
For the problem, see https://issues.redhat.com/browse/KOGITO-1583?focusedCommentId=14011466&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14011466
=> [KOGITO-1583] Update due to new Strimzi operator conditions

go.mod, go.sum, pkg/client/client.go, test/features/binary_build.feature, test/framework/command.go, test/framework/kogitoapp.go, test/framework/openshift.go, test/framework/util.go, test/steps/data.go, test/steps/git.go, test/steps/kogitoapp.go, test/steps/maven.go, test/steps/openshift.go
https://issues.redhat.com/browse/KOGITO-1370
=> [KOGITO-1370] Add Cucumber tests for binary build

Makefile
https://issues.redhat.com/browse/KOGITO-1623
Many thanks for submiting your Pull Request :heart: :racing_car: ! 
=> KOGITO-1623 - Fix Makefile run-tests target variable reference

README.md
- Wrong kogito-imagestream.yaml link
- Infinispan link not working
- Wrong sentence in Running the Kogito Operator locally
- Add requirements for testing e2e
JIRA Link: https://issues.redhat.com/browse/KOGITO-1605
=> KOGITO-1605: Amend issues in GitHub documentation

.osdk-scorecard.yaml, Makefile, deploy/crds/app.kiegroup.org_v1alpha1_kogitojobsservice_cr.yaml, deploy/crds/app.kiegroup.org_v1alpha1_kogitomgmtconsole_cr.yaml, deploy/olm-catalog/kogito-operator/0.9.0/kogito-operator.v0.9.0.clusterserviceversion.yaml, go.sum, hack/scorecard.sh
See:
https://issues.redhat.com/browse/KOGITO-1600
Nitpicks/scorecard check for 0.9.0 release.
=> [KOGITO-1600] - Prepare 0.9.0 Kogito Operator release

Makefile, hack/crds-utils.sh, hack/deploy-operator-on-ocp.sh, hack/run-tests.sh
We would like to provide an "install" option to Makefile so we can easily make use of the operator in an Openshift instance.
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1606
=> KOGITO-1606: Add install option in makefile

hack/go-build-cli.sh
See:
https://issues.redhat.com/browse/KOGITO-1365
Little tiny change for next releases :)
=> [KOGITO-1365] - Renaming final CLI binary

hack/go-build-cli.sh
cherry-pick for: https://github.com/kiegroup/kogito-cloud-operator/pull/258
=> [0.9.x][KOGITO-1365] - Renaming final CLI binary (#258)

deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.10.0/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.10.0/kogito-operator.v0.10.0.clusterserviceversion.yaml, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go
https://issues.redhat.com/browse/KOGITO-1703
=> [master][KOGITO-1703] Wrong build resource description in KogitoApp CRD

deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.9.1/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go
https://issues.redhat.com/browse/KOGITO-1703
=> [0.9.x][KOGITO-1703] Wrong build resource description in KogitoApp CRD

pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/apis/app/v1alpha1/kogitoservices_types.go, test/framework/kogitoapp.go, test/steps/kogitoapp.go
https://issues.redhat.com/browse/KOGITO-1597
=> [master][KOGITO-1597] Refactor Cucumber tests to get rid of KogitoAppDeployment

cmd/kogito/command/completion/completion.go, cmd/kogito/command/completion/factory.go, cmd/kogito/command/context/command_context.go, cmd/kogito/command/deploy/delete_service.go, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/deploy/factory.go, cmd/kogito/command/install/data_index.go, cmd/kogito/command/install/factory.go, cmd/kogito/command/install/infinispan.go, cmd/kogito/command/install/install.go, cmd/kogito/command/install/jobs_service.go, cmd/kogito/command/install/kafka.go, cmd/kogito/command/install/keycloak.go, cmd/kogito/command/install/kogito_operator.go, cmd/kogito/command/install/mgmt_console.go, cmd/kogito/command/project/delete_project.go, cmd/kogito/command/project/display_project.go, cmd/kogito/command/project/factory.go, cmd/kogito/command/project/new_project.go, cmd/kogito/command/project/use_project.go, cmd/kogito/command/remove/factory.go, cmd/kogito/command/remove/infinispan.go, cmd/kogito/command/remove/kafka.go, cmd/kogito/command/remove/keycloak.go, cmd/kogito/command/remove/remove.go, cmd/kogito/command/remove/runtime_services.go, cmd/kogito/command/remove/runtime_services_test.go, cmd/kogito/command/test/common.go
Cherry pick: https://github.com/kiegroup/kogito-cloud-operator/pull/267
See:
https://issues.redhat.com/browse/KOGITO-1258
=> [0.9.x][KOGITO-1258] - Adding 'remove' CLI commands to runtime support services

README.md, cmd/kogito/command/install/jobs_service.go, deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml, deploy/examples/data-index.yaml, deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml, pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller_test.go, pkg/infrastructure/data_index.go, pkg/infrastructure/data_index_test.go, pkg/infrastructure/integration_test.go, pkg/infrastructure/jobs_service.go, pkg/infrastructure/kogito_service_test.go, pkg/infrastructure/services/deployer_test.go, pkg/infrastructure/services/resources_test.go, test/features/install_dataindex.feature, test/features/install_jobs_service.feature, test/features/olm/cli_install_operator.feature, test/features/olm/cli_new_project.feature, test/features/olm/cli_use_project.feature
Chery-pick for https://github.com/kiegroup/kogito-cloud-operator/pull/272
=> [0.9.x][KOGITO-1688] - Renaming Kogito Support Services

Jenkinsfile, Jenkinsfile.nightly, Makefile, README.md, deploy/examples/jobs-service.yaml, hack/bump-version.sh, hack/run-tests.sh, hack/run-tests.sh.bats, test/.default_config
https://issues.redhat.com/browse/KOGITO-1627\
This will allow PR and nightlies to load against predefined version (case of cr builds).
This can still be overloaded when calling the script if needed.
=> [master] [KOGITO-1627] Load default test config

cmd/kogito/command/install/data_index.go, cmd/kogito/command/install/jobs_service.go, cmd/kogito/command/install/mgmt_console.go, deploy/crds/app.kiegroup.org_v1alpha1_kogitojobsservice_cr.yaml, deploy/crds/app.kiegroup.org_v1alpha1_kogitomgmtconsole_cr.yaml, deploy/examples/data-index.yaml, deploy/examples/management-console.yaml, deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml, pkg/controller/kogitoapp/kogitoapp_controller.go, pkg/controller/kogitoapp/kogitoapp_controller_test.go, pkg/controller/kogitoapp/resource/build_config.go, pkg/controller/kogitoapp/resource/kogito_imagestream_test.go, pkg/controller/kogitodataindex/kogitodataindex_controller_test.go, pkg/infrastructure/data_index.go, pkg/infrastructure/jobs_service.go, pkg/infrastructure/kogito_images.go, pkg/infrastructure/kogito_images_test.go, pkg/infrastructure/mgmt_console.go, pkg/infrastructure/services/deployment_test.go, pkg/infrastructure/services/image.go, pkg/infrastructure/services/image_test.go, pkg/infrastructure/services/resources_test.go, pkg/test/image.go, test/config/config.go, test/framework/kogitodataindex.go, test/framework/kogitojobsservice.go, test/framework/kogitomgmtconsole.go
Chery-pick for https://github.com/kiegroup/kogito-cloud-operator/pull/260
See:
https://issues.redhat.com/browse/KOGITO-1663
=> [0.9.x][KOGITO-1663] - Support for Kogito runtimes images micro version

test/features/install_mgmtconsole.feature
https://issues.redhat.com/browse/KOGITO-1750
=> [master] [KOGITO-1750] Set simple mgmt console test as smoke test

test/features/install_mgmtconsole.feature
https://issues.redhat.com/browse/KOGITO-1750
cherry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/280
=> [0.9.x] [KOGITO-1750] [cherry-pick] Set simple mgmt console test as smoke test

test/features/install_jobs_service.feature, test/framework/kogitojobsservice.go, test/steps/graphql.go, test/steps/graphql_queries.go, test/steps/kogitojobsservice.go
https://issues.redhat.com/browse/KOGITO-1359
=> [master] [KOGITO-1359] Setup jobs-service to data-index feature test

test/features/install_jobs_service.feature
https://issues.redhat.com/browse/KOGITO-1359
Correction of https://github.com/kiegroup/kogito-cloud-operator/pull/273
Small issue occured when rebased ...
=> [master] [KOGITO-1359] Corrected jobservice/data-index feature test

test/features/service_discovery.feature
https://issues.redhat.com/browse/KOGITO-1702
example change: https://github.com/kiegroup/kogito-examples/pull/152
This one should be merged after.
=> [master] [KOGITO-1702] Updated discovery test due to onboarding example migrated to ruleunit

test/features/binary_build.feature, test/features/deploy_quarkus_service.feature, test/features/deploy_springboot_service.feature, test/features/install_dataindex.feature, test/features/kogito_service_performance.feature
Issue: https://issues.redhat.com/browse/KOGITO-1669
Depends on https://github.com/kiegroup/kogito-examples/pull/187
=> [master] [KOGITO-1669] Updated features with new examples' names

test/features/install_jobs_service.feature, test/framework/kogitojobsservice.go, test/steps/graphql.go, test/steps/graphql_queries.go, test/steps/kogitojobsservice.go
https://issues.redhat.com/browse/KOGITO-1359
chrry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/273
=> [0.9.x] [KOGITO-1359] Setup jobs-service to data-index feature test

test/features/service_discovery.feature
https://issues.redhat.com/browse/KOGITO-1702
cherry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/268
depends on: https://github.com/kiegroup/kogito-examples/pull/190
=> [0.9.x] [KOGITO-1702] Updated discovery test due to onboarding example migrated to ruleunit

test/features/binary_build.feature, test/features/deploy_quarkus_service.feature, test/features/deploy_springboot_service.feature, test/features/install_dataindex.feature
Issue: https://issues.redhat.com/browse/KOGITO-1669
cherry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/283
Depends on https://github.com/kiegroup/kogito-examples/pull/197
=> [0.9.x] [KOGITO-1669] Updated features with new examples' names

test/framework/cli.go
https://issues.redhat.com/browse/KOGITO-1772
=> [KOGITO-1772] Use generic command execution in cli.go

test/.default_config
https://issues.redhat.com/browse/KOGITO-1774
0.9.1-rc1 is based on kiegroup/kogito-images#133 (tests will be done there)
=> [0.9.x][KOGITO-1774] Updated test default config to 0.9.1-rc1

test/.default_config
https://issues.redhat.com/browse/KOGITO-1774
0.10.0-rc1 is based on https://github.com/kiegroup/kogito-images/pull/130 (tests done there)
=> [master][KOGITO-1774] Updated test default config to 0.10.0-rc1

test/features/install_dataindex.feature
https://issues.redhat.com/browse/KOGITO-1407
=> [0.9.x] [KOGITO-1407] Enable scenario 'Process instance events are stored in Data Index' with native enabled

README.md, cmd/kogito/command/deploy/deploy_service_test.go, deploy/crds/app.kiegroup.org_v1alpha1_kogitoapp_cr.yaml, deploy/examples/example-custom-build-images.yaml, deploy/examples/onboarding-example.yaml, deploy/examples/process-quarkus-example-binary-builds.yaml, deploy/examples/process-quarkus-example-persistence.yaml, deploy/examples/process-quarkus-example.yaml, deploy/examples/service-labels.yaml, deploy/examples/springboot.yaml, deploy/examples/travelapp-kogito-travel-agency.yaml, deploy/examples/travelapp-kogito-visas.yaml, deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml, pkg/controller/kogitoapp/kogitoapp_controller_test.go, pkg/controller/kogitoapp/resource/build_config_test.go, pkg/controller/kogitoapp/resource/deployment_config_test.go, pkg/controller/kogitoapp/resource/service_test.go
Cherry-pick for https://github.com/kiegroup/kogito-cloud-operator/pull/289
=> [0.9.x][KOGITO-1770] - Renaming examples and CR to match kogito-examples repo

test/features/install_dataindex.feature
https://issues.redhat.com/browse/KOGITO-1407
cherry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/290
=> [master][KOGITO-1407] Enable scenario 'Process instance events are stored in Data Index' with native enabled

test/.default_config
https://issues.redhat.com/browse/KOGITO-1828
Depends on https://github.com/kiegroup/kogito-images/pull/137
=> [0.9.x][KOGITO-1828] Updated test default config to 0.9.1-rc2

test/README.md
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1698
Description: Add instructions about how to debug the automation tests using VS Code.
This is running the tests locally using Openshift.
=> [master][KOGITO-1698]: Add instructions about how to debug the automation tests

test/features/binary_build.feature
https://issues.redhat.com/browse/KOGITO-1926
=> [KOGITO-1926] Removed quarkus binary build from smoke tests

test/framework/kogitoserviceutils.go
=> Fix number of replicas in log entry

test/features/binary_build.feature, test/steps/maven.go
https://issues.redhat.com/browse/KOGITO-1950
=> [KOGITO-1950] Tests: Skip tests when building binary builds

test/features/deploy_springboot_service.feature
https://issues.redhat.com/browse/KOGITO-1965
`Data Index retrieves Spring Boot process' events: Step is undefined`
=> [KOGITO-1965] Tests: Corrected undefined step

deploy/examples/example-custom-build-images.yaml, deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml, test/.default_config
See: https://issues.redhat.com/browse/KOGITO-1728
=> [KOGITO-1728] - Release Kogito Operator/CLI 0.9.1

cmd/kogito/command/install/data_index.go, cmd/kogito/command/install/data_index_test.go, cmd/kogito/command/install/kogito_operator.go, cmd/kogito/command/message/data_index.go, cmd/kogito/command/message/flags/project.go, cmd/kogito/command/project/new_project.go, cmd/kogito/command/project/use_project.go, cmd/kogito/command/shared/install_data_index.go, cmd/kogito/command/shared/install_services.go
See: https://issues.redhat.com/browse/KOGITO-865
Just a small adjustment to remove some duplications in code.
=> [KOGITO-865] Small refactor to reuse same functions to deploy data index

hack/bump-version.sh
https://issues.redhat.com/browse/KOGITO-2009
=> [KOGITO-2009] Updated bump-version script for test default cfg

hack/run-tests.sh.bats, test/config/config.go, test/framework/http.go, test/framework/operator.go
https://issues.redhat.com/browse/KOGITO-1852
=> [KOGITO-1852] Corrected bug on pulling from internal Openshift in parallel

pkg/client/client.go, pkg/client/meta/meta.go, pkg/controller/kogitoinfra/infinispan/infinispan_credentials.go, pkg/controller/kogitoinfra/infinispan/resource.go, pkg/controller/kogitoinfra/infinispan/resource_test.go, test/features/install_dataindex.feature, test/framework/infinispan.go, test/framework/kogitodataindex.go, test/framework/kogitojobsservice.go, test/framework/kogitomgmtconsole.go, test/framework/kogitoserviceutils.go, test/framework/kubernetes.go, test/steps/data.go, test/steps/infinispan.go, test/steps/kogitodataindex.go, test/steps/prometheus.go
https://issues.redhat.com/browse/KOGITO-1347
=> [KOGITO-1347] Test Data index using external Infinispan

test/features/deploy_quarkus_service.feature, test/features/deploy_springboot_service.feature, test/framework/task.go, test/steps/data.go, test/steps/http.go, test/steps/process.go, test/steps/task.go
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1953
Description: Ability to test user task actions. Also, these changes add a context within steps in a scenario with variables (as a map).
Added scenario for spring boot and quarkus both.
=> KOGITO-1953: BDD tests: Test user task actions scenarios

test/steps/utils.go
https://issues.redhat.com/browse/KOGITO-2037
Should be merged together with https://github.com/kiegroup/kogito-examples/pull/253
=> [KOGITO-2037] Adjust process-quarkus-example example for Kogito operator

README.md, deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml, deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml, test/.default_config, test/README.md
=> [KOGITO-2006] - Release Kogito Operator/CLI 0.10.0

Jenkinsfile, Jenkinsfile.nightly, test/framework/kubernetes.go, test/framework/operator.go
https://issues.redhat.com/browse/KOGITO-1852
https://github.com/kiegroup/kogito-cloud-operator/pull/304 was not enough
we need also to confirm that the image pull secret is correctly attached to the pod...
=> [KOGITO-1852]: Update check for internal registry

Jenkinsfile, Jenkinsfile.nightly
Due to problems with podman in the Jenkins slave container ...
https://issues.redhat.com/browse/KOGITO-2077
=> [KOGITO-2077] Use buildah instead of podman

README.md, test/features/deploy_quarkus_service.feature, test/features/deploy_service_resources.feature, test/features/deploy_springboot_service.feature, test/features/install_jobs_service.feature
https://issues.redhat.com/browse/KOGITO-2010
=> [KOGITO-2010] Review scenario tags and add a tags dictionary

pkg/framework/controller_watcher.go
https://issues.redhat.com/browse/KOGITO-2108
Use a map indexed by the server group and version ("group/version"
format), matching all necessary information.
Signed-off-by: Lucas Caparelli <lucas.caparelli112@gmail.com>
=> [KOGITO-2108] Match group version when checking available groups

Jenkinsfile.nightly
https://issues.redhat.com/browse/KOGITO-2159
Due to infrastructure problems on Openshift.
Will be reactivated later in KOGITO-2160
=> [KOGITO-2159] Nightly run only smoke tests

Jenkinsfile
See: https://issues.redhat.com/browse/KOGITO-2183
Updating Jenkinsfile to stop previous build if new build is triggered from same PR
Signed-off-by: TARUN KHANDELWAL <tarkhand@redhat.com>
=> [KOGITO-2183] - Stop previous build if new build is triggered

go.sum, pkg/client/client.go, pkg/client/meta/meta.go, pkg/controller/kogitoinfra/kafka/resource.go, pkg/infrastructure/kafka.go, test/features/install_dataindex.feature, test/framework/kafka.go, test/framework/kogitoserviceutils.go, test/steps/data.go, test/steps/kafka.go, test/steps/kogitodataindex.go
https://issues.redhat.com/browse/KOGITO-1347
=> [KOGITO-1347] Test Data index using external Kafka

test/features/deploy_quarkus_service.feature, test/features/deploy_springboot_service.feature, test/features/install_dataindex.feature, test/steps/kogitoapp.go
https://issues.redhat.com/browse/KOGITO-1347
=> [KOGITO-1347] Test KogitoApp using external Infinispan and Kafka

README.md, test/features/deploy_quarkus_service.feature, test/features/deploy_springboot_service.feature, test/features/deploy_travel_agency.feature, test/features/install_dataindex.feature, test/features/install_jobs_service.feature, test/features/install_mgmtconsole.feature, test/features/kogito_service_performance.feature
https://issues.redhat.com/browse/KOGITO-2308
=> [KOGITO-2308] Review infra component tagging

test/features/deploy_travel_agency.feature
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1899
Description: Configure Travel Agency tests with native enabled
=> KOGITO-1899: BDD tests: Test travel-agency scenario in native mode

Jenkinsfile.deploy, Jenkinsfile.promote, Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/kogitoapp.go, test/framework/kogitoserviceutils.go
https://issues.redhat.com/browse/KOGITO-2150
https://issues.redhat.com/browse/KOGITO-2117
`Jenkinsfile.nightly` will be deprecated and replaced by `Jenkinsfile.deploy` (which is a copy of it with some improvements/parameters)
With this PR, we will need also to update the Jenkins job with the new file.
Finally default deployment registry is done Openshift.
The parent nightly pipeline will first call the `Jenkinsfile.deploy` pipeline and then if everything is ok, will call the `Jenkinsfile.promote` pipeline.
https://github.com/kiegroup/kogito-pipelines/pull/8
=> [KOGITO-2150][KOGITO-2117] Adjust deploy pipeline & Setup promote pipeline

test/features/deploy_travel_agency.feature
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1899
Description:
Enable the tests in native mode.
=> KOGITO-1899: Enable tests in native mode

deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitoapps_crd.yaml, pkg/apis/app/v1alpha1/kogitoapp_types.go, pkg/framework/image.go, pkg/framework/image_test.go
to include registry port
https://issues.redhat.com/browse/KOGITO-2218
=> [KOGITO-2218] Setup new regex for images

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/features/deploy_kogito_runtime.feature, test/framework/container_engine.go, test/framework/kogitoruntime.go, test/steps/image_registry.go, test/steps/kogitoruntime.go
https://issues.redhat.com/browse/KOGITO-2329
=> [KOGITO-2329] Implement image cache support for KogitoRuntime tests

test/framework/kogitodeployfiles.go
https://issues.redhat.com/browse/KOGITO-2369
=> [KOGITO-2369] Correct deploy files tests with test config

pkg/apis/app/v1alpha1/kogitoservices_types.go, test/features/deploy_kogito_runtime.feature, test/features/install_jobs_service.feature, test/framework/kogitodataindex.go, test/framework/kogitojobsservice.go, test/framework/kogitomgmtconsole.go, test/framework/kogitoruntime.go, test/framework/kogitoserviceutils.go, test/steps/kogito_service_table_parser.go, test/steps/kogitodataindex.go, test/steps/kogitojobsservice.go, test/steps/kogitoruntime.go
https://issues.redhat.com/browse/KOGITO-2330
=> [KOGITO-2330] Unify parsing of configuration table for Kogito services

cmd/manager/main.go
JIRA: https://issues.redhat.com/browse/KOGITO-2405
Description: Fix logs in Main.go
=> KOGITO-2405: Fix info logs

test/features/deploy_travel_agency.feature
https://issues.redhat.com/browse/KOGITO-2412
Dependency on https://github.com/kiegroup/kogito-examples/pull/267
=> [KOGITO-2412] Updated paths for travel agency test

hack/go-lint.sh
Changed the procedure to download the golangci-lint in go-lint.sh
https://github.com/kiegroup/kogito-cloud-operator/pull/388
=> [KOGITO-2396] - Integrate `golangci-lint` in `hack/go-lint.sh`

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, pkg/client/client.go, pkg/client/meta/meta.go, test/config/config.go, test/framework/check_setup.go, test/framework/http.go, test/framework/kogitoruntime.go, test/framework/kogitoserviceutils.go, test/framework/kubernetes.go, test/framework/openshift.go, test/framework/operator.go, test/main_test.go, test/steps/graphql.go, test/steps/http.go, test/steps/operator.go, test/steps/process.go, test/steps/prometheus.go, test/steps/task.go
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-2327
Description: KogitoRuntime Support in Kubernetes
Pending tasks:
How to test locally:
1.- Run minikube (v1.11 or later):
```
minikube start --addons ingress --addons olm --driver kvm2
```
The OC client will be configured transparently for us.
2.- Configure your /etc/hosts file with:
```
[YOUR K8S IP] data-index
[YOUR K8S IP] process-springboot-example
[YOUR K8S IP] process-quarkus-example
```
To find the IP, run "minikube ip".
3.- Login to the quay.io repository using your account:
```
docker login quay.io
```
And make your repositories public:
```
process-springboot-example-default
process-quarkus-example-default
process-springboot-example-persistence
process-quarkus-example-persistence
process-springboot-example-events-persistence …
```
=> KOGITO-2327: KogitoRuntime Support in Kubernetes

test/steps/kogitoapp.go
https://issues.redhat.com/browse/KOGITO-2492
=> [KOGITO-2492] Correct external kafka for spring

Jenkinsfile.deploy, Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/kogitoapp.go, test/framework/maven.go, test/steps/maven.go
https://issues.redhat.com/browse/KOGITO-1957
https://issues.redhat.com/browse/KOGITO-2359
=> [KOGITO-1957][KOGITO-2359] Setup a specific repository on local maven & S2I builds

deploy/examples/kubernetes/travel-agency/data-index.yaml, deploy/olm-catalog/kogito-operator/0.11.0/kogito-operator.v0.11.0.clusterserviceversion.yaml, deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml, test/.default_config
=> [KOGITO-1946] - Release Kogito Operator/CLI 0.11.0

test/features/deploy_source_files.feature, test/steps/deploy_files.go
JIRA: https://issues.redhat.com/browse/KOGITO-2477
=> KOGITO-2477: Deploy files for spring boot

pkg/infrastructure/record/event.go, pkg/infrastructure/record/event_test.go, pkg/infrastructure/record/log.go, pkg/infrastructure/services/deployer.go
Jira issue : https://issues.redhat.com/browse/KOGITO-1584
=> [KOGITO-1584] - Integrate Operator with Events API

deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitodataindices_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitojobsservices_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoruntimes_crd.yaml, pkg/controller/kogitobuild/build/image_stream.go, pkg/controller/kogitobuild/kogitobuild_controller_test.go, pkg/controller/kogitojobsservice/kogitojobsservice_controller_test.go, pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller_test.go, pkg/controller/kogitoruntime/kogitoruntime_controller_test.go, pkg/infrastructure/services/image.go, pkg/infrastructure/services/resources.go, pkg/test/reconciler.go
See: https://issues.redhat.com/browse/KOGITO-2535
Small fix to a bug introduced by the `KogitoBuild` feature.
=> [KOGITO-2535] Fix ImageStream name when custom image is given

cmd/kogito/command/deploy/common.go, cmd/kogito/command/install/data_index.go, cmd/kogito/command/install/data_index_test.go, cmd/kogito/command/install/jobs_service.go, cmd/kogito/command/install/jobs_service_test.go, cmd/kogito/command/install/mgmt_console.go, cmd/kogito/command/install/mgmt_console_test.go, deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml, deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml, deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml, deploy/crds/app.kiegroup.org_kogitomgmtconsoles_crd.yaml, deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoapps_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitodataindices_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitojobsservices_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml, deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoruntimes_crd.yaml, pkg/apis/app/v1alpha1/kogitoservices_types.go, pkg/apis/app/v1alpha1/zz_generated.openapi.go, pkg/infrastructure/services/image.go, pkg/infrastructure/services/image_test.go, test/framework/kogitoruntime.go, test/framework/kogitoserviceutils.go
https://issues.redhat.com/browse/KOGITO-2278
=> [KOGITO-2278] Add option to mark Kogito image streams as insecure

test/framework/kubernetes.go, test/framework/logging.go, test/steps/data.go
https://issues.redhat.com/browse/KOGITO-2560
=> [KOGITO-2560] Workaround for stuck zookeeper

test/features/deploy_kogito_build.feature, test/framework/kogitobuild.go, test/framework/kogitoserviceutils.go, test/steps/data.go, test/steps/kogitobuild.go, test/steps/kogitoruntime.go, test/steps/openshift.go
https://issues.redhat.com/browse/KOGITO-2090
=> [KOGITO-2090] Integrate KogitoBuild in tests

test/framework/maven.go
https://issues.redhat.com/browse/KOGITO-2590
=> [KOGITO-2590] SkipTests is ignored in maven.go

pkg/controller/kogitobuild/build/build_config_test.go
See: https://issues.redhat.com/browse/KOGITO-1906
=> [KOGITO-1906] - Create test to target incremental builds with operator

test/.default_config
https://issues.redhat.com/browse/KOGITO-2612
=> [KOGITO-2612] Set back correct default config

test/features/deploy_quarkus_service.feature
https://issues.redhat.com/browse/KOGITO-2614
Due to https://github.com/quarkusio/quarkus/issues/9954
=> [KOGITO-2614] Disable `Data Index retrieves Quarkus process' events with native enabled` test

.circleci/config.yml, go.sum, hack/go-vet.sh, pkg/apis/app/v1alpha1/zz_generated.openapi.go
See: https://issues.redhat.com/browse/KOGITO-2550
=> [KOGITO-2550] - Fixed vet test

test/.default_config
https://issues.redhat.com/browse/KOGITO-2628
=> [KOGITO-2628] Use nightly images for test dft config

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/config/image_cache_mode.go, test/framework/check_setup.go, test/framework/util.go, test/scripts/examples/process-optaplanner-quarkus.feature, test/scripts/examples/process-quarkus-example.feature, test/scripts/examples/process-springboot-example.feature, test/steps/image_registry.go
https://issues.redhat.com/browse/KOGITO-2594
=> [KOGITO-2594] Implement script to generate Kogito example images

test/.default_config
https://issues.redhat.com/browse/KOGITO-2649
=> [KOGITO-2649] Default cfg contains app runtime

test/features/deploy_quarkus_service.feature
https://issues.redhat.com/browse/KOGITO-2616
=> [KOGITO-2616] Enable events quarkus native enabled

Jenkinsfile.deploy, test/framework/maven.go, test/steps/maven.go
https://issues.redhat.com/browse/KOGITO-2661
=> [KOGITO-2661] Deploy pipeline cannot build examples images

.circleci/config.yml, .github/workflows/Kogito-Operator-PR-Check.yaml
=> Remove circleci from the repo

Jenkinsfile.deploy, test/framework/namespace.go
https://issues.redhat.com/browse/KOGITO-2700
=> [KOGITO-2700] Tests: increase timeout and concurrent

hack/run-tests.sh.bats
https://issues.redhat.com/browse/KOGITO-2702
=> [KOGITO-2702] Optimize bats tests runtime

deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml, deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml, deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml, examples/kubernetes/travel-agency/data-index.yaml, examples/process-quarkus-example-runtime-build-webhook.yaml
See: https://issues.redhat.com/browse/KOGITO-2635
Small adjustments in the manifest to release the 0.12.0 version.
=> [KOGITO-2635] - Preparing release 0.12.0

hack/ci/operator-olm-test.sh
=> Changed the operator-testing image with previous version of operator-courier

pkg/controller/kogitobuild/build/build_config.go, pkg/controller/kogitobuild/build/build_config_test.go
JIRA: https://issues.redhat.com/browse/KOGITO-2522
Description: Fix webhook issue for Github. Cover tests.
=> KOGITO-2522: Webhooks seems not working when deploying a Kogito Build

test/framework/http.go
https://issues.redhat.com/browse/KOGITO-2749
=> [KOGITO-2749] Tests: Fix invalid memory address for unsuccessful HTTP request

Makefile
https://issues.redhat.com/browse/KOGITO-2793
=> [KOGITO-2793] Set cr_deployment_only flag to true for image generation

go.mod, go.sum, test/feature.go, test/main_test.go, test/steps/data.go, test/steps/deploy_files.go, test/steps/git.go, test/steps/graphql.go, test/steps/http.go, test/steps/image_registry.go, test/steps/infinispan.go, test/steps/kafka.go, test/steps/kogito_service_table_parser.go, test/steps/kogitoapp.go, test/steps/kogitobuild.go, test/steps/kogitodataindex.go, test/steps/kogitoinfra.go, test/steps/kogitojobsservice.go, test/steps/kogitomgmtconsole.go, test/steps/kogitoruntime.go, test/steps/kubernetes.go, test/steps/maven.go, test/steps/openshift.go, test/steps/operator.go, test/steps/process.go, test/steps/prometheus.go, test/steps/task.go, test/steps/utils.go
https://issues.redhat.com/browse/KOGITO-2640
=> [KOGITO-2640] Upgrade tests to godog 0.10.0

.github/workflows/Kogito-Operator-OLM-tests.yaml, hack/ci/operator-olm-test.sh
See: https://issues.redhat.com/browse/KOGITO-2825
=> [KOGITO-2825] - Change operator-testing image to latest

deploy/olm-catalog/kogito-operator/0.13.0/kogito-operator.v0.13.0.clusterserviceversion.yaml
See: https://issues.redhat.com/browse/KOGITO-2880
=> [KOGITO-2880] - Fix failing lint stage

test/framework/maven.go
https://issues.redhat.com/browse/KOGITO-2850
=> [KOGITO-2850] Tests: Add Maven mirror configuration for local Maven builds

test/framework/kogitobuild.go
=> KOGITO-2903 KogitoBuild include custom maven repo

Jenkinsfile, test/framework/container_engine.go
https://issues.redhat.com/browse/KOGITO-2790
=> [KOGITO-2790] Setup build examples images

test/framework/kogitobuild.go
https://issues.redhat.com/browse/KOGITO-2903
Cherry-pick from 0.13.x fix: https://github.com/kiegroup/kogito-cloud-operator/pull/476 
=> [cherry-pick][KOGITO-2903] KogitoBuild include custom maven repo

test/features/deploy_kogito_runtime.feature
https://issues.redhat.com/browse/KOGITO-2904
=> [KOGITO-2904] Tests: Enable KogitoRuntime tests

test/steps/http.go
https://issues.redhat.com/browse/KOGITO-2940
=> [KOGITO-2940] Tests: Fix missing request body in HTTP request step

test/steps/operator.go
https://issues.redhat.com/browse/KOGITO-2932
Due to https://github.com/operator-framework/operator-lifecycle-manager/issues/1704
=> [KOGITO-2932] Install operators one after the other

GUIDE_TO_KOGITO_DEVS.md, README.md, docs/GUIDE_TO_KOGITO_DEVS.md
See: https://issues.redhat.com/browse/KOGITO-1654
=> [KOGITO-1654] - Guide for Core/Runtimes team to Smoke test local changes on Kubernetes

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-2978
=> [KOGITO-2978] Run all non native BDD tests in Kogito PR check

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3001
=> [KOGITO-3001] Set unstable if build examples imgs failing in deploy pipeline

test/features/deploy_kogito_runtime.feature, test/scripts/examples/process-optaplanner-quarkus.feature
https://issues.redhat.com/browse/KOGITO-2999
Disabled due to https://issues.redhat.com/browse/KOGITO-2998
=> [KOGITO-2999] BDD tests: Disable optaplanner native

test/features/install_jobs_service.feature
JIRA: https://issues.redhat.com/browse/KOGITO-2355
Description: Add tests making sure that Jobs service is able to communicate with other components using external Infinispan and Kafka connection.
=> KOGITO-2355: BDD tests: Test Jobs service using external Infinispan and Kafka connection

test/features/deploy_kogito_build.feature
https://issues.redhat.com/browse/KOGITO-3025
=> [KOGITO-3025] Disable native binary build test

.github/bot-files/comments.yml
The bot commented with `Jenkins, test this.` but on my pr the build did not start. The correct syntax is `Jenkins test this` isnt't? 
Sorry for the missing jira ticket, feel free to close it if I'm wrong
=> Update comments.yml for jenkins tests

test/steps/data.go
JIRA: https://issues.redhat.com/browse/KOGITO-3052
Description: Print error stack trace.
=> KOGITO-3052: Allow to see the exception stacktrace.

test/steps/data.go
https://issues.redhat.com/browse/KOGITO-2966
=> [KOGITO-2966] Tests: Remove Strimzi workaround

test/framework/command.go, test/framework/container_engine.go
https://issues.redhat.com/browse/KOGITO-3030
=> [KOGITO-3030] Tests: Retry image build in case of failure

test/framework/dockerfile_provider.go
https://issues.redhat.com/browse/KOGITO-2988
=> [KOGITO-2988] BDD: Revert detection for docker build

test/framework/kubernetes.go
https://issues.redhat.com/browse/KOGITO-3061
=> [KOGITO-3061] BDD: Correct invalid pointer reference

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3044
=> [KOGITO-3044] Improve build images time in deploy

pkg/infrastructure/services/infinispan.go, pkg/infrastructure/services/infinispan_test.go
Jira issue : https://issues.redhat.com/browse/KOGITO-2871
=> [KOGITO-2871] - Remove deprecated properties from kogito-cloud-operator

test/README.md
https://issues.redhat.com/browse/KOGITO-3103
=> [KOGITO-3103] Improve writing new BDD tests doc

Jenkinsfile.copy_csv_files
https://issues.redhat.com/browse/KOGITO-3149
=> [KOGITO-3149] Correct copy manifest files pipeline

test/framework/logging.go
Fixed by using synchronized Map.
https://issues.redhat.com/browse/KOGITO-3170
=> [KOGITO-3170] Tests: Concurrent map writes error in pod log collector

test/framework/logging.go
JIRA: https://issues.redhat.com/browse/KOGITO-3058
Description: Debug log of test run is not appearing
=> KOGITO-3058: Improve DEBUG option

test/features/deploy_kogito_runtime.feature, test/scripts/examples/process-optaplanner-quarkus.feature
JIRA: https://issues.redhat.com/browse/KOGITO-3000
Description: Enable optaplanner native test
=> KOGITO-3000: BDD tests: Enable optaplanner native test

test/features/prometheus.feature, test/framework/mappers/cr_to_cli.go, test/scripts/examples/dmn-drools-quarkus-metrics.feature, test/steps/kogitoruntime.go, test/steps/mappers/create_kogito_service.go
https://issues.redhat.com/browse/KOGITO-961
=> [KOGITO-961] Tests: Enable Prometheus test

README.md, test/features/install_jobs_service.feature, test/framework/http.go, test/framework/keycloak.go, test/steps/data.go, test/steps/http.go, test/steps/keycloak.go
JIRA: https://issues.redhat.com/browse/KOGITO-1001
Description: Add tests to integrate Jobs Service with Keycloak in order to add security capabilities.
=> KOGITO-1001: Add test for Jobs-service with Keycloak

test/framework/task.go, test/steps/task.go
https://issues.redhat.com/browse/KOGITO-3311
=> [KOGITO-3311] Tests: Update tests to reflect task endpoint change

Jenkinsfile.deploy, Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/maven.go
https://issues.redhat.com/browse/KOGITO-2997
=> [KOGITO-2997] BDD: Maven native build in container

test/features/install_dataindex.feature, test/framework/graphql.go, test/steps/graphql.go
JIRA: https://issues.redhat.com/browse/KOGITO-999
Description: As part of https://issues.redhat.com/browse/KOGITO-846, data-index is going to support Keycloak on operator side.
Need to be tested.
=> KOGITO-999: Cucumber Tests: Add test with Data-index and Keycloak

test/features/install_jobs_service.feature
JIRA: https://issues.redhat.com/browse/KOGITO-3333
=> [0.15.x] - KOGITO-3333: Disable jobs service keycloak test.

test/features/operator/deploy_kogito_runtime.feature, test/scripts/examples/process-optaplanner-quarkus.feature
https://issues.redhat.com/browse/PLANNER-2084
=> [PLANNER-2084] Tests: Disable Optaplanner native test

test/steps/data.go
https://issues.redhat.com/browse/KOGITO-3391
Many thanks for submiting your Pull Request :heart: :racing_car:! 
- [] Your feature/bug fix has a unit test that verifies it
- [] You've tested the new feature/bug fix in an actual OpenShift cluster
=> KOGITO-3391 - Fix logging in BDD tests case of the failed scenario

test/features/integration/keycloak.feature
JIRA: https://issues.redhat.com/browse/KOGITO-3357
=> Cucumber Tests: Add test for explainability-service with Keycloak

pkg/client/client.go, pkg/client/client_builder.go, pkg/client/client_builder_test.go, pkg/test/client.go
https://issues.redhat.com/browse/KOGITO-3388
=> [KOGITO-3388] Remove the PrometheusCli from operator code

Jenkinsfile, Jenkinsfile.deploy
JIRA: https://issues.redhat.com/browse/KOGITO-3360
=> KOGITO-3360: Cucumber Tests: Keep logs only for test failures

test/features/integration/keycloak.feature
JIRA: https://issues.redhat.com/browse/KOGITO-3281
Description: Add test for trusty-service with Keycloak
=> KOGITO-3281: Cucumber Tests: Add test for trusty-service with Keycloak

pkg/controller/kogitoexplainability/kogitoexplainability_controller.go, pkg/controller/kogitoexplainability/kogitoexplainability_controller_test.go, pkg/infrastructure/explainability.go, test/features/operator/install_explainability.feature, test/framework/kafka.go, test/framework/keycloak.go, test/framework/kogitotrusty.go, test/steps/kafka.go, test/steps/kogitoexplainability.go
JIRA: https://issues.redhat.com/browse/KOGITO-3369
Description: Apply the changes asked in the comments for https://github.com/kiegroup/kogito-cloud-operator/pull/568#event-3774194017.
=> KOGITO-3369: Cucumber Tests - Refactor Kogito Explainability Changes

RELEASE_NOTES.md
=> [KOGITO-3382] Add KOGITO-3382 issue to release notes

RELEASE_NOTES.md
=> update release notes with image change

pkg/controller/kogitoinfra/kogitoinfra_controller.go
https://issues.redhat.com/browse/KOGITO-3475
=> [KOGITO-3475] Periodic reconciler error when KogitoInfra is deleted

RELEASE_NOTES.md
=> [KOGITO-3433] - Update Graalvm version to 20.2.0

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3514
Due to https://issues.redhat.com/browse/KOGITO-3512
=> [KOGITO-3514] BDD: switch to docker container engine

test/features/keycloak.feature
JIRA: https://issues.redhat.com/browse/KOGITO-3552
=> KOGITO-3552: BDD tests: Enable Trusty - Keycloak test

test/steps/data.go
https://issues.redhat.com/browse/KOGITO-3586
=> [KOGITO-3586] BDD tests should have unique namespace

cmd/kogito/command/flag/infraresource_flag.go, cmd/kogito/command/install/kogito_infra_test.go, pkg/controller/kogitobuild/build/image_stream_kogito.go, pkg/controller/kogitobuild/build/image_stream_kogito_test.go, pkg/controller/kogitobuild/build/manager_test.go, pkg/controller/kogitobuild/kogitobuild_controller_test.go, pkg/controller/kogitoinfra/infinispan/infinispan_reconciler.go, pkg/controller/kogitoinfra/infinispan/resource.go, pkg/controller/kogitoinfra/kafka/kafka_reconciler.go, pkg/controller/kogitoinfra/kafka/resource.go, pkg/controller/kogitoinfra/keycloak/keyclock_reconciler.go, pkg/controller/kogitoinfra/keycloak/resource.go, pkg/controller/kogitoinfra/kogitoinfra_controller_test.go, pkg/controller/kogitoinfra/kogitoinfra_service.go, pkg/infrastructure/infinispan.go, pkg/infrastructure/kafka.go, pkg/infrastructure/keycloak.go, pkg/infrastructure/kogito_images.go, pkg/infrastructure/services/kafka.go, pkg/infrastructure/services/kafka_test.go, test/framework/dockerfile_provider.go, test/framework/kogitobuild.go, test/framework/kogitoinfra.go, test/steps/kafka.go
https://issues.redhat.com/browse/KOGITO-2986
Test should not depend on `controller` package directly but should make usage of `infrastructure` package
=> [KOGITO-2986] Remove controller package dependency in tests

Jenkinsfile, Jenkinsfile.deploy, Makefile, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/kogitobuild.go
https://issues.redhat.com/browse/KOGITO-3465
=> [KOGITO-3465] BDD tests: Handle self-signed certificate

test/steps/openshift.go
JIRA: https://issues.redhat.com/browse/KOGITO-3711
Description: Build <runtime> binary build with native <native> using KogitoBuild" is invoking binary build using OC client. Sometimes this build crash due to "unable to find latest tagged image".
=> KOGITO-3711: BDD tests: Unable to find latest tagged image

.github/pull_request_template.md
@sterobin can you take a look please?
=> Fixing grammar errors

RELEASE_NOTES.md, pkg/controller/kogitoruntime/deployer.go, pkg/controller/kogitoruntime/kogitoruntime_controller_test.go, pkg/infrastructure/kogito_service.go, pkg/infrastructure/kogito_service_test.go, pkg/infrastructure/services/dashboards.go, pkg/infrastructure/services/deployment.go, pkg/infrastructure/services/messaging.go, pkg/infrastructure/services/prometheus.go
See: https://issues.redhat.com/browse/KOGITO-3376
Accompanying images PR: https://github.com/kiegroup/kogito-images/pull/270
=> [KOGITO-3376] Update protobuf ConfigMap using fetched files

.github/workflows/Kogito-Operator-PR-Check.yaml, hack/go-vet.sh, kogito-operator.yaml
=> Debugging gen manifest status

.github/bot-files/reviewers.yml
=> Drop Jose from test reviewers

Jenkinsfile.deploy, Makefile, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/maven.go
https://issues.redhat.com/browse/KOGITO-3745
Link PR: https://github.com/kiegroup/kogito-images/pull/271
=> [KOGITO-3745] Mirror should ignore the custom repo

test/features/data_index_performance.feature, test/framework/graphql.go, test/framework/kogitodataindex.go, test/framework/maven.go, test/steps/graphql.go, test/steps/graphql_queries.go, test/steps/image_registry.go, test/steps/mappers/create_maven_options.go, test/steps/maven.go
Many thanks for submitting your Pull Request :heart: :racing_car:!
[KOGITO-1046](https://issues.redhat.com/browse/KOGITO-1046)
Feature file is not ready yet (will be finished in another PR) as I still have to tune up Kafka and Kogito service to get to the desired numbers. However, I chose to do this as a part of another JIRA ([KOGITO-3742](https://issues.redhat.com/browse/KOGITO-3742)), which will be purely focused on tuning the parameters and infrastructure. Therefore you can ignore the enclosed feature file, it has the tag `@performance`, so it won't run by default.
=> KOGITO-1046 - Data Index performance tests

test/steps/data.go
https://issues.redhat.com/browse/KOGITO-3831
=> [KOGITO-3831] Store ClusterServiceVersions used in tests

test/features/grafana.feature, test/framework/grafana.go, test/steps/data.go, test/steps/grafana.go
https://issues.redhat.com/browse/KOGITO-3720
=> [KOGITO-3720] Add test coverage for Grafana dashboard

test/framework/operator.go
https://issues.redhat.com/browse/KOGITO-3847
=> [1.0.x][KOGITO-3847] Switch Strimzi operator channel to 0.19

test/framework/operator.go
https://issues.redhat.com/browse/KOGITO-3847
=> [KOGITO-3847] Switch Strimzi operator channel to 0.19

.github/workflows/Kogito-Operator-OLM-tests.yaml, .github/workflows/Kogito-Operator-PR-Check.yaml, .github/workflows/Kogito-Operator-Unit-tests.yaml
https://issues.redhat.com/browse/KOGITO-3852
=> [1.0.x][KOGITO-3852] Extend GitHub actions to cover all branches

.github/workflows/Kogito-Operator-OLM-tests.yaml, .github/workflows/Kogito-Operator-PR-Check.yaml, .github/workflows/Kogito-Operator-Unit-tests.yaml
https://issues.redhat.com/browse/KOGITO-3852
=> [KOGITO-3852] Extend GitHub actions to cover all branches

pkg/controller/kogitoinfra/kogitoinfra_controller.go, pkg/controller/kogitoruntime/kogitoruntime_controller.go, pkg/controller/kogitosupportingservice/kogitosupportingservice_controller.go, pkg/infrastructure/kogito_infra.go, pkg/infrastructure/kogito_infra_test.go, pkg/infrastructure/kogito_runtime.go, pkg/infrastructure/kogito_runtime_test.go
Jira issue : https://issues.redhat.com/browse/KOGITO-3866
=> [KOGITO-3866] - Operator print error logs when KogitoRuntime delete

Jenkinsfile, Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3893
=> [KOGITO-3893] Add unit testing to jenkinsfiles

RELEASE_NOTES.md
=> [1.0.x] Update release notes with known bugs for 1.0.0 release

test/features/deploy_source_files.feature
Signed-off-by: Karel Suta <karel@localhost.localdomain>
https://issues.redhat.com/browse/KOGITO-3899
=> [KOGITO-3899] Add build check steps in source files feature

test/features/prometheus.feature
https://issues.redhat.com/browse/KOGITO-3935
=> [KOGITO-3935] Adjust Prometheus test for metric change

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/operator.go, test/main_test.go
https://issues.redhat.com/browse/KOGITO-3910
=> [KOGITO-3910] Add option to run tests with cluster wide operator

RELEASE_NOTES.md, pkg/controller/add_kogitoruntime.go, pkg/controller/add_kogitosupportingservice.go, pkg/controller/kogitoinfra/kogitoinfra_controller.go, pkg/controller/kogitoruntime/kogitoruntime_controller.go, pkg/controller/kogitoruntime/kogitoruntime_finalizer.go, pkg/controller/kogitosupportingservice/kogitosupportingservice_controller.go, pkg/controller/kogitosupportingservice/kogitosupportingservice_finalizer.go, pkg/framework/owner.go, pkg/framework/owner_test.go, pkg/infrastructure/kogito_infra.go, pkg/infrastructure/kogito_infra_test.go, pkg/infrastructure/kogito_service.go, pkg/infrastructure/kogito_service_test.go
…gitoSupportingService delete
Jira issue : https://issues.redhat.com/browse/KOGITO-3864
=> [KOGITO-3864] - KogitoInfra gets deleted when refering KogitoRuntime/KogitoSupportingService delete

test/framework/operator.go, test/main_test.go
https://issues.redhat.com/browse/KOGITO-3960
=> [KOGITO-3960] Add log monitoring for OLM namespace

hack/clean-stuck-namespaces.sh
https://issues.redhat.com/browse/KOGITO-3961
=> [KOGITO-3961] Adjust clean-stuck-namespaces.sh with Kogito CRs

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3962
=> [KOGITO-3962] BDD tests: Set load factor to 1 for nightlies/release

Jenkinsfile, Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3960
=> [KOGITO-3960] Store OLM logs for PR checks and nightly builds

test/features/install_explainability.feature
Jira: https://issues.redhat.com/browse/KOGITO-3966
The BDD explainability test is currently broken on master due to https://github.com/kiegroup/kogito-examples/pull/477 . 
This PR aims to fix it according to the changes in the dmn model used in the kogito runtime application. 
Many thanks for submitting your 
- [] Your feature/bug fix has a unit test that verifies it
=> [KOGITO-3966] Update explainability BDD test

pkg/apis/app/v1beta1/kogitoservices_types.go, test/framework/kogitoruntime.go, test/framework/kogitoserviceutils.go
Signed-off-by: Karel Suta ksuta@redhat.com
https://issues.redhat.com/browse/KOGITO-3939
=> [KOGITO-3939] Adjust readiness and liveness probes

Jenkinsfile, Jenkinsfile.deploy, Makefile, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/namespace.go, test/framework/operator.go, test/main_test.go, test/steps/operator.go
https://issues.redhat.com/browse/KOGITO-3938
=> [KOGITO-3938] Add option to run tests with Kogito cluster wide operator

Jenkinsfile, Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-4016
=> [KOGITO-4016] Don't deploy Kogito operator when building example images

Jenkinsfile.copy_csv_files, Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3863
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/99
- https://github.com/kiegroup/kogito-runtimes/pull/947
- https://github.com/kiegroup/kogito-apps/pull/572
- https://github.com/kiegroup/kogito-examples/pull/490
- https://github.com/kiegroup/optaplanner/pull/1071
- https://github.com/kiegroup/kogito-images/pull/289
- https://github.com/kiegroup/kogito-cloud-operator/pull/698
=> [KOGITO-3863] Setup timeout to pipelines

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-4111
=> [KOGITO-4111] Use docker in deploy/promote pipelines

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4121
=> [KOGITO-4121] Disable native options for BDD tests

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4121
=> [KOGITO-4121] Switch PR checks to podman

Makefile, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/config/config.go, test/framework/operator.go, test/main_test.go, test/steps/operator.go
https://issues.redhat.com/browse/KOGITO-4109
=> [KOGITO-4109] Implement OLM based approach for running tests

Jenkinsfile, Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-4159
to avoid blocking even tests on another OCP
=> [KOGITO-4159] updated BDD tests lock string

Jenkinsfile, Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-4159
to avoid blocking even tests on another OCP
Cherry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/717
=> [1.1.x][KOGITO-4159][cherry-pick] Updated BDD tests lock string (#717)

RELEASE_NOTES.md, test/features/keycloak.feature
Workaround for BDD tests to avoid https://issues.redhat.com/browse/KOGITO-4173
Cherrypick of https://github.com/kiegroup/kogito-cloud-operator/pull/720
=> [1.1.x] [KOGITO-4173] Appy workaround for Keycloak tests

RELEASE_NOTES.md, test/features/keycloak.feature
Workaround for BDD tests to avoid https://issues.redhat.com/browse/KOGITO-4173
=> [KOGITO-4173] Appy workaround for Keycloak tests

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-4180
=> [KOGITO-4180] Setup different lock for BDD

RELEASE_NOTES.md, controllers/infinispan.go, controllers/kogitoinfra_controller.go, go.mod, go.sum, hack/install-manifest.sh, pkg/infrastructure/infinispan.go
See: 
- https://issues.redhat.com/browse/KOGITO-4188 
- https://issues.redhat.com/browse/KOGITO-4192
Here's how the `KogitoInfra` looks like now:
```
Name:         kogito-infinispan-infra
Namespace:    my-infinispan
Labels:       <none>
API Version:  app.kiegroup.org/v1beta1
Kind:         KogitoInfra
Metadata:
Creation Timestamp:  2021-01-15T19:51:50Z
Generation:          1
Spec:
Resource:
API Version:  infinispan.org/v1
Kind:         Infinispan
Name:         example-infinispan
Namespace:    my-infinispan
Status:
Condition:
Last Transition Time:  2021-01-15T19:51:50Z
Status:                True
Type:                  Success
Runtime Properties:
Quarkus:
App Props:
quarkus.infinispan-client.sasl-mechanism:  PLAIN …
```
=> [KOGITO-4188] [KOGITO-4192] Update Infinispan to 2.0.6

Jenkinsfile.promote
Introduced by https://github.com/kiegroup/kogito-cloud-operator/pull/729
=> Correct promote Jenkinsfile

Makefile, README.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, cmd/kogito/version/version.go, config/manager/kustomization.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, kogito-operator.yaml, pkg/version/version.go, test/.default_config
=> [1.2.x] Set next snapshot

Makefile, RELEASE_NOTES.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, cmd/kogito/command/deploy/delete_service_test.go, cmd/kogito/command/deploy/deploy_service_test.go, cmd/kogito/command/project/delete_project_test.go, cmd/kogito/command/project/new_project_test.go, cmd/kogito/command/remove/kogitoinfra_test.go, config/rbac/role.yaml, controllers/kogitobuild_controller.go, controllers/kogitoinfra_controller.go, controllers/kogitoruntime_controller.go, controllers/kogitosupportingservice_controller.go, controllers/mongodb.go, go.mod, go.sum, kogito-operator.yaml, main.go, pkg/client/client.go, pkg/client/client_builder.go, pkg/client/client_builder_test.go, test/framework/kubernetes.go, test/framework/operator.go
=> [1.2.x][KOGITO-4332] Fixing role.yaml generation

RELEASE_NOTES.md, controllers/build/build_config.go, controllers/build/image_stream_kogito.go, controllers/build/image_stream_kogito_test.go, controllers/build/manager_test.go, controllers/kogitobuild_controller.go, controllers/kogitobuild_controller_test.go, pkg/infrastructure/kogito_images.go, pkg/infrastructure/services/deployer_resources.go, test/framework/dockerfile_provider.go, test/framework/kogitobuild.go
See: https://issues.redhat.com/browse/KOGITO-2317
=> [KOGITO-2317] - Unify Kogito Quarkus and Spring Images

Jenkinsfile.deploy
=> Added `kogito-operator-system` log archive

Jenkinsfile.deploy
cherry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/747
=> [1.2.x] Added `kogito-operator-system` log archive (#747)

Jenkinsfile.deploy
and some other useful params
https://issues.redhat.com/browse/KOGITO-4307
=> [KOGITO-4307] Add tags params

Jenkinsfile.promote, hack/update_test_config.sh.bats
=> Fix promote file

README.md, test/features/deploy_kogito_runtime.feature, test/framework/http.go, test/framework/knative.go, test/framework/kogitoinfra.go, test/framework/kubernetes.go, test/steps/data.go, test/steps/http.go, test/steps/knative.go, test/steps/kogitoinfra.go, test/steps/kubernetes.go
https://issues.redhat.com/browse/KOGITO-3678
=> [KOGITO-3678] Add test coverage for Knative functionality

.github/workflows/jenkins-tests-PR.yml, .jenkins/dsl/jobs.groovy, .jenkins/dsl/test.sh, Jenkinsfile.deploy, Jenkinsfile.promote, test/framework/maven.go
https://issues.redhat.com/browse/KOGITO-3034
https://issues.redhat.com/browse/BXMSPROD-1094
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/92
- https://github.com/kiegroup/kogito-runtimes/pull/940
- https://github.com/kiegroup/kogito-apps/pull/581
- https://github.com/kiegroup/optaplanner/pull/1085
- https://github.com/kiegroup/kogito-examples/pull/500
- https://github.com/kiegroup/kogito-images/pull/307
- https://github.com/kiegroup/kogito-cloud-operator/pull/710
**Setup DSL scripts for the different Kogito jobs.**
- Allow easy setup of jobs for own purpose (with different configuration for example)
- Moved parameters as environment
- That allows exact same configuration information for all the jobs, without having to 
- For testing, taking the getting the seed job and …
=> [KOGITO-3034][BXMSPROD-1094] Setup Jenkins DSL scripts

.github/workflows/jenkins-tests-PR.yml, .jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-3034
=> Correct DSL generation

Jenkinsfile.deploy
=> Use docker for OLM test in nightly pipeline

Makefile, bundle.Dockerfile, bundle/metadata/annotations.yaml, hack/ci/operator-ensure-manifests.sh
See: https://issues.redhat.com/browse/KOGITO-2947
=> [KOGITO-2947] - Upgrade Operator manifests to the new bundle format

Makefile, bundle.Dockerfile, bundle/metadata/annotations.yaml, hack/ci/operator-ensure-manifests.sh
See: https://issues.redhat.com/browse/KOGITO-2947
=> [1.3.x] [KOGITO-2947] - Upgrade Operator manifests to the new bundle format

Makefile, README.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, cmd/kogito/version/version.go, config/manager/kustomization.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, kogito-operator.yaml, pkg/version/version.go, test/.default_config
=> Update version to 1.3.0-snapshot

RELEASE_NOTES.md, pkg/infrastructure/services/dashboards.go, pkg/infrastructure/services/dashboards_test.go
Cherry pick for https://github.com/kiegroup/kogito-cloud-operator/pull/762
=> [1.3.x] KOGITO-4444 - Sanitize dashboard name

pkg/infrastructure/services/dashboards.go, pkg/infrastructure/services/dashboards_test.go
Cherry pick regex of https://github.com/kiegroup/kogito-cloud-operator/pull/762
=> [1.3.x] KOGITO-4444 - cherry pick grafana dashboard regex sanitizer

docs/GUIDE_TO_KOGITO_DEVS.md, examples/quarkus-jvm.Dockerfile, examples/springboot.Dockerfile
=> Fix image reference in some examples and guide

docs/GUIDE_TO_KOGITO_DEVS.md, examples/quarkus-jvm.Dockerfile, examples/springboot.Dockerfile
=> [1.3.x] Fix image reference in some examples and guide

test/README.md
[KOGITO-4616](https://issues.redhat.com/browse/KOGITO-4616)
Many thanks for submitting your Pull Request :heart: :robot:! 
=> KOGITO-4616 - Revise BDD tests debugging instructions and add GoLand

Makefile
Jira issue : https://issues.redhat.com/browse/KOGITO-4620
=> [KOGITO-4620] - role.yaml is not updating

cmd/kogito/command/converter/binarybuildtype_converter.go, cmd/kogito/command/converter/binarybuildtype_converter_test.go, cmd/kogito/command/converter/native_converter_test.go, cmd/kogito/command/converter/runtimetype_converter.go, cmd/kogito/command/converter/runtimetype_converter_test.go, cmd/kogito/command/flag/binary_build_type.go, cmd/kogito/command/iozip/zip_files.go, cmd/kogito/command/iozip/zip_files_test.go, cmd/kogito/command/service/build_service.go, cmd/kogito/command/test/mkdir.go, docs/GUIDE_TO_KOGITO_DEVS.md, examples/quarkus-jvm.Dockerfile, test/framework/dockerfile_provider.go
https://issues.redhat.com/browse/KOGITO-4644
=> KOGITO-4644 Support Quarkus fast-jar

RELEASE_NOTES.md
https://issues.redhat.com/browse/KOGITO-4644
=> [KOGITO-4644] Update release notes

RELEASE_NOTES.md
=> Branching 1.4.x - Reset release notes

Makefile, README.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, cmd/kogito/version/version.go, config/manager/kustomization.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, kogito-operator.yaml, test/.default_config, version/version.go
=> [1.4.x] Update version to 1.4.0-snapshot

test/features/install_dataindex.feature
=> Fix typo in MongoDB BDD test

.jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-3107
Small correction from  https://github.com/kiegroup/kogito-operator/pull/737
=> KOGITO-3107 DSL: Correct repo name

README.md
=> Add Kogito operator tested integrations into readme

hack/update_test_config.sh.bats
https://issues.redhat.com/browse/KOGITO-4703
Follow-up on https://github.com/kiegroup/kogito-operator/pull/801#issuecomment-800623322
Tested on master and 1.4.x
=> [KOGITO-4703] correct bats test

test/features/deploy_kogito_runtime.feature, test/features/deploy_travel_agency.feature
https://issues.redhat.com/browse/KOGITO-3756
Depends on https://github.com/kiegroup/kogito-examples/pull/616
=> KOGITO-3756 Added Kafka&MongoDB BDD test

.jenkins/scripts/helper.groovy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-4635
Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/146
- https://github.com/kiegroup/kogito-runtimes/pull/1127
- https://github.com/kiegroup/optaplanner/pull/1214
- https://github.com/kiegroup/kogito-apps/pull/712
- https://github.com/kiegroup/kogito-examples/pull/618
- https://github.com/kiegroup/kogito-images/pull/398
- https://github.com/kiegroup/kogito-operator/pull/804
=> [KOGITO-4635] Allow to override the tag if exists

test/scripts/examples/process-mongodb-persistence-quarkus-example.feature, test/scripts/examples/process-mongodb-persistence-springboot-example.feature
https://issues.redhat.com/browse/KOGITO-4728
=> [KOGITO-4728] Build process mongodb events example

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4742
=> [KOGITO-4742] Reuse nightly example images for BDD PR check

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4775
Following https://github.com/kiegroup/kogito-operator/blob/master/Jenkinsfile.deploy#L180
=> [KOGITO-4775] Solve artifacts saving in PR check

RELEASE_NOTES.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/kogitobuild_controller.go, controllers/kogitoruntime_controller.go, controllers/kogitosupportingservice_controller.go, kogito-operator.yaml
See: https://issues.redhat.com/browse/KOGITO-4333
=> [KOGITO-4333] - Hardening Kogito Operator permissions

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4790
=> [KOGITO-4790] BDD tests: Remove unit test from BDD PR check pipeline

main.go
See: https://issues.redhat.com/browse/KOGITO-4797
=> [KOGITO-4797] - Disable Dev mode in logging by default

test/features/deploy_kogito_runtime.feature, test/scripts/examples/dmn-quarkus-example.feature, test/scripts/examples/dmn-springboot-example.feature
https://issues.redhat.com/browse/KOGITO-4769
=> [KOGITO-4769] BDD tests: Create DMN example test

Makefile, test/Makefile
https://issues.redhat.com/browse/KOGITO-4798
This is the first part of the PR. Another one will come to `rhpam-kogito-operator` to use this new test Makefile.
=> [KOGITO-4798] Extracted Makefile test commands

RELEASE_NOTES.md, core/framework/comparator.go, core/framework/comparator_test.go, core/kogitoservice/deployer_resources.go
https://issues.redhat.com/browse/KOGITO-4826
=> [KOGITO-4826] Service ClusterIPs triggers reconciliation

RELEASE_NOTES.md, core/framework/comparator.go, core/framework/comparator_test.go, core/kogitoservice/deployer_resources.go
https://issues.redhat.com/browse/KOGITO-4826
=> [1.5.x][KOGITO-4826] Service ClusterIPs triggers reconciliation

.github/bot-files/reviewers.yml
=> Updated reviewers bot file

Jenkinsfile.deploy
=> [1.5.x] Correction on deploy pipeline

Makefile, README.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, cmd/kogito/version/version.go, config/manager/kustomization.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, kogito-operator.yaml, test/.default_config, version/version.go
=> [1.5.x] Set 1.5.0-snapshot version

examples/process-quarkus-example-persistence-nobuild.yaml, hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/config/config.go, test/framework/infinispan.go, test/framework/kubernetes.go, test/installers/infinispan_installer.go, test/steps/infinispan.go
https://issues.redhat.com/browse/KOGITO-4877
=> [KOGITO-4877] Implement YAML based approach for Infinispan installation

RELEASE_NOTES.md, examples/springboot.Dockerfile
See: https://issues.redhat.com/browse/KOGITO-4905
I was able to successfully run `docker build --tag quay.io/kmok/process-springboot-example -f springboot.Dockerfile .`.
=> [KOGITO-4905] Fix COPY line in springboot.Dockerfile

.jenkins/dsl/jobs.groovy, Jenkinsfile.promote
=> Corrected examples images deploy job cfg

.jenkins/dsl/jobs.groovy, Jenkinsfile.promote
Following 1.5.x error
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/842
=> [1.5.x] Corrected examples images deploy job cfg

test/pkg/steps/data.go
https://issues.redhat.com/browse/KOGITO-4946
=> [KOGITO-4946] BDD: Allow to modify logged K8s objects

cmd/kogito/command/context/root.go
Jira issue : https://issues.redhat.com/browse/KOGITO-4154
=> [KOGITO-4154] - CLI displays usage page whenever any command fails

Jenkinsfile.examples-images.deploy
https://issues.redhat.com/browse/KOGITO-4973
=> [KOGITO-4973] Correct Examples Images building archiving

examples/springboot.Dockerfile
See: https://issues.redhat.com/browse/KOGITO-4905?focusedCommentId=16073089&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16073089
This is an amendment to my original [KOGITO-4905](https://github.com/kiegroup/kogito-operator/pull/838) PR. I reverted the `COPY` line to its original text, but I modified the comment to make it clear that you must replace the `*.jar` in order for the image to run.
I was able to successfully build and run the process-springboot-example image locally and on OpenShift.
=> [KOGITO-4905] Fix COPY line comment in springboot.Dockerfile

Makefile, README.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, cmd/kogito/version/version.go, config/manager/kustomization.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, hack/ci/operator-ensure-manifests.sh, kogito-operator.yaml, version/version.go
https://issues.redhat.com/browse/KOGITO-4974
=> [1.5.x] [KOGITO-4974] Corrected OLM tests on release branch

RELEASE_NOTES.md, core/kogitoservice/deployer_test.go, core/manager/infra_manager.go
https://issues.redhat.com/browse/KOGITO-4993
=> [KOGITO-4993] Operator crash when data-index is created

test/features/keycloak.feature
=> [1.6.x] Fix explainability dto 

test/features/keycloak.feature
=> Fix explainability dto

RELEASE_NOTES.md, core/kogitoservice/configmap.go, core/kogitoservice/configmap_test.go
See: https://issues.redhat.com/browse/KOGITO-4453
cherry-picks https://github.com/kiegroup/kogito-operator/pull/874
=> [1.5.x] [KOGITO-4453] Fix getAppPropsFromConfigMap

Jenkinsfile.examples-images.promote
=> [1.7.x] Correct promote examples images

Jenkinsfile.examples-images.promote
Backport from https://github.com/kiegroup/kogito-operator/pull/880
=> Correct promote examples images

README.md
=> [1.6.x] Update certification versions

README.md
=> [1.7.x] Update certification versions

README.md
=> Update certification versions

test/features/grafana.feature
https://issues.redhat.com/browse/KOGITO-5182
=> [KOGITO-5182] BDD tests: Fix Grafana test after dashboard name change

hack/update_test_config.sh, hack/update_test_config.sh.bats, test/.default_config
https://issues.redhat.com/browse/KOGITO-4487
Use nightly branch for stability
Related PRs:
- https://github.com/kiegroup/kogito-images/pull/487
- https://github.com/kiegroup/kogito-operator/pull/889
=> [KOGITO-4487] Update to nightly branch for testing

RELEASE_NOTES.md, core/kogitoservice/messaging_knative.go, core/kogitoservice/messaging_knative_test.go, core/test/env.go
See: https://issues.redhat.com/browse/KOGITO-5256
The creation of Knative Triggers was incorrect. The filter must rely on CE Type instead of Kogito Topic name.
=> [KOGITO-5256] - Fix Knative Trigger creation

test/features/deploy_kogito_runtime.feature
https://issues.redhat.com/browse/KOGITO-5297
=> KOGITO-5297 Enable process-timer native BDD test

hack/run-tests.sh, test/Makefile, test/features/deploy_kogito_build.feature, test/pkg/config/config.go, test/pkg/steps/kogitobuild.go
https://issues.redhat.com/browse/KOGITO-5303
=> KOGITO-5303 BDD: Disable SSL on Git option

test/features/deploy_source_files.feature
=> [1.5.x] Change source folder BDD test to use dmn project

test/pkg/installers/prometheus_installer.go, test/pkg/steps/prometheus.go
https://issues.redhat.com/browse/KOGITO-5312
=> [KOGITO-5312] BDD tests: Implement service installer for Prometheus

core/kogitoservice/dashboards.go, go.mod, go.sum, test/pkg/framework/grafana.go, test/pkg/framework/kubernetes.go
https://issues.redhat.com/browse/KOGITO-5348
=> [KOGITO-5348] BDD tests: Use Grafana image based on digest

README.md, RELEASE_NOTES.md, core/kogitoinfra/infinispan_reconciler.go, core/kogitoinfra/infinispan_reconciler_test.go, go.mod, go.sum, test/pkg/framework/infinispan.go, test/pkg/installers/infinispan_installer.go
https://issues.redhat.com/browse/KOGITO-5313
https://issues.redhat.com/browse/KOGITO-5315
=> [KOGITO-5313][KOGITO-5315] Upgrade Kogito operator and BDD tests to Infinispan 12

test/pkg/framework/logging.go
https://issues.redhat.com/browse/KOGITO-5393
=> [KOGITO-5393] BDD tests: Concurrent map read and map write error

test/pkg/framework/logging.go
https://issues.redhat.com/browse/KOGITO-5393
=> [1.8.x] [KOGITO-5393] BDD tests: Concurrent map read and map write error

core/kogitosupportingservice/dataindex_reconciler.go
=> KOGITO-5262 Remove reference to no longer used consumers

core/kogitosupportingservice/dataindex_reconciler.go
(cherry picked from commit 33e6b074674ee40d65f6db8b5b8f4e012bb0ddee)
=> [1.8.x] KOGITO-5262 Remove reference to no longer used consumers (#902)

controllers/kogitobuild_controller.go, core/kogitobuild/buid_config_test.go, core/kogitobuild/build_config.go, core/kogitobuild/build_context.go, core/kogitobuild/decorator.go, core/kogitobuild/decorator_test.go, core/kogitobuild/image_stream.go, core/kogitobuild/image_stream_test.go, core/kogitobuild/manager.go, core/kogitobuild/manager_build_binary.go, core/kogitobuild/manager_build_source.go, core/kogitobuild/manager_test.go, core/kogitobuild/status.go, core/kogitobuild/status_test.go, internal/kogitobuild.go
=> [RHPAM-3681] - [1.5.x] - Introduce BuildContext

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.profiling, test/pkg/framework/namespace.go, test/pkg/installers/service_installer.go
https://issues.redhat.com/browse/KOGITO-5246
=> [KOGITO-5246] Update namespace cleanup

test/pkg/framework/operator.go
https://issues.redhat.com/browse/KOGITO-4362
=> [KOGITO-4362] BDD wait for OperatorGroup creation

test/pkg/config/config.go, test/pkg/executor/bdd_executor.go, test/pkg/framework/http.go, test/pkg/framework/operator.go, test/pkg/installers/grafana_installer.go, test/pkg/installers/infinispan_installer.go, test/pkg/installers/kafka_installer.go, test/pkg/installers/keycloak_installer.go, test/pkg/installers/kogito_installer.go, test/pkg/installers/prometheus_installer.go, test/pkg/installers/service_installer.go, test/pkg/steps/data.go
Adjustments separated into commits.
All are related to the support of BDD tests for Kubernetes environment.
More will come!
I didn't create a JIRA for this as the adjustments are not significant and are focusing just on tests.
=> Various BDD adjustments

README.md, core/kogitosupportingservice/jobsservice_reconciler.go, test/features/install_jobs_service.feature, test/pkg/steps/data.go, test/pkg/steps/kogitojobsservice.go, test/pkg/steps/mappers/create_postgresql_instance.go, test/pkg/steps/postgresql.go
https://issues.redhat.com/browse/KOGITO-4699
=> [KOGITO-4699] BDD tests for Jobs Service with PostgreSQL persistence

README.md, core/kogitosupportingservice/jobsservice_reconciler.go, test/features/install_jobs_service.feature, test/pkg/steps/data.go, test/pkg/steps/kogitojobsservice.go, test/pkg/steps/mappers/create_postgresql_instance.go, test/pkg/steps/postgresql.go
https://issues.redhat.com/browse/KOGITO-4699
=> [1.9.x] [KOGITO-4699] BDD tests for Jobs Service with PostgreSQL persistence

RELEASE_NOTES.md, api/v1beta1/kogitosupportingservice_types.go, api/v1beta1/kogitosupportingservice_types_test.go, core/manager/supportingservice_manager.go, go.sum, internal/kogitosupportingservice.go
cherry-picks https://github.com/kiegroup/kogito-operator/pull/925
Jira Issue : https://issues.redhat.com/browse/KOGITO-5478
=> [KOGITO-5478] - [1.9.x] - Management console does not work on OpenShift

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/929
=> [1.5.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#929)

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/929
=> [1.9.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#929)

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/929
=> [1.8.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#929)

.jenkins/dsl/jobs.groovy, .jenkins/scripts/helper.groovy, Jenkinsfile.deploy, Jenkinsfile.profiling
=> [1.9.x] Use external cluster for tests (#932)

bundle/manifests/kogito-operator.clusterserviceversion.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, go.sum, hack/env.sh
Since operatorhub updated their repositories, we need to change the scripts a bit.
=> Update OLM retrieval + version

.jenkins/scripts/helper.groovy
=> [1.9.x] Correct Maven repository handling

README.md
=> Update of tested certification matrix

.jenkins/dsl/jobs.groovy, Jenkinsfile.deploy, Jenkinsfile.examples-images.deploy, Jenkinsfile.examples-images.promote, Jenkinsfile.profiling, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-5326
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/212
- https://github.com/kiegroup/kogito-runtimes/pull/1449
- https://github.com/kiegroup/optaplanner/pull/1436
- https://github.com/kiegroup/kogito-apps/pull/945
- https://github.com/kiegroup/kogito-examples/pull/800
- https://github.com/kiegroup/kogito-images/pull/602
- https://github.com/kiegroup/kogito-operator/pull/944
- https://github.com/kiegroup/rhpam-kogito-operator/pull/56
=> [KOGITO-5326] Setup deploy/promote notifications on demand

.github/bot-files/comments.yml, .github/pull_request_template.md, .github/workflows/jenkins-tests-PR.yml, .jenkins/dsl/test.sh, README.md, bundle/manifests/kogito-operator.clusterserviceversion.yaml, cmd/kogito/command/install/supportingservices.go, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, core/framework/image.go, docs/GUIDE_FOR_KOGITO_DEVS.md, examples/data-index-mongodb.yaml, examples/data-index.yaml, examples/explainability.yaml, examples/kogitoinfra-kafka.yaml, examples/kubernetes/travel-agency/data-index.yaml, examples/process-quarkus-example-persistence.yaml, examples/springboot.yaml, examples/travelapp-kogito-travel-agency.yaml, examples/travelapp-kogito-visas.yaml, examples/trusty.yaml, hack/run-tests.sh, hack/update_test_config.sh, hack/update_test_config.sh.bats, test/.default_config
**PLEASE DO NOT MERGE. THIS WILL BE DONE WHEN `master` will be renamed as `main`**
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/188
- https://github.com/kiegroup/kogito-runtimes/pull/1365
- https://github.com/kiegroup/optaplanner/pull/1372
- https://github.com/kiegroup/optaweb-employee-rostering/pull/660
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/532
- https://github.com/kiegroup/optaplanner-quickstarts/pull/144
- https://github.com/kiegroup/kogito-apps/pull/882
- https://github.com/kiegroup/kogito-examples/pull/729
- https://github.com/kiegroup/kogito-images/pull/516
- https://github.com/kiegroup/kogito-operator/pull/905
- https://github.com/kiegroup/rhpam-kogito-operator/pull/44
Please make sure …
=> BXMSPROD-1265: Conscious language initiative

hack/env.sh
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/947
=> [1.9.x] Update OLM retrieval + version (#947)

bundle/manifests/kogito-operator.clusterserviceversion.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, hack/ci/operator-ensure-manifests.sh, hack/ci/run-olm-tests.sh
=> [1.9.x] Correct OLM tests

hack/ci/run-olm-tests.sh
=> Correct OLM tests link

.jenkins/dsl/jobs.groovy, .jenkins/scripts/helper.groovy, Jenkinsfile.deploy, Jenkinsfile.profiling
=> [1.10.x] Setup QE production cluster for tests

go.tools.mod, go.tools.sum, hack/addheaders.sh
=> Fix build problem with addlicense library

test/pkg/framework/kogitoruntime.go, test/pkg/framework/kogitoserviceutils.go
https://issues.redhat.com/browse/KOGITO-5694
=> [KOGITO-5694] BDD tests: Increase failure threshold for startup probe

api/kogitoinfra_types.go, api/v1beta1/kogitoinfra_types.go, test/pkg/framework/kogitoinfra.go, test/pkg/framework/mappers/cr_to_cli.go, test/pkg/steps/kogitoinfra.go, test/pkg/steps/mappers/create_kogito_infra.go
https://issues.redhat.com/browse/KOGITO-5685
Related PRs:
- https://github.com/kiegroup/kogito-operator/pull/968
- https://github.com/kiegroup/rhpam-kogito-operator/pull/63
=> KOGITO-5685 RHPAM BDD tests with events

go.tools.mod, go.tools.sum, hack/addheaders.sh
Cherry-pick: https://github.com/kiegroup/kogito-operator/pull/969
=> Fix build problem with addlicense library (#969)

core/kogitoservice/dashboards.go
Dashboard name must follow RFC 1123 standard
https://issues.redhat.com/browse/KOGITO-5688
=> [KOGITO-5688] Correct sanitize dashboard names

test/features/keycloak.feature
https://issues.redhat.com/browse/KOGITO-5707
=> KOGITO-5707 Disable mgmt/task keycloak tests

test/features/keycloak.feature
https://issues.redhat.com/browse/KOGITO-5707
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/978
=> [1.10.x] KOGITO-5707 BDD: Disable mgmt/task keycloak tests

go.mod, go.sum, hack/run-tests.sh, hack/run-tests.sh.bats, meta/meta.go, test/Makefile, test/features/kogito_service_performance.feature, test/pkg/config/config.go, test/pkg/framework/http.go, test/pkg/installers/hyperfoil_installer.go, test/pkg/steps/data.go, test/pkg/steps/hyperfoil.go
https://issues.redhat.com/browse/KOGITO-5612
=> [KOGITO-5612] BDD tests: Migrate performance tests to Hyperfoil

.jenkins/dsl/jobs.groovy, .jenkins/scripts/helper.groovy, Jenkinsfile.deploy, README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/features/deploy_kogito_build.feature, test/pkg/config/config.go, test/pkg/framework/maven.go, test/pkg/steps/kogitobuild.go
https://issues.redhat.com/browse/KOGITO-5636
=> KOGITO-5636 Native build image with another image

Jenkinsfile.deploy, Jenkinsfile.examples-images.deploy
=> Update Jenkins deploy jobs

.jenkins/scripts/helper.groovy
Related PRs:
- https://github.com/kiegroup/kogito-operator/pull/985
- https://github.com/kiegroup/rhpam-kogito-operator/pull/66
=> BDD: Removed usage of Maven mirror

RELEASE_NOTES.md, api/v1beta1/artifact.go, api/v1beta1/gitsource.go, api/v1beta1/kogitobuild_types.go, api/v1beta1/kogitoinfra_types.go, api/v1beta1/kogitoruntime_types.go, api/v1beta1/kogitoservices.go, api/v1beta1/kogitosupportingservice_types.go, api/v1beta1/probe.go, api/v1beta1/zz_generated.openapi.go, bundle/manifests/app.kiegroup.org_kogitobuilds.yaml, bundle/manifests/app.kiegroup.org_kogitoinfras.yaml, bundle/manifests/app.kiegroup.org_kogitoruntimes.yaml, bundle/manifests/app.kiegroup.org_kogitosupportingservices.yaml, bundle/manifests/kogito-operator.clusterserviceversion.yaml, config/crd/bases/app.kiegroup.org_kogitobuilds.yaml, config/crd/bases/app.kiegroup.org_kogitoinfras.yaml, config/crd/bases/app.kiegroup.org_kogitoruntimes.yaml, config/crd/bases/app.kiegroup.org_kogitosupportingservices.yaml, config/manifests/bases/kogito-operator.clusterserviceversion.yaml, kogito-operator.yaml, profiling/kogito-operator-profiling.yaml
https://issues.redhat.com/browse/KOGITO-3793
=> [KOGITO-3793] Review OLM UI spec descriptors

hack/bump-version.sh, hack/ci/operator-ensure-manifests.sh, hack/ci/run-olm-tests.sh, hack/clean-crds.sh, hack/clean-stuck-namespaces.sh, hack/client-gen.sh, hack/create-olm-manifests.sh, hack/env.sh, hack/openapi.sh, hack/run-tests.sh, hack/update_test_config.sh
https://issues.redhat.com/browse/KOGITO-5762
=> KOGITO-5762 BDD: Cleanup crds

hack/bump-version.sh, hack/ci/operator-ensure-manifests.sh, hack/ci/run-olm-tests.sh, hack/clean-crds.sh, hack/clean-stuck-namespaces.sh, hack/create-olm-manifests.sh, hack/env.sh, hack/run-tests.sh, hack/update_test_config.sh
https://issues.redhat.com/browse/KOGITO-5762
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/990
=> [1.11.x] KOGITO-5762 BDD: Cleanup crds (#990)

README.md
=> Upgrade Kogito Operator tested integrations

RELEASE_NOTES.md, controllers/kogitoinfra_controller.go, core/kogitoinfra/status.go, core/kogitoinfra/status_test.go
https://issues.redhat.com/browse/KOGITO-5811
=> [KOGITO-5811] - no kind is registered for the type v1beta1.KogitoInfra

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/scripts/helper.groovy
https://issues.redhat.com/browse/KOGITO-5781
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/247
- https://github.com/kiegroup/kogito-images/pull/686
- https://github.com/kiegroup/kogito-operator/pull/994
=> KOGITO-5781 Push reduced tag in deploy pipeline

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/scripts/helper.groovy
https://issues.redhat.com/browse/KOGITO-5781
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/994
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/250
- https://github.com/kiegroup/kogito-images/pull/712
- https://github.com/kiegroup/kogito-operator/pull/1001
=> [1.11.x] KOGITO-5781 Push reduced tag in deploy pipeline (#994)

README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/pkg/config/config.go, test/pkg/framework/kogitobuild.go
https://issues.redhat.com/browse/KOGITO-5837
=> KOGITO-5837 BDD: Split jvm and native runtime imgs

hack/update_test_config.sh, hack/update_test_config.sh.bats
https://issues.redhat.com/browse/KOGITO-5857
=>  [KOGITO-5857] Correct bats test

hack/update_test_config.sh, hack/update_test_config.sh.bats
https://issues.redhat.com/browse/KOGITO-5857
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1008
=> [1.11.x] [KOGITO-5857] Correct bats test

README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/features/deploy_kogito_runtime.feature, test/features/service_discovery.feature, test/pkg/config/config.go, test/pkg/framework/dockerfile_provider.go, test/pkg/framework/kogitobuild.go, test/pkg/framework/util.go
https://issues.redhat.com/browse/KOGITO-5837
https://issues.redhat.com/browse/KOGITO-5845
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1003 + https://github.com/kiegroup/kogito-operator/pull/1005
=> [1.11.x] [KOGITO-5837] [KOGITO-5845] BDD: Split jvm and native runtime imgs (#1003)(#1005)

test/pkg/executor/bdd_executor.go, test/pkg/steps/data.go
https://issues.redhat.com/browse/KOGITO-5692
=> [KOGITO-5692] Store objects to be logged to Data struct

test/pkg/executor/bdd_executor.go, test/pkg/steps/data.go
https://issues.redhat.com/browse/KOGITO-5692
=> [1.11.x] [KOGITO-5692] Store objects to be logged to Data struct

hack/clean-cluster-operators.sh, hack/clean-crds.sh, hack/env.sh, hack/run-tests.sh, hack/run-tests.sh.bats
https://issues.redhat.com/browse/KOGITO-5865
=> [KOGITO-5865] BDD: Cleanup installed operators

hack/clean-cluster-operators.sh, hack/clean-crds.sh, hack/env.sh, hack/run-tests.sh, hack/run-tests.sh.bats
https://issues.redhat.com/browse/KOGITO-5865
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1012
=> [1.11.x] [KOGITO-5865] BDD: Cleanup installed operators

test/features/deploy_kogito_runtime.feature, test/features/service_discovery.feature, test/pkg/framework/dockerfile_provider.go, test/pkg/framework/kogitobuild.go, test/pkg/framework/util.go
https://issues.redhat.com/browse/KOGITO-5845
=> KOGITO-5845 Add @rhpam native scenarios

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/scripts/helper.groovy, go.sum, hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/pkg/config/config.go, test/pkg/framework/kogitoserviceutils.go, test/pkg/framework/util.go, test/pkg/steps/image_registry.go
https://issues.redhat.com/browse/KOGITO-5888
=> [KOGITO-5888] Remove namespace option from BDD tests

.github/workflows/Kogito-Operator-PR-Check.yaml, hack/run-tests.sh, test/features/kogito_service_performance.feature, test/pkg/framework/kubernetes.go, test/pkg/installers/hyperfoil_node_scraper_installer.go, test/pkg/steps/hyperfoil.go
https://issues.redhat.com/browse/KOGITO-5745
=> [KOGITO-5745] BDD tests: Add Node scraper for performance tests

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5730
This will reorganize the different jobs in a specific branch folder and allow automatically deleting jobs when the concerned branch is removed from the [main config](https://github.com/kiegroup/kogito-pipelines/blob/main/dsl/seed/config/main.yaml#L2)
Example: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-5730/
Here are the new mapping: 
- nightly/{branch}/... => {branch}/nightly/...
- release/{branch}/... => {branch}/release/...
- pullrequest/{branch}/... => {branch}/pullrequest/...
- tools/{branch}/... => {branch}/tools/...
- other/{branch}/... => {branch}/other/...
**All PRs should be merged at the same time !!!!**
Dependent PRs:
- …
=> KOGITO-5730 Restructure DSL folders

.ci/jenkins/dsl/jobs.groovy
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/987
https://issues.redhat.com/browse/KOGITO-5730
This will reorganize the different jobs in a specific branch folder and allow automatically deleting jobs when the concerned branch is removed from the [main config](https://github.com/kiegroup/kogito-pipelines/blob/main/dsl/seed/config/main.yaml#L2)
Example: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-5730/
Here are the new mappings: 
- nightly/{branch}/... => {branch}/nightly/...
- release/{branch}/... => {branch}/release/...
- pullrequest/{branch}/... => {branch}/pullrequest/...
- tools/{branch}/... => {branch}/tools/...
- other/{branch}/... => {branch}/other/...
**All PRs should be merged at the same time …
=> [1.11.x] KOGITO-5730 Restructure DSL folders (#987)

test/pkg/config/config.go, test/pkg/installers/kogito_installer.go
https://issues.redhat.com/browse/KOGITO-5945
=> [KOGITO-5945] BDD tests: Add option to run tests using released operator

hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/pkg/config/config.go, test/pkg/steps/hyperfoil.go
=> BDD tests: Allow configuring Hyperfoil controller image version

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/scripts/helper.groovy, Makefile, hack/ci/install-operator-sdk.sh, hack/ci/uninstall-operator-sdk.sh, test/pkg/steps/data.go
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1024
https://issues.redhat.com/browse/BXMSPROD-1478
Depends on
- https://github.com/kiegroup/kogito-pipelines/pull/263
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1107
=> [1.11.x] BXMSPROD-1478 Setup Jenkins pipelines with new golang

test/go.mod, test/go.sum
=> BDD tests: Update golang.org/x/sys

hack/run-tests.sh, hack/run-tests.sh.bats, test/Makefile, test/pkg/config/config.go, test/pkg/framework/infinispan.go
=> BDD tests: Add support for Infinispan storage class

go.mod, go.sum, hack/run-tests.sh, test/features/install_dataindex.feature, test/features/install_jobs_service.feature, test/features/install_trusty.feature, test/go.mod, test/go.sum, test/pkg/framework/graphql.go, test/pkg/framework/http.go, test/pkg/framework/kubernetes.go, test/pkg/framework/mongodb.go, test/pkg/framework/postgresql.go, test/pkg/steps/graphql.go, test/pkg/steps/graphql_queries.go, test/pkg/steps/http.go, test/pkg/steps/mongodb.go, test/pkg/steps/postgresql.go
https://issues.redhat.com/browse/KOGITO-5947
=> [KOGITO-5947] BDD - Kogito Services failover tests

test/pkg/framework/operator.go
[KOGITO-6260](https://issues.redhat.com/browse/KOGITO-6260)
<details>
<summary>
</summary>
</details>
=> [KOGITO-6260] BDD tests: Don't delete Subscriptions not created by BDD

test/features/deploy_kogito_runtime.feature, test/features/keycloak.feature, test/go.mod, test/go.sum
<details>
<summary>
</summary>
</details>
=> [1.14.x] Fix bdd tests

test/features/deploy_kogito_runtime.feature, test/features/keycloak.feature
<details>
<summary>
</summary>
</details>
=> Fix BDD tests

core/kogitoinfra/infinispan_reconciler.go, core/kogitoinfra/mongodb_reconciler.go, docs/GUIDE_FOR_KOGITO_DEVS.md, examples/data-index.yaml, examples/jobs-service-infinispan.yaml, examples/kogitoinfra-infinispan.yaml, examples/kubernetes/travel-agency/data-index.yaml, examples/process-quarkus-example-persistence-nobuild.yaml, examples/process-quarkus-example-persistence.yaml, examples/travelapp-kogito-travel-agency.yaml, examples/travelapp-kogito-visas.yaml, examples/trusty.yaml
<details>
<summary>
</summary>
</details>
=> [1.11.x] BAPL-1990 conscious language

core/kogitoinfra/infinispan_reconciler.go, core/kogitoinfra/mongodb_reconciler.go, docs/GUIDE_FOR_KOGITO_DEVS.md, examples/app/data-index.yaml, examples/app/jobs-service-infinispan.yaml, examples/app/kogitoinfra-infinispan.yaml, examples/app/kubernetes/travel-agency/data-index.yaml, examples/app/process-quarkus-example-persistence-nobuild.yaml, examples/app/process-quarkus-example-persistence.yaml, examples/app/travelapp-kogito-travel-agency.yaml, examples/app/travelapp-kogito-visas.yaml, examples/app/trusty.yaml
<details>
<summary>
</summary>
</details>
=> BAPL-1990 conscious language

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.profiling
Due to Jenkins build failure
<details>
<summary>
</summary>
</details>
=> [1.11.x] Ignore CLI build

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/BXMSPROD-1577
<details>
<summary>
</summary>
</details>
=> BXMSPROD-1577 Improved result message for nightlies

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/BXMSPROD-1577
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1097
<details>
<summary>
</summary>
</details>
=> [1.15.x] BXMSPROD-1577 Improved result message for nightlies (#1097)

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/BXMSPROD-1577
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1097
<details>
<summary>
</summary>
</details>
=> [1.11.x] BXMSPROD-1577 Improved result message for nightlies (#1097)

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.profiling
<details>
<summary>
</summary>
</details>
=> Send test error logs to Zulip

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
<details>
<summary>
</summary>
</details>
=> KOGITO-6513: add issues template

content-sets.yaml, rhpam-image-bundle.yaml, rhpam-image-prod.yaml, rhpam-image.yaml
<details>
<summary>
</summary>
</details>
=> Setup content_sets for RHPAM images

test/pkg/framework/operator.go
[KOGITO-6604](https://issues.redhat.com/browse/KOGITO-6604)
<details>
<summary>
</summary>
</details>
=> [KOGITO-6604] Fail fast when Subscription constraint fails

test/features/deploy_source_files.feature, test/pkg/framework/grafana.go, test/pkg/installers/grafana_installer.go, test/pkg/installers/infinispan_installer.go, test/pkg/steps/deploy_files.go
<details>
<summary>
</summary>
</details>
=> [1.16.x] Corrected BDD tests

test/features/deploy_source_files.feature, test/pkg/framework/grafana.go, test/pkg/installers/grafana_installer.go, test/pkg/installers/infinispan_installer.go, test/pkg/steps/deploy_files.go
<details>
<summary>
</summary>
</details>
=> Corrected BDD tests

README.md, hack/run-tests.sh, hack/run-tests.sh.bats, test/features/deploy_source_files.feature, test/pkg/config/config.go, test/pkg/installers/amqstreams_installer.go, test/pkg/steps/deploy_files.go
<details>
<summary>
</summary>
</details>
=> BDD tests: Handle different URL for archetype mirror URL

README.md, test/features/grafana.feature, test/features/prometheus.feature
<details>
<summary>
</summary>
</details>
=> BDD: Added tags to prometheus/grafana tests

.github/ISSUE_TEMPLATE/config.yml
<details>
<summary>
</summary>
</details>
=> Fix typo in ISSUES_TEMPLATE/config.yml 

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.profiling
https://issues.redhat.com/browse/KOGITO-5531
PR checks modifications will be handled with rebuild of image, after https://github.com/kiegroup/kogito-pipelines/pull/214 is merged
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/214
- https://github.com/kiegroup/kogito-runtimes/pull/1446
- https://github.com/kiegroup/optaplanner/pull/1815
- https://github.com/kiegroup/kogito-apps/pull/942
- https://github.com/kiegroup/kogito-examples/pull/797
- https://github.com/kiegroup/kogito-operator/pull/1123
=> KOGITO-5531 Update Jenkins CI to Maven 3.8.1

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.profiling
https://issues.redhat.com/browse/KOGITO-5531
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1123
=> [1.16.x] KOGITO-5531 Update Jenkins CI to Maven 3.8.1

RELEASE_NOTES.md, cmd/kogito/command/deploy/delete_service.go, cmd/kogito/command/deploy/deploy_service.go, cmd/kogito/command/flag/install_flag.go, cmd/kogito/command/project/delete_project_test.go, cmd/kogito/command/remove/kogitoinfra.go, cmd/kogito/command/shared/resource_checks.go
Signed-off-by: Davide Salerno <dsalerno@redhat.com>
See: https://issues.redhat.com/browse/KOGITO-2787
<details>
<summary>
</summary>
</details>
=> [KOGITO-2787] Unify namespace/project wording in logs and Kogito CLI

.ci/jenkins/Jenkinsfile-rhpam, bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoruntimes.yaml, bundle/rhpam/manifests/rhpam.kiegroup.org_kogitosupportingservices.yaml, config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
<details>
<summary>
</summary>
</details>
=> Setup multiarch CSV file

test/pkg/framework/grafana.go, test/pkg/installers/grafana_installer.go
<details>
<summary>
</summary>
</details>
=> [1.11.x] Update Grafana operator/image version

Makefile
<details>
<summary>
</summary>
</details>
=> [1.13.x] - Fix CSV cmd

Makefile
<details>
<summary>
</summary>
</details>
=> [main] - Fix CSV cmd

test/pkg/framework/grafana.go
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1141
<details>
<summary>
</summary>
</details>
=> [1.18.x] Update Grafana image version to 7.5.15 (#1141)

test/pkg/framework/infinispan.go, test/pkg/framework/kubernetes.go, test/pkg/steps/infinispan.go
https://issues.redhat.com/browse/KOGITO-6888
<details>
<summary>
</summary>
</details>
=> KOGITO-6888 Corrected scale to 0 of Infinispan

Makefile.rhpam, RELEASE_NOTES.md, bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
See: https://issues.redhat.com/browse/KOGITO-6907
<details>
<summary>
</summary>
</details>
=> [KOGITO-6907] - Add subscription annotations to and Kogito operator

test/features/deploy_travel_agency.feature, test/pkg/steps/task.go
https://issues.redhat.com/browse/KOGITO-7083
<details>
<summary>
</summary>
</details>
=> KOGITO-7083 Corrected Travel agency scenarios

rhpam-image-prod.yaml
<details>
<summary>
</summary>
</details>
=> [1.13.x] Fix cachito configuration after repo migration

.ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .github/workflows/jenkins-tests-PR.yml
https://issues.redhat.com/browse/KOGITO-6962
Depends on https://github.com/kiegroup/kogito-pipelines/pull/416
=> KOGITO-6962 DSL reorganization for flexibility

content_sets.yaml
<details>
<summary>
</summary>
</details>
=> [1.13.x] fix ppc64le section in content_sets.yaml

content_sets.yaml
<details>
<summary>
</summary>
</details>
=> fix ppc64le section in content_sets.yaml

.ci/jenkins/Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-7100
Related PRs:
- https://github.com/kiegroup/drools/pull/4355
- https://github.com/kiegroup/optaplanner/pull/1966
- https://github.com/kiegroup/kogito-runtimes/pull/2187
- https://github.com/kiegroup/kogito-apps/pull/1330
- https://github.com/kiegroup/kogito-examples/pull/1244
- https://github.com/kiegroup/kogito-images/pull/1251
- https://github.com/kiegroup/kogito-operator/pull/1183
=> [KOGITO-7100] Jenkinsfiles: Corrected boolean env var handling

.ci/jenkins/dsl/jobs.groovy, .ci/jenkins/scripts/helper.groovy
https://issues.redhat.com/browse/KOGITO-7110
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/438
- https://github.com/kiegroup/drools/pull/4364
- https://github.com/kiegroup/kogito-runtimes/pull/2192
- https://github.com/kiegroup/kogito-apps/pull/1332
- https://github.com/kiegroup/kogito-examples/pull/1247
- https://github.com/kiegroup/kogito-images/pull/1252
- https://github.com/kiegroup/kogito-operator/pull/1184
- https://github.com/kiegroup/optaplanner/pull/1969
=> KOGITO-7110 Correct nightly DSL generation

test/features/install_trusty.feature
<details>
<summary>
</summary>
</details>
=> Fixes from 1.21.x release

test/features/deploy_travel_agency.feature, test/features/install_trusty.feature, test/pkg/steps/task.go
<details>
<summary>
</summary>
</details>
=> [1.21.x] Fixes from release

test/features/deploy_kogito_runtime.feature
https://issues.redhat.com/browse/KOGITO-7153
<details>
<summary>
</summary>
</details>
=> KOGITO-7153 Remove Optaplanner BDD tests

.gitignore, test/features/deploy_kogito_build.feature, test/features/deploy_kogito_runtime.feature, test/features/deploy_source_files.feature, test/features/service_discovery.feature, test/pkg/framework/kafka.go, test/pkg/framework/maven.go, test/pkg/framework/openshift.go, test/pkg/steps/kafka.go
<details>
<summary>
</summary>
</details>
=> [7.13.x] QE fixes

.gitignore, Makefile, bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manager/rhpam/manager.yaml, rhpam-operator.yaml, test/pkg/framework/openshift.go, test/pkg/installers/rhpam_kogito_installer.go
backports:
- https://github.com/kiegroup/kogito-operator/pull/1186 
- https://github.com/kiegroup/kogito-operator/pull/1185
<details>
<summary>
</summary>
</details>
=> 7.13 fix backports

test/pkg/framework/postgresql.go
https://issues.redhat.com/browse/KOGITO-7323
<details>
<summary>
</summary>
</details>
=> KOGITO-7323 Add probes to postgres deployment

test/features/deploy_source_files.feature, test/pkg/steps/deploy_files.go
https://issues.redhat.com/browse/KOGITO-7217
<details>
<summary>
</summary>
</details>
=> [1.13.x] KOGITO-7217 Tests: Use starters for spring boot archetype

test/pkg/steps/prometheus.go
Tested locally.
<details>
<summary>
</summary>
</details>
=> Fix Prometheus cucumber test

test/pkg/steps/prometheus.go
Cherrypick of https://github.com/kiegroup/kogito-operator/pull/1210
<details>
<summary>
</summary>
</details>
=> [1.13.x] Fix Prometheus cucumber test

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, version/rhpam/version.go
Signed-off-by: Davide Salerno <dsalerno@redhat.com>
<details>
<summary>
</summary>
</details>
=> [RHPAM- 4269] - Fix replaces version with latest one

hack/rhpam/rhpam-update-bundle.sh
<details>
<summary>
</summary>
</details>
=> Fix wrong replace script for bundle CSV

test/pkg/steps/mappers/create_kogito_build.go
<details>
<summary>
</summary>
</details>
=> Cucumber tests: Fix WebHook mapping for both operators

.ci/jenkins/Jenkinsfile-rhpam, test/pkg/installers/rhpam_kogito_installer.go, test/pkg/steps/mappers/create_kogito_build.go
<details>
<summary>
</summary>
</details>
=> [1.13.x] Cucumber tests: Fix WebHook mapping for both operators

test/pkg/steps/prometheus.go
<details>
<summary>
</summary>
</details>
=> [1.23.x] Fix Prometheus cucumber test (#1210)

test/pkg/installers/amqstreams_installer.go
<details>
<summary>
</summary>
</details>
=> [1.13.x] Update AMQ streams operator version

test/pkg/installers/amqstreams_installer.go
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1225
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue] Update AMQ streams operator version

test/pkg/installers/amqstreams_installer.go
backport: https://github.com/kiegroup/kogito-operator/pull/1225
<details>
<summary>
</summary>
</details>
=> Update AMQ streams operator version

config/full/rhpam/manager_auth_proxy_patch.yaml, rhpam-operator.yaml
cherry-picks https://github.com/kiegroup/kogito-operator/pull/1228
<details>
<summary>
</summary>
</details>
=> [1.13.x] [KOGITO-7481] - Update ose-kube-rbac-proxy to v4.10.0

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/full/rhpam/manager_auth_proxy_patch.yaml, rhpam-operator.yaml
cherry-picks https://github.com/kiegroup/kogito-operator/pull/1228
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue] [KOGITO-7481] - Update ose-kube-rbac-proxy to v4.10.0

RELEASE_NOTES.md, bundle/app/manifests/kogito-operator.clusterserviceversion.yaml, bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/full/app/manager_auth_proxy_patch.yaml, config/full/rhpam/manager_auth_proxy_patch.yaml, config/manager/rhpam/kustomization.yaml, kogito-operator.yaml, profiling/kogito-operator-profiling.yaml, rhpam-operator.yaml
<details>
<summary>
</summary>
</details>
=> [KOGITO-7481] - Update ose-kube-rbac-proxy to v4.10.0

RELEASE_NOTES.md
<details>
<summary>
</summary>
</details>
=> clean release_notes.md

.github/workflows/jenkins-tests-PR.yml
<details>
<summary>
</summary>
</details>
=> Update GHA DSL check to use composite action

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/269
- https://github.com/kiegroup/drools/pull/4518
- https://github.com/kiegroup/kogito-runtimes/pull/1622
- https://github.com/kiegroup/kogito-apps/pull/1405
- https://github.com/kiegroup/kogito-examples/pull/1323
- https://github.com/kiegroup/kogito-operator/pull/1239
- https://github.com/kiegroup/optaplanner/pull/2061
=> KOGITO-5780 Set JDK and Maven tools as env vars

RELEASE_NOTES.md, examples/app/user-friendly/process-quarkus-example.yaml
Jira issue : https://issues.redhat.com/browse/KOGITO-6297
<details>
<summary>
</summary>
</details>
=> [KOGITO-6297] - Add example in kogito-operator repo

rhpam-image-bundle.yaml, rhpam-image-prod.yaml, rhpam-image.yaml
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue] update brew packages name, repositories names and branches

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manager/rhpam/manager.yaml, config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue][KOGITO-7457] update csv sources repo

test/features/deploy_kogito_build.feature, test/features/deploy_kogito_runtime.feature
<details>
<summary>
</summary>
</details>
=> [1.13.x] Set back native checks

test/features/deploy_kogito_build.feature, test/features/deploy_kogito_runtime.feature
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue] Set back native checks

test/pkg/framework/grafana.go
<details>
<summary>
</summary>
</details>
=> [1.25.x] BDD: Update grafana image version

test/pkg/framework/grafana.go
<details>
<summary>
</summary>
</details>
=> BDD: Update grafana image version

test/pkg/framework/grafana.go
<details>
<summary>
</summary>
</details>
=> [1.13.x] BDD: Update grafana image version (#1254)

.ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/dsl/jobs.groovy
Example init commit: https://github.com/kiegroup/kogito-operator/pull/1264/commits/a4bc8c1cba32217e7c0a0eca71e05414dda96fbf
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/591
- https://github.com/kiegroup/drools/pull/4631
- https://github.com/kiegroup/kogito-runtimes/pull/2410
- https://github.com/kiegroup/kogito-apps/pull/1443
- https://github.com/kiegroup/kogito-examples/pull/1380
- https://github.com/kiegroup/kogito-images/pull/1323
- https://github.com/kiegroup/kogito-operator/pull/1264
- https://github.com/kiegroup/kogito-docs/pull/176
=> KOGITO-7785 Setup init-branch job

test/features/install_jobs_service.feature, test/features/keycloak.feature
<details>
<summary>
</summary>
</details>
=> [1.27.x] Fix Jobs Service BDD tests

test/features/install_jobs_service.feature, test/features/keycloak.feature
<details>
<summary>
</summary>
</details>
=> Fix Jobs Service BDD tests

.github/workflows/Kogito-Operator-OLM-tests.yaml, README.md
<details>
<summary>
</summary>
</details>
=> [1.13.x] Correct OLM tests

modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml, rhpam-image-bundle.yaml, rhpam-image-prod.yaml, rhpam-image.yaml
<details>
<summary>
</summary>
</details>
=> bump versions to 7.13.1

.ci/jenkins/Jenkinsfile, hack/run-tests.sh
Introduced by https://github.com/kiegroup/kogito-operator/pull/1279
<details>
<summary>
</summary>
</details>
=> Remove useless debug commands

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, hack/rhpam/rhpam-update-bundle.sh, modules/org.kie.kogito.rhpam.builder/module.yaml
<details>
<summary>
</summary>
</details>
=> [1.13.x] [KIECLOUD-654] - bundle replaces points to wrong previous version

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/631
- https://github.com/kiegroup/drools/pull/4723
- https://github.com/kiegroup/kogito-runtimes/pull/2525
- https://github.com/kiegroup/kogito-apps/pull/1483
- https://github.com/kiegroup/kogito-examples/pull/1423
- https://github.com/kiegroup/kogito-images/pull/1342
- https://github.com/kiegroup/kogito-operator/pull/1293
- https://github.com/kiegroup/kogito-docs/pull/218
- https://github.com/kiegroup/kie-tools/pull/1249
- https://github.com/kiegroup/optaplanner/pull/2219
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/760
- https://github.com/kiegroup/optaplanner-quickstarts/pull/415
=> KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/632
- https://github.com/kiegroup/kogito-pipelines/pull/633
- https://github.com/kiegroup/drools/pull/4724
- https://github.com/kiegroup/kogito-runtimes/pull/2526
- https://github.com/kiegroup/kogito-apps/pull/1484
- https://github.com/kiegroup/kogito-examples/pull/1424
- https://github.com/kiegroup/kogito-images/pull/1343
- https://github.com/kiegroup/kogito-operator/pull/1294
- https://github.com/kiegroup/kogito-docs/pull/219
=> [1.27.x] KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/638
- https://github.com/kiegroup/kogito-runtimes/pull/2529
- https://github.com/kiegroup/kogito-examples/pull/1427
- https://github.com/kiegroup/kogito-images/pull/1346
- https://github.com/kiegroup/kogito-operator/pull/1297
=> [1.13.x-blue] KOGITO-8043 Jenkins node master -> built-in

bamoe-image-bundle.yaml, bamoe-image-prod.yaml, bamoe-image.yaml, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue] bump versions to 8.0.1

bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, hack/rhpam/rhpam-update-bundle.sh
Related PR:
- https://github.com/kiegroup/kogito-operator/pull/1277
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue] bundle replaces points to wrong previous version

RELEASE_NOTES.md, bundle/app/manifests/kogito-operator.clusterserviceversion.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitobuilds.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoinfras.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoruntimes.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitosupportingservices.yaml, config/manager/app/manager.yaml, config/manager/rhpam/manager.yaml, config/rbac/rhpam/role.yaml, core/deployment/deployment_processor.go, core/deployment/deployment_processor_test.go, go.mod, kogito-operator.yaml, profiling/kogito-operator-profiling.yaml, rhpam-operator.yaml
Signed-off-by: spolti <filippespolti@gmail.com>
See: https://issues.redhat.com/browse/KOGITO-8088
<details>
<summary>
</summary>
</details>
=> [KOGITO-8088][RHPAM-4437] - Gain All Capabilities Using Unshare

RELEASE_NOTES.md, bundle/app/manifests/kogito-operator.clusterserviceversion.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitobuilds.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoinfras.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoruntimes.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitosupportingservices.yaml, config/manager/app/manager.yaml, config/manager/rhpam/manager.yaml, config/rbac/rhpam/role.yaml, core/kogitoservice/kogito_deployment.go, core/kogitoservice/kogito_deployment_test.go, go.mod, kogito-operator.yaml, profiling/kogito-operator-profiling.yaml, rhpam-operator.yaml
Signed-off-by: spolti <filippespolti@gmail.com>
See: https://issues.redhat.com/browse/RHPAM-4437
<details>
<summary>
</summary>
</details>
=> [1.13.x][RHPAM-4437] - Gain All Capabilities Using Unshare

RELEASE_NOTES.md, bamoe-operator.yaml, bundle/app/manifests/kogito-operator.clusterserviceversion.yaml, config/manager/app/manager.yaml, config/manager/bamoe/manager.yaml, core/kogitoservice/kogito_deployment.go, core/kogitoservice/kogito_deployment_test.go, go.mod, kogito-operator.yaml, profiling/kogito-operator-profiling.yaml
See: https://issues.redhat.com/browse/RHPAM-4437
Cherry-picks: https://github.com/kiegroup/kogito-operator/pull/1303
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue][RHPAM-4437] - Gain All Capabilities Using Unshare

.ci/jenkins/dsl/test.sh, .github/workflows/Kogito-Operator-PR-Check.yaml, .github/workflows/Kogito-Operator-Unit-tests.yaml, .github/workflows/jenkins-tests-PR.yml
https://issues.redhat.com/browse/KOGITO-8110
- https://github.com/kiegroup/kogito-pipelines/pull/646
- https://github.com/kiegroup/drools/pull/4738
- https://github.com/kiegroup/kogito-runtimes/pull/2547
- https://github.com/kiegroup/kogito-apps/pull/1489
- https://github.com/kiegroup/kogito-examples/pull/1440
- https://github.com/kiegroup/kogito-images/pull/1348
- https://github.com/kiegroup/kogito-operator/pull/1305
- https://github.com/kiegroup/kogito-docs/pull/228
- https://github.com/kiegroup/optaplanner/pull/2242
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/770
- https://github.com/kiegroup/optaplanner-quickstarts/pull/428
- https://github.com/kiegroup/kie-tools/pull/1271
=> KOGITO-8110 Correct GHA DSL checks

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, bundle/rhpam/manifests/rhpam.kiegroup.org_kogitobuilds.yaml, bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoinfras.yaml, bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoruntimes.yaml, bundle/rhpam/manifests/rhpam.kiegroup.org_kogitosupportingservices.yaml, bundle/rhpam/metadata/annotations.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitobuilds.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoinfras.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoruntimes.yaml, config/crd/rhpam/bases/rhpam.kiegroup.org_kogitosupportingservices.yaml, config/rbac/rhpam/role.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
=> updade bundle to 7.13.1-2

bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
=> updade bundle to 8.0.1-2

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manager/rhpam/kustomization.yaml, version/rhpam/version.go
- [] You've tested the new feature/bug fix in an actual OpenShift cluster
<details>
<summary>
</summary>
</details>
=> [1.13.x][KIECLOUD-656] - Prepare RHPAM branches for 7.13.2 

bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, config/manager/bamoe/kustomization.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue][KIECLOUD-656] - Prepare BAMOE branches for 8.0.2

bamoe-image-bundle.yaml, bamoe-image-prod.yaml, bamoe-image.yaml, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml
<details>
<summary>
</summary>
</details>
=> [1.13.x-blue][KIECLOUD-656] update modules to version 8.0.2

.ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary>
</details>
=> KOGITO-8062 DSL: Refactor environments and export to config

.github/pull_request_template.md, .github/workflows/pr-backporting.yml
Following https://github.com/kiegroup/kogito-pipelines/pull/743
<details>
<summary>
</summary>
</details>
=> Automated pull request backporting workflow

test/features/deploy_kogito_runtime.feature, test/pkg/framework/grafana.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.32.x] Fix from release 1.32.0

test/pkg/framework/grafana.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x] BDD: update grafana image

test/features/deploy_kogito_runtime.feature, test/pkg/framework/grafana.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Fixes from Release 1.32.0

test/pkg/installers/amqstreams_installer.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x] BDD: AMQ streams 2.2

test/pkg/framework/grafana.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x-blue] Updated grafana image

test/pkg/installers/amqstreams_installer.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x-blue] BDD: AMQ streams 2.2

.ci/jenkins/Jenkinsfile.setup-branch
https://issues.redhat.com/browse/KOGITO-8393
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> KOGITO-8393 Clean release notes on branching

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.setup-branch
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Pipelines: Update Cekit path

cmd/kogito/command/test/common.go, core/client/client.go, core/infrastructure/mongodb/v1/mongodbcommunity_types.go, core/kogitoinfra/infinispan_reconciler.go, core/kogitoinfra/infinispanconfig_reconciler.go, core/kogitoinfra/infinispanconfig_reconciler_test.go, core/kogitoservice/kogito_service.go, core/test/mock_svc.go, test/pkg/installers/infinispan_installer.go, test/pkg/installers/keycloak_installer.go
https://issues.redhat.com/browse/KOGITO-8495
Please review and merge
- https://github.com/kiegroup/kogito-pipelines/pull/769
- https://github.com/kiegroup/kogito-docs/pull/279
- https://github.com/kiegroup/kogito-images/pull/1403
- https://github.com/kiegroup/kogito-runtimes/pull/2734
- https://github.com/kiegroup/drools/pull/4910
- https://github.com/kiegroup/kogito-examples/pull/1534
- https://github.com/kiegroup/kogito-apps/pull/1589
- https://github.com/kiegroup/kogito-operator/pull/1349
=> [KOGITO-8495] Bump quarkus version to 2.16.0.Final

RELEASE_NOTES.md, bamoe-operator.yaml, bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, config/manager/bamoe/kustomization.yaml, version/rhpam/version.go
Signed-off-by: Your Name <fspolti@redhat.com>
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to …
=> [KIECLOUD-687] - Prepare the BAMOE branches for the 8.0.3 release

core/infrastructure/reconciliation_error.go, core/kogitobuild/utils.go, core/kogitoinfra/infinispanconfig_reconciler.go, core/kogitoinfra/infraproperties_reconciler.go, core/kogitoinfra/kafkaconfig_reconciler.go, core/kogitoinfra/mongodbconfig_reconciler.go, core/kogitoservice/config_reconciler.go, core/kogitoservice/status_test.go, hack/go-lint.sh, revive.toml
https://issues.redhat.com/browse/KOGITO-8598
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [KOGITO-8598] Golint deprecated migrated to revive

hack/build-osbs.sh, modules/org.kie.kogito.rhpam.builder/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml, rhpam-image-bundle.yaml, rhpam-image-prod.yaml, rhpam-image.yaml
Signed-off-by: desmax74 <mdessi@redhat.com>
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [KIECLOUD-663] Create pipeline for rhpam-kogito operator

hack/build-osbs.sh
See:https://issues.redhat.com/browse/KIECLOUD-664
Signed-off-by: desmax74 <mdessi@redhat.com>
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., …
=> [KEICLOUD-664]Create pipeline for bamoe-kogito operator

Makefile.rhpam, hack/build-osbs.sh
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [KIECLOUD-692] - Update the target dist-git branch with the new ones

.ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.promote
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> KIECLOUD-688 Use rhel8 for podman jobs

core/kogitoinfra/infinispan_reconciler.go, core/kogitoinfra/infinispancredential_reconciler_test.go, hack/clean-cluster-operators.sh
https://issues.redhat.com/browse/KOGITO-8708
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.34.x] [KOGITO-8708] Infinispan corrections

core/kogitoinfra/infinispan_reconciler.go, core/kogitoinfra/infinispancredential_reconciler_test.go, hack/clean-cluster-operators.sh, test/features/install_dataindex.feature
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Corrections from 1.34 release

test/features/keycloak.feature
Due to incompatiblity with new Keycloak operator ...
https://issues.redhat.com/browse/KOGITO-8751
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., …
=> KOGITO-8751 BDD: Disable keycloak testing

.ci/jenkins/Jenkinsfile.setup-branch
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Correct Setup Branch job

test/features/deploy_kogito_runtime.feature, test/features/install_dataindex.feature
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.35.x] Fix BDD tests based on release

test/features/deploy_kogito_runtime.feature, test/features/install_dataindex.feature
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Fix BDD tests based on release (#1408)

bamoe-operator.yaml, bundle/app/manifests/kogito-operator.clusterserviceversion.yaml, bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, config/manager/app/manager.yaml, config/manager/bamoe/manager.yaml, kogito-operator.yaml
See:https://issues.redhat.com/browse/RHPAM-4629
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to …
=> [RHPAM-4629] RHPAM Kogito Operator 7.x installation is failing with OOMKilled and CrashLoopBackOff

bundle/app/manifests/kogito-operator.clusterserviceversion.yaml, bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manager/app/manager.yaml, config/manager/rhpam/manager.yaml, kogito-operator.yaml, rhpam-operator.yaml
See:https://issues.redhat.com/browse/RHPAM-4629
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to …
=> [RHPAM-4629] RHPAM Kogito Operator 7.x installation is failing with OOMKilled and CrashLoopBackOff 

rhpam-image.yaml
Fixes ERROR Found multiple container definitions ([{'image_build_method': 'imagebuilder', 'platforms': {'only': ['x86_64', 'ppc64le']}}, {'image_build_method': 'imagebuilder', 'platforms': {'only': ['x86_64']}}])
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format …
=> [KIECLOUD-694] - fixes duplicated item in the rhpam-image.yaml

Makefile.rhpam
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [KIECLOUD-694] - add missing osbs assume yes flag

rhpam-image-bundle.yaml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [KIECLOUD-702] - RHPAM Kogito Operator - Upgrade OCP EUS to version 4.10

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, rhpam-operator.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [7.13.2-x] [KIECLOUD-708] - Prepare RHPAM Kogito Operator for CVEs respin

bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [KIECLOUD-708] - Prepare BAMOE Operator for CVEs respin

apis/go.mod, apis/go.sum
Fixes:
- https://github.com/kiegroup/kogito-operator/security/dependabot/46
- https://github.com/kiegroup/kogito-operator/security/dependabot/45
- https://github.com/kiegroup/kogito-operator/security/dependabot/42
- https://github.com/kiegroup/kogito-operator/security/dependabot/40
- https://github.com/kiegroup/kogito-operator/security/dependabot/38
- https://github.com/kiegroup/kogito-operator/security/dependabot/47
- https://github.com/kiegroup/kogito-operator/security/dependabot/43
<details>
<summary>
</summary>
* <b>Run RHPAM operator BDD …
=> [RHPAM-4665] - [Kogito] Address the security alerts from Dependabot

apis/go.mod, apis/go.sum
fixes:
- https://github.com/kiegroup/kogito-operator/security/dependabot/44
- https://github.com/kiegroup/kogito-operator/security/dependabot/41
- https://github.com/kiegroup/kogito-operator/security/dependabot/39
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format …
=> [RHPAM-4665] - Kogito] Address the security alerts from Dependabot

.ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/dsl/jobs.groovy
This is the nightly responsibility
https://issues.redhat.com/browse/KOGITO-8981
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/932
- https://github.com/kiegroup/kogito-runtimes/pull/2926
- https://github.com/kiegroup/kogito-apps/pull/1693
- https://github.com/kiegroup/kogito-examples/pull/1633
- https://github.com/kiegroup/kogito-images/pull/1487
- https://github.com/kiegroup/kogito-operator/pull/1453
- https://github.com/kiegroup/kogito-serverless-operator/pull/89
- https://github.com/kiegroup/kogito-docs/pull/327
=> KOGITO-8981 Setup branch should not deploy

.github/dependabot.yml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x-next][KIECLOUD-707] - Enable dependabot for 1.13.x-next branch

test/features/deploy_kogito_build.feature
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x] BDD tests: native S2I disabled

test/features/deploy_kogito_build.feature
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1458
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-blue] BDD tests: native S2I disabled (#1458)

test/features/deploy_kogito_build.feature
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1458
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-next] BDD tests: native S2I disabled (#1458)

test/features/deploy_kogito_build.feature
cherry-pick: https://github.com/kiegroup/kogito-operator/pull/1458
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-blue-next] BDD tests: native S2I disabled (#1458)

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.profiling
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> CI: Update nodes to rhel8

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile-rhpam
Related to https://github.com/kiegroup/kogito-pipelines/pull/978
=> Update PR Jenkins node label

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.examples-images.deploy, .ci/jenkins/Jenkinsfile.examples-images.promote, .ci/jenkins/Jenkinsfile.profiling, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/scripts/helper.groovy, .github/workflows/Kogito-Operator-PR-Check.yaml, .github/workflows/Kogito-Operator-Unit-tests.yaml
Follow-up on https://github.com/kiegroup/kogito-operator/pull/1475
=> CI: RHEL8 migration corrections

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, version/rhpam/version.go
Cherry-picks: https://github.com/kiegroup/kogito-operator/pull/1493
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-next][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin

bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x-blue][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin

bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, version/rhpam/version.go
Cherry-picks https://github.com/kiegroup/kogito-operator/pull/1495
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-blue-next][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin

.ci/jenkins/scripts/helper.groovy
https://issues.redhat.com/browse/KOGITO-9616
Similar to https://github.com/kiegroup/kogito-runtimes/pull/3017
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be …
=> KOGITO-9616 Improve release notes

.ci/jenkins/scripts/helper.groovy
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> CI: Fix create release

test/features/deploy_kogito_runtime.feature, test/features/install_dataindex.feature
https://issues.redhat.com/browse/KOGITO-8435
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> KOGITO-8435 Remove useless persistence profile

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manager/rhpam/kustomization.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x-next] prepare Kogito RHPAM for 7.13.4 release

modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.builder/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml, rhpam-image-bundle.yaml, rhpam-image-prod.yaml, rhpam-image.yaml, rhpam-operator.yaml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Preparing to 7.13.4

.ci/jenkins/dsl/jobs.groovy, .github/workflows/jenkins-tests-PR.yml
Never used/maintained
https://issues.redhat.com/browse/KOGITO-9725
- https://github.com/kiegroup/kogito-pipelines/pull/1044
- https://github.com/kiegroup/kogito-runtimes/pull/3180
- https://github.com/kiegroup/kogito-apps/pull/1839
- https://github.com/kiegroup/kogito-examples/pull/1769
- https://github.com/kiegroup/kogito-images/pull/1672
- https://github.com/kiegroup/kogito-operator/pull/1514
=> KOGITO-9725 DSL cleanup: Remove 'kogito-bdd' check

.ci/jenkins/Jenkinsfile.promote
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.43.x] Fix promote pipeline

bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, config/manifests/bamoe/bases/bamoe-kogito-operator.clusterserviceversion.yaml
Jira: https://issues.redhat.com/browse/KIECLOUD-732
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR …
=> [1.13.x-blue][KIECLOUD-732] add BAMOE subscription

.github/dependabot.yml, .github/workflows/jenkins-tests-PR.yml, bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manager/rhpam/kustomization.yaml, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.builder/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml, rhpam-image-bundle.yaml, rhpam-image-prod.yaml, rhpam-image.yaml, rhpam-operator.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Merge next on release

.github/dependabot.yml, .github/workflows/jenkins-tests-PR.yml, bamoe-image-bundle.yaml, bamoe-image-prod.yaml, bamoe-image.yaml, bamoe-operator.yaml, bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml, config/manager/bamoe/kustomization.yaml, config/manifests/bamoe/bases/bamoe-kogito-operator.clusterserviceversion.yaml, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> 1.13.x blue merge

bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml, config/manager/rhpam/kustomization.yaml, modules/org.kie.kogito.rhpam.builder.prod/module.yaml, modules/org.kie.kogito.rhpam.builder/module.yaml, modules/org.kie.kogito.rhpam.bundleinstall/module.yaml, rhpam-image-bundle.yaml, rhpam-image-prod.yaml, rhpam-image.yaml, rhpam-operator.yaml, version/rhpam/version.go
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> [1.13.x-next][KIECLOUD-735] - Prepare RHPAM repositories for 7.13.5 release

hack/run-tests.sh, test/pkg/config/config.go, test/pkg/framework/maven.go
Changes references to JBoss Nexus to Apache Nexus.
=> [kie-issues#628] Change JBoss Nexus to Apache Nexus.
